---
sidebar: sidebar 
permalink: concept_asset_user_data_section.html 
summary: 자산 페이지의 사용자 데이터 섹션에서는 현재 자산에 주석이나 애플리케이션을 할당할 수 있습니다. 
keywords: asset page, user data, applications, annotations 
---
= 사용자 데이터 섹션
:hardbreaks:
:allow-uri-read: 


[role="lead"]
자산 페이지의 사용자 데이터 섹션에는 애플리케이션 및 주석과 같은 사용자 정의 데이터가 표시되고 이를 변경할 수 있습니다.



== 사용자 데이터 섹션을 사용하여 응용 프로그램을 할당하거나 수정합니다.

테넌트에서 실행되는 애플리케이션을 특정 자산(호스트, 가상 머신, 볼륨, 내부 볼륨, Q트리, 하이퍼바이저)에 할당할 수 있습니다.  사용자 데이터 섹션에서는 자산에 할당된 애플리케이션을 추가, 변경 또는 제거할 수 있습니다.  볼륨을 제외한 모든 자산 유형에 대해 두 개 이상의 애플리케이션을 할당할 수 있습니다.

.단계
. 다음 중 하나를 수행하여 자산 페이지를 찾으세요.
+
.. 자산 목록을 쿼리한 다음 목록에서 하나를 선택합니다.
.. 대시보드에서 자산 이름을 찾아 클릭합니다.
.. 검색을 수행하고 결과에서 자산을 선택하세요.
+
자산 페이지가 표시됩니다.  이 페이지의 사용자 데이터 섹션에는 현재 할당된 애플리케이션이나 주석이 표시됩니다.





할당된 애플리케이션을 변경하거나 애플리케이션 하나 또는 추가 애플리케이션을 할당하려면 *애플리케이션* 목록을 드롭다운하고 자산에 할당하려는 애플리케이션을 선택합니다.  애플리케이션을 검색하려면 입력하거나 목록에서 애플리케이션을 선택할 수 있습니다.

애플리케이션을 제거하려면 애플리케이션 목록을 드롭다운하여 해당 애플리케이션의 선택을 취소하세요.



== 사용자 데이터 섹션을 사용하여 주석을 할당하거나 수정합니다.

기업 요구 사항에 맞게 데이터를 추적하기 위해 Data Infrastructure Insights 사용자 정의할 때 주석이라는 특수 메모를 정의하고 자산에 할당할 수 있습니다.  자산 페이지의 사용자 데이터 섹션에는 자산에 할당된 주석이 표시되며 해당 자산에 할당된 주석을 변경할 수도 있습니다.

.단계
. 자산에 주석을 추가하려면 자산 페이지의 사용자 데이터 섹션에서 *+주석*을 클릭합니다.
. 목록에서 주석을 선택하세요.
. 값을 클릭하고 선택한 주석 유형에 따라 다음 중 하나를 수행합니다.
+
.. 주석 유형이 목록, 날짜 또는 부울인 경우 목록에서 값을 선택합니다.
.. 주석 유형이 텍스트인 경우 값을 입력합니다.


. Save를 클릭합니다.


주석이 자산에 할당됩니다.  나중에 쿼리를 사용하여 주석으로 자산을 필터링할 수 있습니다.

주석을 할당한 후에 주석의 값을 변경하려면 주석 목록을 드롭다운하여 다른 값을 입력하세요.

주석이 _즉시 새 값 추가_ 옵션이 선택된 목록 유형인 경우 기존 값을 선택하는 것 외에도 새 값을 추가하도록 입력할 수 있습니다.
