---
sidebar: sidebar 
permalink: concept_import_from_dashboard_gallery.html 
summary: 갤러리에서 미리 만들어진 대시보드를 가져와 비즈니스 인사이트를 빠르게 얻거나, 내보낸 사용자 지정 대시보드를 가져와 테넌트 간에 구성을 공유할 수 있습니다. 
keywords: dashboard, gallery, import, export 
---
= 대시보드 가져오기
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
갤러리에서 미리 구성된 대시보드를 사용하여 인프라에 대한 통찰력을 빠르게 얻거나, 다른 테넌트에서 내보낸 사용자 지정 대시보드를 가져올 수 있습니다. 갤러리 대시보드는 환경의 데이터 수집기에 맞춰 특정 비즈니스 질문에 대한 답을 제공하도록 설계되었으며, 내보낸 대시보드를 사용하면 여러 테넌트에서 유용한 구성을 공유할 수 있습니다.



[[importing-from-the-dashboard-gallery]]
== 대시보드 갤러리에서 가져오기

갤러리에서 대시보드를 가져오려면 다음을 수행하세요.

. *관찰성 > 탐색 > 모든 대시보드*를 선택하세요.
. *+대시보드 가져오기*를 클릭하고 _갤러리에서 가져오기_를 선택하세요.
+
사용자 환경의 데이터 수집기를 기반으로 *추천 대시보드* 목록이 표시됩니다. 대시보드는 AWS, NetApp, Storage, VMware 등 다양한 유형의 객체와 관련된 질문에 답하는 데 도움이 됩니다.

. 목록에서 하나 이상의 대시보드를 선택하고 *대시보드 추가*를 클릭합니다. 이러한 대시보드는 대시보드 목록에 표시됩니다.


추천 대시보드 외에도 현재 데이터와 관련이 없는 *추가 대시보드*를 가져오도록 선택할 수도 있습니다.  예를 들어, 현재 스토리지 데이터 수집기가 설치되어 있지 않지만 나중에 구성할 계획이라면 스토리지 관련 대시보드를 가져오는 것을 선택할 수 있습니다.  이러한 대시보드는 표시될 수 있지만 최소한 하나의 스토리지 데이터 수집기가 구성될 때까지 관련 데이터가 표시되지 않을 수 있습니다.

대시보드 갤러리에서 가져오기는 관리자 또는 계정 소유자 역할을 가진 사용자에게만 제공됩니다.



[[importing-an-exported-dashboard]]
== 내보낸 대시보드 가져오기

대시보드를 *내보내려면* 관찰 가능성 > 탐색 > 모든 대시보드* 페이지에서 대시보드 오른쪽에 있는 메뉴를 클릭하고 _내보내기_를 선택합니다. 여러 대시보드를 선택하고 _대량 작업_ 드롭다운에서 _내보내기_를 선택할 수도 있습니다. 대시보드는 로컬 시스템의 .ZIP 파일로 저장됩니다.

대시보드를 *가져오려면* 원하는 테넌트로 이동하여 다음을 수행하세요.

. *관찰성 > 탐색 > 모든 대시보드*를 선택하세요.
. *+대시보드 가져오기*를 클릭하고 _파일에서 가져오기_를 선택합니다. 이전에 내보낸 파일의 .ZIP을 선택하세요. 대시보드가 가져와져 대시보드 목록에 표시됩니다. 기존 대시보드와 동일한 이름의 대시보드를 가져오는 경우 대시보드 이름에 "(2)"가 추가됩니다.

