---
sidebar: sidebar 
permalink: concept_cs_event_rate_checker.html 
summary: SVM 이벤트 속도 검사기를 사용하여 NFS/SMB 이벤트 속도를 측정하고 워크로드 보안 데이터 수집기를 배포하기 전에 최적의 에이전트 크기를 결정하십시오. 
keywords: event, checker, rate, sizing, cloud secure 
---
= SVM 이벤트 비율 검사기(에이전트 크기 조정 가이드)
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
이벤트 비율 검사기는 ONTAP SVM 데이터 수집기를 설치하기 전에 SVM에서 NFS/SMB 결합 이벤트 비율을 검사하여 하나의 에이전트 머신이 모니터링할 수 있는 SVM의 수를 확인하는 데 사용됩니다.  이벤트 비율 검사기를 크기 조정 가이드로 사용하여 보안 환경을 계획하세요.

에이전트는 최대 50개의 데이터 수집기를 지원할 수 있습니다.



== 요구 사항:

* 클러스터 IP
* 클러스터 관리자 사용자 이름 및 비밀번호



NOTE: 이 스크립트를 실행할 때 이벤트 비율을 결정하는 SVM에 대해 ONTAP SVM 데이터 수집기가 실행되어서는 안 됩니다.

단계:

. CloudSecure의 지침에 따라 에이전트를 설치하세요.
. 에이전트가 설치되면 sudo 사용자로 _server_data_rate_checker.sh_ 스크립트를 실행합니다.
+
 /opt/netapp/cloudsecure/agent/install/svm_event_rate_checker.sh
. 이 스크립트를 사용하려면 Linux 시스템에 _sshpass_가 설치되어 있어야 합니다.  설치하는 방법은 두 가지가 있습니다.
+
.. 다음 명령을 실행하세요.
+
 linux_prompt> yum install sshpass
.. 그래도 작동하지 않으면 웹에서 Linux 머신에 _sshpass_를 다운로드하고 다음 명령을 실행하세요.
+
 linux_prompt> rpm -i sshpass


. 메시지가 표시되면 올바른 값을 입력하세요.  아래 예를 참조하세요.
. 스크립트를 실행하는 데 약 5분이 걸립니다.
. 실행이 완료되면 스크립트는 SVM에서 이벤트 비율을 인쇄합니다.  콘솔 출력에서 SVM당 이벤트 비율을 확인할 수 있습니다.
+
 “Svm svm_rate is generating 100 events/sec”.


각 Ontap SVM 데이터 수집기는 단일 SVM과 연결될 수 있습니다. 즉, 각 데이터 수집기는 단일 SVM이 생성하는 이벤트 수만큼 수신할 수 있습니다.

다음 사항을 명심하세요.

A) 이 표를 일반적인 사이즈 가이드로 활용하세요.  최대 50개까지 지원되는 데이터 수집기 수를 늘리려면 코어 수 및/또는 메모리 수를 늘릴 수 있습니다.

|===


| 에이전트 머신 구성 | SVM 데이터 수집기 수 | 에이전트 머신이 처리할 수 있는 최대 이벤트 속도 


| 4코어, 16GB | 10명의 데이터 수집가 | 20K 이벤트/초 


| 4코어, 32GB | 20명의 데이터 수집가 | 20K 이벤트/초 
|===
B) 총 이벤트를 계산하려면 해당 에이전트의 모든 SVM에 대해 생성된 이벤트를 추가합니다.

C) 스크립트가 최대 사용량 시간대에 실행되지 않거나 최대 사용량 트래픽을 예측하기 어려운 경우 이벤트 비율 버퍼를 30%로 유지합니다.

B + C는 A보다 작아야 합니다. 그렇지 않으면 에이전트 머신이 모니터링에 실패합니다.

즉, 단일 에이전트 머신에 추가할 수 있는 데이터 수집기의 수는 아래 공식을 따라야 합니다.

 Sum of all Event rate of all Data Source Collectors + Buffer Event rate of 30% < 20000 events/second
를 참조하십시오link:concept_cs_agent_requirements.html["에이전트 요구 사항"] 추가 전제 조건 및 요구 사항은 페이지를 참조하세요.



== 예

각각 초당 100, 200, 300개의 이벤트를 생성하는 3개의 SVMS가 있다고 가정해 보겠습니다.

우리는 다음 공식을 적용합니다:

....
 (100+200+300) + [(100+200+300)*30%] = 600+180 = 780events/sec
780 events/second is < 20000 events/second, so the 3 SVMs can be monitored via one agent box.
....
콘솔 출력은 현재 작업 디렉토리의 __fpolicy_stat_<SVM 이름>.log__ 파일 이름으로 에이전트 머신에서 사용할 수 있습니다.

다음과 같은 경우 스크립트가 잘못된 결과를 제공할 수 있습니다.

* 잘못된 자격 증명, IP 또는 SVM 이름이 제공되었습니다.
* 동일한 이름, 시퀀스 번호 등을 가진 이미 존재하는 fpolicy가 있으면 오류가 발생합니다.
* 스크립트가 실행 중에 갑자기 중단됩니다.


스크립트 실행 예는 아래와 같습니다.

 [root@ci-cs-data agent]# /opt/netapp/cloudsecure/agent/install/svm_event_rate_checker.sh
....
Enter the cluster ip: 10.192.139.166
Enter the username to SSH: admin
Enter the password:
Getting event rate for NFS and SMB events.
Available SVMs in the Cluster
-----------------------------
QA_SVM
Stage_SVM
Qa-fas8020
Qa-fas8020-01
Qa-fas8020-02
audit_svm
svm_rate
vs_new
vs_new2
....
....
-----------------------------
Enter [1/5] SVM name to check (press enter to skip): svm_rate
Enter [2/5] SVM name to check (press enter to skip): audit_svm
Enter [3/5] SVM name to check (press enter to skip):
Enter [4/5] SVM name to check (press enter to skip):
Enter [5/5] SVM name to check (press enter to skip):
Running check for svm svm_rate...
Running check for svm audit_svm...
Waiting 5 minutes for stat collection
Stopping sample svm_rate_sample
Stopping sample audit_svm_sample
fpolicy stats of svm svm_rate is saved in fpolicy_stat_svm_rate.log
Svm svm_rate is generating 100 SMB events/sec and 100 NFS events/sec
Overall svm svm_rate is generating 200 events/sec
fpolicy stats of svm audit_svm is saved in fpolicy_stat_audit_svm.log
Svm audit_svm is generating 200 SMB events/sec and 100 NFS events/sec
Overall svm audit_svm is generating 300 events/sec
....
 [root@ci-cs-data agent]#


== 문제 해결

|===


| 질문 | 답변 


| Workload Security에 대해 이미 구성된 SVM에서 이 스크립트를 실행하면 SVM의 기존 fpolicy 구성을 그대로 사용하나요? 아니면 임시 구성을 설정하고 프로세스를 실행하나요? | 이벤트 비율 검사기는 워크로드 보안을 위해 이미 구성된 SVM에서도 정상적으로 실행될 수 있습니다.  아무런 영향이 없어야 합니다. 


| 스크립트를 실행할 수 있는 SVM의 수를 늘릴 수 있나요? | 네. 스크립트를 편집하여 SVM의 최대 개수를 5개에서 원하는 개수로 변경하기만 하면 됩니다. 


| SVM의 수를 늘리면 스크립트 실행 시간이 늘어나나요? | 아니요. SVM 수가 늘어나더라도 스크립트는 최대 5분 동안 실행됩니다. 


| 스크립트를 실행할 수 있는 SVM의 수를 늘릴 수 있나요? | 네. 스크립트를 편집하여 SVM의 최대 수를 5에서 원하는 수로 변경해야 합니다. 


| SVM의 수를 늘리면 스크립트 실행 시간이 늘어나나요? | 아니요. SVM 수가 늘어나도 스크립트는 최대 5분 동안만 실행됩니다. 


| 기존 에이전트로 이벤트 비율 검사기를 실행하면 어떻게 되나요? | 이미 존재하는 에이전트에 대해 이벤트 비율 검사기를 실행하면 SVM에서 지연 시간이 증가할 수 있습니다.  이벤트 요금 검사가 실행되는 동안 이러한 증가는 일시적인 성격을 갖습니다. 
|===