---
sidebar: sidebar 
permalink: concept_searching_assets.html 
summary: 고급 검색 기술을 사용하면 원하는 자산을 찾는 데 도움이 될 수 있습니다. 
keywords: asset page, objects, search, advanced, alerts 
---
= 자산 및 알림 검색을 위한 힌트와 팁
:hardbreaks:
:allow-uri-read: 


[role="lead"]
모니터링하는 환경에서 데이터나 객체를 검색하기 위해 다양한 검색 기술을 사용할 수 있습니다.

* *와일드카드 검색*
+
* 문자를 사용하여 여러 문자로 구성된 와일드카드 검색을 수행할 수 있습니다.  예를 들어, _applic*n_은 _application_을 반환합니다.

* *검색에 사용된 문구*
+
구는 큰따옴표로 묶인 단어의 집합입니다. 예를 들어, "VNX LUN 5"입니다.  큰따옴표를 사용하면 이름이나 속성에 공백이 포함된 문서를 검색할 수 있습니다.

* *부울 연산자*
+
부울 연산자 OR, AND, NOT을 사용하면 여러 용어를 결합하여 더 복잡한 쿼리를 형성할 수 있습니다.

+
또는

+
OR 연산자는 기본 접속 연산자입니다.

+
두 항 사이에 부울 연산자가 없으면 OR 연산자가 사용됩니다.

+
OR 연산자는 두 용어를 연결하고 두 용어 중 하나라도 문서에 존재하면 일치하는 문서를 찾습니다.

+
예를 들어, _storage OR netapp_은 _storage_ 또는 _netapp_을 포함하는 문서를 검색합니다.

+
대부분의 용어와 일치하는 문서에는 높은 점수가 부여됩니다.

+
그리고

+
AND 연산자를 사용하면 두 검색어가 모두 단일 문서에 존재하는 문서를 찾을 수 있습니다.  예를 들어, _storage AND netapp_은 _storage_와 _netapp_을 모두 포함하는 문서를 검색합니다.

+
AND라는 단어 대신 *&&* 기호를 사용할 수 있습니다.

+
아니다

+
NOT 연산자를 사용하면 NOT 뒤에 있는 용어가 포함된 모든 문서가 검색 결과에서 제외됩니다.  예를 들어, _storage NOT netapp_은 _storage_만 포함하고 _netapp_은 포함하지 않는 문서를 검색합니다.

+
NOT이라는 단어 대신 *!* 기호를 사용할 수 있습니다.



검색은 대소문자를 구분하지 않습니다.



== 색인된 용어를 사용하여 검색

색인된 용어와 더 많이 일치하는 검색은 더 높은 점수를 얻습니다.

검색 문자열은 공백을 기준으로 여러 개의 검색어로 나뉩니다.  예를 들어, 검색 문자열 "storage aurora netapp"은 "storage", "aurora", "netapp"의 세 가지 키워드로 나뉩니다.  세 가지 용어를 모두 사용하여 검색을 수행합니다.  이러한 용어와 대부분 일치하는 문서가 가장 높은 점수를 받습니다.  더 많은 정보를 제공할수록 검색 결과가 더 좋아집니다.  예를 들어, 이름과 모델로 스토리지를 검색할 수 있습니다.

UI는 검색 결과를 카테고리별로 표시하며, 각 카테고리별로 상위 3개 결과가 표시됩니다.  예상했던 객체를 찾지 못한 경우, 검색어에 더 많은 용어를 포함시켜 검색 결과를 개선할 수 있습니다.

다음 표는 검색 문자열에 추가할 수 있는 색인 용어 목록을 제공합니다.

|===
| 범주 | 색인된 용어 


| 스토리지 | "저장소" 이름 공급업체 모델 


| 스토리지풀 | "storagepool" 이름 저장소 이름 저장소 IP 주소 저장소 일련 번호 저장소 공급업체 저장소 모델 모든 관련 내부 볼륨의 이름 모든 관련 디스크의 이름 


| 내부 볼륨 | "internalvolume" 이름 저장소 이름 저장소의 IP 주소 저장소의 일련 번호 저장소 공급업체 저장소 모델 저장소 풀 이름 모든 관련 공유 이름 모든 관련 애플리케이션 이름 


| 용량 | "볼륨" 이름 레이블 모든 내부 볼륨의 이름 스토리지 풀 이름 스토리지 이름 스토리지의 IP 주소 스토리지의 일련 번호 스토리지 공급업체 스토리지 모델 


| 저장 노드 | "storagenode" 이름 저장소의 이름 저장소의 IP 주소 저장소의 일련 번호 저장소 공급업체 저장소 모델 


| 주인 | "호스트" 이름 IP 주소 모든 관련 애플리케이션의 이름 


| 데이터 저장소 | "데이터 저장소" 이름 가상 센터 IP 모든 볼륨의 이름 모든 내부 볼륨의 이름 


| 가상 머신 | "가상 머신" 이름 DNS 이름 IP 주소 호스트 이름 호스트의 IP 주소 모든 데이터 저장소의 이름 모든 연관된 애플리케이션의 이름 


| 스위치(일반 및 NPV) | "스위치" IP 주소 wwn 이름 일련 번호 모델 도메인 ID 패브릭 이름 패브릭 wwn 


| 애플리케이션 | "응용 프로그램" 이름 테넌트 사업 부문 사업 프로젝트 


| 줄자 | "테이프" IP 주소 이름 일련 번호 공급업체 


| 포트 | "포트" wwn 이름 


| 구조 | "패브릭" wwn 이름 


| 스토리지 가상 머신(SVM) | "storagevirtualmachine" 이름 UUID 
|===