---
sidebar: sidebar 
permalink: concept_about_applications.html 
keywords: applications, asset, cost 
summary: 회사 환경에서 사용되는 애플리케이션을 이해하면 자산 사용과 비용을 추적하는 데 도움이 됩니다. 
---
= 애플리케이션별 자산 사용 추적
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
회사 환경에서 사용되는 애플리케이션을 이해하면 자산 사용과 비용을 추적하는 데 도움이 됩니다.

테넌트에서 실행되는 애플리케이션과 관련된 데이터를 추적하려면 먼저 해당 애플리케이션을 정의하고 적절한 자산과 연결해야 합니다.  다음 자산과 애플리케이션을 연결할 수 있습니다: 호스트, 가상 머신, 볼륨, 내부 볼륨, Q트리, 공유 및 하이퍼바이저.

이 주제에서는 마케팅 팀이 Exchange 이메일에 사용하는 가상 머신의 사용량을 추적하는 예를 제공합니다.

테넌트에서 사용되는 애플리케이션을 식별하고 각 애플리케이션을 사용하는 그룹이나 사업부를 기록하려면 다음과 유사한 표를 만들 수 있습니다.

[cols="5*"]
|===


| 거주자 | 사업 분야 | 사업부 | 프로젝트 | 응용 프로그램 


| NetApp | 데이터 저장 | 합법적인 | 특허 | Oracle Identity Manager, Oracle On Demand, PatentWiz 


| NetApp | 데이터 저장 | 마케팅 | 판매 이벤트 | Exchange, Oracle 공유 데이터베이스, BlastOff 이벤트 플래너 
|===
표는 마케팅팀이 Exchange 애플리케이션을 사용하고 있음을 보여줍니다.  Exchange의 가상 머신 활용도를 추적하여 언제 더 많은 스토리지를 추가해야 할지 예측하고자 합니다.  Exchange 애플리케이션을 Marketing의 모든 가상 머신과 연결할 수 있습니다.

. _Exchange_라는 이름의 애플리케이션을 만듭니다.
. *쿼리 > +새 쿼리*로 이동하여 가상 머신에 대한 새 쿼리를 만듭니다(또는 해당되는 경우 기존 VM 쿼리를 선택합니다).
+
마케팅 팀의 VM이 모두 "*mkt*" 문자열을 포함하는 이름을 가지고 있다고 가정하고, "mkt"에 대한 VM 이름을 필터링하는 쿼리를 만듭니다.

. VM을 선택하세요.
. *대량 작업 > 애플리케이션 추가*를 사용하여 VM을 _Exchange_ 애플리케이션과 연결합니다.
. 원하는 애플리케이션을 선택하고 *저장*을 클릭하세요.
. 완료되면 쿼리를 *저장*합니다.

