---
sidebar: sidebar 
permalink: concept_cs_api.html 
keywords: api, access, token, swagger 
summary: 안전한 토큰 기반 인증을 사용하는 REST API를 통해 워크로드 보안 데이터에 액세스하여 CMDB, 티켓팅 시스템 및 기타 엔터프라이즈 애플리케이션과 통합할 수 있습니다. 
---
= 워크로드 보안 API
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Workload Security API를 사용하면 NetApp 고객과 ISV(독립 소프트웨어 공급업체)가 Workload Security를 ​​CMDB나 다른 티켓팅 시스템 등의 다른 애플리케이션과 통합할 수 있습니다.

API 접근을 위한 요구 사항:

* API 액세스 토큰 모델은 액세스 권한을 부여하는 데 사용됩니다.
* API 토큰 관리 작업은 관리자 역할을 가진 Workload Security 사용자가 수행합니다.




== API 문서(Swagger)

최신 API 정보는 Workload Security에 로그인하여 *관리자 > API 액세스*로 이동하면 확인할 수 있습니다.  *API 문서* 링크를 클릭하세요.  API 문서는 Swagger 기반으로, API에 대한 간략한 설명과 사용 정보를 제공하고 테넌트에서 API를 시험해 볼 수 있도록 해줍니다.


NOTE: Forensics Activity API를 호출하는 경우 cloudsecure_forensics.activities.*v2* API를 사용하세요.  이 API에 여러 번 호출하는 경우 호출이 병렬로가 아닌 순차적으로 발생하는지 확인하세요.  여러 개의 병렬 호출로 인해 API 시간이 초과될 수 있습니다.



== API 액세스 토큰

Workload Security API를 사용하기 전에 하나 이상의 *API 액세스 토큰*을 만들어야 합니다.  액세스 토큰은 읽기 권한을 부여합니다.  각 액세스 토큰의 만료일을 설정할 수도 있습니다.

액세스 토큰을 생성하려면:

* *관리자 > API 액세스*를 클릭하세요.
* *+API 액세스 토큰*을 클릭하세요.
* *토큰 이름*을 입력하세요
* *토큰 만료* 지정



NOTE: 귀하의 토큰은 생성 과정에서 클립보드에 복사하고 저장하는 데만 사용할 수 있습니다.  토큰은 생성된 후에는 검색할 수 없으므로 토큰을 복사하여 안전한 곳에 저장하는 것이 좋습니다.  토큰 생성 화면을 닫기 전에 API 액세스 토큰 복사 버튼을 클릭하라는 메시지가 표시됩니다.

토큰을 비활성화, 활성화 및 취소할 수 있습니다.  비활성화된 토큰을 활성화할 수 있습니다.

토큰은 고객 관점에서 API에 대한 일반적인 액세스 권한을 부여하고 자체 테넌트 범위 내에서 API에 대한 액세스를 관리합니다.

사용자가 성공적으로 인증하고 액세스를 승인하면 애플리케이션은 액세스 토큰을 받은 다음 대상 API를 호출할 때 액세스 토큰을 자격 증명으로 전달합니다.  전달된 토큰은 토큰 보유자가 API에 액세스하고 권한 부여 시 부여된 범위에 따라 특정 작업을 수행할 권한이 있음을 API에 알립니다.

액세스 토큰이 전달되는 HTTP 헤더는 *X-CloudInsights-ApiKey:*입니다.

예를 들어, 다음을 사용하여 저장소 자산을 검색합니다.

 curl https://<Workload Security tenant>/rest/v1/cloudsecure/activities -H 'X-CloudInsights-ApiKey: <API_Access_Token>'
여기서 _<API_Access_Token>_은 API 액세스 키 생성 중에 저장한 토큰이고 _<Workload Security Tenant>_는 Workload Security 환경의 테넌트 URL입니다.

자세한 내용은 *관리자 > API 액세스* 아래의 _API 문서_ 링크에서 확인할 수 있습니다.



== API를 통해 데이터를 추출하는 스크립트

Workload Security 에이전트에는 요청된 시간 범위를 더 작은 배치로 나누어 v2 API에 대한 병렬 호출을 용이하게 하는 내보내기 스크립트가 포함되어 있습니다.

스크립트는 _/opt/netapp/cloudsecure/agent/export-script_에 있습니다.  같은 디렉토리에 있는 README 파일에 사용 지침이 나와 있습니다.

스크립트를 호출하는 명령의 예는 다음과 같습니다.

[source]
----
python3 data-export.py --tenant_url <Workload Security tenant> --access_key %ACCESS_KEY% --path_filter "<dir path>" --user_name "<user>" --from_time "01-08-2024 00:00:00" --to_time "31-08-2024 23:59:59" --iteration_interval 12 --num_workers 3
----
주요 매개변수: - `--iteration_interval 12` : 요청된 시간 범위를 12시간 간격으로 나눕니다.  - `--num_workers 3` : 3개의 스레드를 사용하여 이러한 간격을 병렬로 가져옵니다.
