---
sidebar: sidebar 
permalink: cs_notifications_email.html 
summary: 워크로드 보안 경고 알림을 위한 이메일 주소를 추가합니다. 
keywords: email, notifications, alerts, warnings, attacks 
---
= 알림, 경고 및 에이전트/데이터 소스 수집기 상태에 대한 이메일 알림 구성
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Workload Security 알림 수신자를 구성하려면 *관리자 > 알림*을 클릭하고 각 수신자의 해당 섹션에 이메일 주소를 입력합니다.



== 잠재적 공격 경고 및 알림

_잠재적 공격_ 경고 알림을 보내려면 _잠재적 공격 경고 보내기_ 섹션에 수신자의 이메일 주소를 입력하세요.  알림에 대한 모든 작업에 대해 알림 수신자 목록에 이메일 알림이 전송됩니다.

_경고_ 알림을 보내려면 _경고 알림 보내기_ 섹션에 수신자의 이메일 주소를 입력하세요.



== 에이전트 및 데이터 수집기 상태 모니터링

알림을 통해 에이전트와 데이터 소스의 상태를 모니터링할 수 있습니다.

에이전트 또는 데이터 소스 수집기가 작동하지 않을 경우 알림을 받으려면 _데이터 수집 상태 알림_ 섹션에 수신자의 이메일 주소를 입력하세요.

다음 사항을 명심하세요.

* 건강 경고는 담당자/수금원이 최소 1시간 이상 보고를 중단한 후에만 전송됩니다.
* 에이전트나 데이터 수집기가 장시간 연결이 끊긴 경우에도 지정된 24시간 동안 의도된 수신자에게 이메일 알림이 한 번만 전송됩니다.
* 에이전트에 오류가 발생하는 경우, 알림이 한 번 전송됩니다(수집기당 하나가 아님).  이메일에는 영향을 받은 모든 SVM 목록이 포함됩니다.
* Active Directory 수집 실패는 경고로 보고되며, 랜섬웨어 감지에는 영향을 미치지 않습니다.
* 시작하기 설정 목록에 이제 새로운 _이메일 알림 구성_ 단계가 포함되었습니다.




== 에이전트 및 데이터 수집기 업그레이드 알림 수신

* "데이터 수집 건강 알림"에 이메일 ID를 입력하세요.
* "업그레이드 알림 사용" 확인란이 활성화됩니다.
* 에이전트 및 데이터 수집기 업그레이드 이메일 알림은 계획된 업그레이드 1일 전에 해당 이메일 ID로 전송됩니다.




== 문제 해결

|===
| *문제:* | *이걸 시도해보세요:* 


| "데이터 수집기 상태 알림"에 이메일 ID가 있지만 알림을 받지 못하고 있습니다. | 알림 이메일은 NetApp Data Infrastructure Insights 도메인(_accounts@service.cloudinsights.netapp.com_)에서 전송됩니다.  일부 회사는 외부 도메인에서 들어오는 이메일을 차단합니다.  NetApp Data Infrastructure Insights 도메인의 외부 알림이 허용 목록에 포함되어 있는지 확인하세요. 
|===