---
sidebar: sidebar 
permalink: faq-config-support.html 
keywords: FAQ, Frequently asked questions, questions, configuration, 
summary:  
---
= 구성 및 지원 장치
:hardbreaks:
:allow-uri-read: 


[role="lead"]
이 FAQ는 Data Infrastructure Insights 구성과 지원되는 장치에 대한 일반적인 질문에 답변합니다.



== Data Infrastructure Insights 내 환경을 변경합니까?

아니요. Data Infrastructure Insights 사용자 환경에 대한 정보를 수집하는 읽기 전용 도구입니다.  Data Infrastructure Insights 자산이나 구성을 변경하지 않습니다.



== Data Infrastructure Insights 내 기기에 접근하려면 어떤 권한 수준이 필요합니까?

대부분의 경우, 장치가 지원하는 경우 읽기 전용 액세스만 필요합니다.  읽기 전용 액세스를 허용하지 않는 솔루션도 있으므로 적절한 상승된 권한이 필요합니다.



== Data Infrastructure Insights 얼마나 자주 정보를 수집합니까?

Data Infrastructure Insights 일반적으로 5분마다 성능 데이터를 수집하고 30분마다 논리적, 물리적 구조를 발견합니다.  Data Infrastructure Insights 제안된 모범 사례와 확장성에 따라 기본 폴링 간격을 설정하지만 사용자가 이러한 간격을 완벽하게 제어할 수 있도록 허용합니다.



== Data Infrastructure Insights가 내 환경에 어떤 영향을 미치나요?

Data Infrastructure Insights의 에이전트 없는 대역 외 수동 IP 통신은 설정, 유지 관리 및 데이터 센터 생태계에 미치는 영향을 최소화하는 데 도움이 됩니다.  Data Infrastructure Insights의 성과 개발팀은 성과 모니터링 활동에서 데이터 센터의 성과에 미치는 영향을 최소화하기 위해 많은 노력을 기울이고 있습니다.  일반적인 운영 환경에서는 영향이 미미한 것으로 간주되지만, 활용도가 높거나 성능이 낮은 기술 플랫폼에서는 영향이 완화되거나 강화될 수 있습니다.  자세한 내용은 Data Infrastructure Insights 설치 가이드를 참조하세요.



== Data Infrastructure Insights 에서 모든 호스트/VM을 나열하려면 어떻게 해야 하나요?

Data Infrastructure Insights의 위젯과 쿼리 목록 기능을 활용하여 데이터 센터 자산에 대한 인벤토리 스타일 목록을 제공할 수 있습니다.  스핀들과 그 사이의 수많은 구성 요소까지 가상 머신 목록을 모두 쿼리, 위젯, 대시보드 및 데이터웨어하우스 보고에 사용할 수 있으며 RESTful API를 통해 액세스할 수 있습니다.



== Data Infrastructure Insights 관련 비 하이퍼바이저 호스트(예: 물리적 서버)에 대해서도 동일한 유형의 지원을 제공합니까?

VMware와 같은 하이퍼바이저는 ESXI 호스트와 해당 가상 머신(VM)에 대한 자세한 정보를 제공합니다.  물리적 서버의 경우 Data Infrastructure Insights 호스트 HBA까지의 메트릭을 수집합니다.  Data Infrastructure Insights 특허 출원 중인 기술을 사용하여 물리적 서버를 검색하는 고유한 방법을 사용합니다.  저장소 및/또는 스위치가 검색되면 물리적 서버의 호스트 이름이 패브릭 별칭 정보에 포함됩니다.  Data Infrastructure Insights 이러한 호스트 이름을 선택하고 DNS에서 일치시킨 후 자동으로 호스트를 Data Infrastructure Insights 로 가져옵니다.  이 기술을 사용하면 수동 입력 업데이트와 도구 재고 유지 관리의 필요성이 크게 최소화됩니다.



== Data Infrastructure Insights 이기종 환경에서 동일한 장치 메트릭 깊이(패리티)를 제공합니까?

타사 플랫폼과 공급업체 기술 간에는 표준화, 공통성 및 명명법의 정도가 다양합니다.  Data Infrastructure Insights 일관된 프레임워크로 용량 및 성능 정보를 표준화하려고 시도합니다.  IOP, 대기 시간, 원시 용량 등 일부 용량 및 성능 측정 항목은 장치의 카운터에서 기본적으로 제공됩니다.  카운터가 제공되지 않으면 Data Infrastructure Insights 값을 요약하려고 시도할 수 있습니다(예: 기본 볼륨의 IOP 또는 용량을 합산). 둘 다 사용할 수 없는 경우 Data Infrastructure Insights 다양한 계산 알고리즘을 통해 메트릭 값을 도출하려고 시도합니다.  Data Infrastructure Insights 현재 Data Infrastructure Insights 에서 수집하지 않는 추가 지표를 통합하기 위한 일반적인 SNMP 통합 기능을 제공합니다.



== Data Infrastructure Insights 파이버 채널 스위치를 지원합니까?

네. Data Infrastructure Insights 스토리지 자산에서 데이터를 수집하는 것 외에도 테넌트의 Cisco, Brocade 및 QLogic 스위치에서 인벤토리 및 성능 데이터도 수집합니다.



== 전체 인프라의 토폴로지 뷰를 이용할 수 있나요?  Data Infrastructure Insights "종단 간 가시성"을 보여줍니까?

네, Data Infrastructure Insights 논리적 및 물리적 구조를 동적으로 검색하고 매핑하여 컴퓨팅, 패브릭, 가상화 장치 및 백엔드 스토리지의 엔드투엔드 토폴로지 뷰를 대화형으로 제공합니다.  토폴로지 아이콘을 사용하면 영향을 받는 리소스로 빠르게 탐색할 수 있으며 공유 스토리지 환경에서 작업 부하 및 위반 사항을 식별하는 데 도움이 됩니다.
