---
sidebar: sidebar 
permalink: insights_overview.html 
keywords: insight, greedy, degraded, impacted, impacting, impactful, impact, resources, consuming, workload, ttf, time to full, k8s, kubernetes, namespace 
summary: 통찰력을 통해 리소스 사용과 추세를 살펴볼 수 있습니다. 
---
= 통찰력
:hardbreaks:
:allow-uri-read: 


[role="lead"]
통찰력을 통해 리소스 사용량과 그것이 다른 리소스에 미치는 영향, 완료까지 걸리는 시간 분석 등을 살펴볼 수 있습니다.

다양한 통찰력을 얻을 수 있습니다.  *대시보드 > 인사이트*로 이동하여 자세히 알아보세요. 기본 탭에서 활성 인사이트(현재 발생 중인 인사이트)를 볼 수 있고, _비활성 인사이트_ 탭에서 비활성 인사이트를 볼 수 있습니다.  비활성 인사이트는 이전에는 활성화되었지만 더 이상 발생하지 않는 인사이트입니다.



== 인사이트 유형



=== 스트레스 하의 공유 자원

큰 영향을 미치는 작업 부하는 공유 리소스에서 다른 작업 부하의 성능을 저하시킬 수 있습니다.  이로 인해 공유 자원에 부담이 가해집니다.  Data Infrastructure Insights 리소스 포화 상태와 테넌트에 미치는 영향을 조사하는 데 도움이 되는 도구를 제공합니다.link:insights_shared_resources_under_stress.html["자세히 알아보기"]



=== Kubernetes 네임스페이스 공간 부족

Kubernetes 네임스페이스 공간 부족 인사이트는 Kubernetes 네임스페이스에서 공간 부족 위험이 있는 워크로드를 파악하고, 각 공간이 가득 차기까지 남은 일수를 추정하여 보여줍니다.link:insights_k8s_namespaces_running_out_of_space.html["자세히 알아보기"]



=== ONTAP 냉장 보관소 회수

ONTAP 냉장 보관 회복_ 인사이트는 ONTAP 시스템의 볼륨에 대한 냉장 용량, 잠재적 비용/전력 절감 및 권장 작업 항목에 대한 데이터를 제공합니다.link:insights_reclaim_ontap_cold_storage.html["자세히 알아보기"]


NOTE: 이는 _미리보기_ 기능이며, 개선이 진행됨에 따라 시간이 지남에 따라 변경될 수 있습니다. link:/concept_preview_features.html["자세히 알아보기"] Data Infrastructure Insights Preview 기능에 대해 알아보세요.
