---
sidebar: sidebar 
permalink: pre-requisites_for_k8s_operator.html 
keywords: telegraf, installation, install, agent, telegraf agent, kubernetes, eks, operator, k8s 
summary: Data Infrastructure Insights는 Telegraf를 Kubernetes에서 통합 데이터 수집을 위한 에이전트로 지원합니다. 
---
= NetApp Kubernetes 모니터링 운영자를 설치 또는 업그레이드하기 전에
:toc: macro
:hardbreaks:
:toclevels: 2
:allow-uri-read: 
:toc: 
:nofooter: 
:toclevels: 2
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
를 설치 또는 업그레이드하기 전에 이 정보를 link:task_config_telegraf_agent_k8s.html["Kubernetes 모니터링 운영자"]읽으십시오.

|===
| 구성 요소 | 요구 사항 


| Kubernetes 버전 | Kubernetes v1.20 이상 


| Kubernetes 배포 | AWS EKS(Elastic Kubernetes Service) AKS(Google Kubernetes Service) GKE(Google Kubernetes Engine) RKE(Red Hat OpenShift Rancher Kubernetes Engine) VMware Tanzu 


| 리눅스 OS | Data Infrastructure Insights는 Arm64 아키텍처로 실행되는 노드를 지원하지 않습니다. 네트워크 모니터링: Linux 커널 버전 4.18.0 이상을 실행해야 합니다. Photon OS는 지원되지 않습니다. 


| 라벨 | Data Infrastructure Insights는 Kubernetes v1.20 이상 플랫폼에서 다음과 같은 Kubernetes 레이블을 찾는 Kubernetes 노드 선택기를 지정하여 Linux를 실행하는 Kubernetes 노드 모니터링을 지원합니다. Kubernetes.IO/OS=Linux Rancher+Cattle.IO as 오케스트레이션/Kubernetes 플랫폼: cool.IO/OS=Linux 


| 명령 | curl 및 kubectl 명령을 사용할 수 있어야 합니다. 최상의 결과를 얻으려면 이러한 명령을 경로에 추가하십시오. 


| 연결성 | kubettl CLI는 대상 K8s 클러스터와 통신하도록 구성되고 Data Infrastructure Insights 환경에 인터넷에 연결되어 있습니다. 설치하는 동안 프록시 뒤에 있는 경우 작업자 설치 섹션의 지침을 link:task_config_telegraf_agent_k8s.html#configuring-proxy-support["프록시 지원을 구성하는 중입니다"]따르십시오. 정확한 감사 및 데이터 보고를 위해 NTP(Network Time Protocol) 또는 SNTP(Simple Network Time Protocol)를 사용하여 Agent 시스템의 시간을 동기화합니다. 


| 기타 | OpenShift 4.6 이상에서 실행 중인 경우 이 필수 구성 요소가 충족되는지 확인하는 것 외에도 를 따라야 link:task_config_telegraf_agent_k8s.html#openshift-instructions["OpenShift 지침"]합니다. 


| API 토큰 | Operator를 다시 배포하는 경우(예: 업데이트 또는 교체) 새 API 토큰을 생성할 필요가 없습니다. 이전 토큰을 다시 사용할 수 있습니다. 
|===


== 시작하기 전에 유의해야 할 중요 사항

를 <<configuring-proxy-support,프록시>>사용하거나<<using-a-custom-or-private-docker-repository,사용자 지정 리포지토리>>, 를 사용하거나 를 사용하는 경우 <<openshift-instructions,OpenShift>>다음 섹션을 주의 깊게 읽어 보십시오.

에 대해서도 읽어 <<권한,권한>>보세요.



=== 프록시 지원을 구성하는 중입니다

NetApp Kubernetes Monitoring Operator를 설치하기 위해 사용자 환경에서 프록시를 사용할 수 있는 두 가지 위치가 있습니다. 이러한 시스템은 동일하거나 별도의 프록시 시스템일 수 있습니다.

* 설치 코드 스니펫을 실행하는 동안("curl" 사용) 프록시를 사용하여 스니펫이 실행되는 시스템을 Data Infrastructure Insights 환경에 연결해야 합니다
* Data Infrastructure Insights 환경과 통신하는 데 필요한 프록시입니다


둘 중 하나 또는 둘 모두에 프록시를 사용하는 경우 NetApp Kubernetes 운영 모니터를 설치하려면 먼저 프록시가 데이터 인프라 인사이트 환경과 제대로 통신할 수 있도록 구성되었는지 확인해야 합니다. 예를 들어, 운영자를 설치할 서버/VM에서 Data Infrastructure Insights에 액세스하고 Data Infrastructure Insights에서 바이너리를 다운로드할 수 있어야 합니다.

NetApp Kubernetes 운영 모니터를 설치하는 데 사용되는 프록시에 대해 Operator를 설치하기 전에 _http_proxy/https_proxy_environment 변수를 설정하십시오. 일부 프록시 환경에서는 _no_proxy 환경_변수를 설정해야 할 수도 있습니다.

변수를 설정하려면 * NetApp Kubernetes Monitoring Operator를 설치하기 전에 * 시스템에서 다음 단계를 수행하십시오.

. 현재 사용자에 대한 _https_proxy_and/or_http_proxy_environment 변수를 설정합니다.
+
.. 설정 중인 프록시에 인증(사용자 이름/암호)이 없으면 다음 명령을 실행합니다.
+
 export https_proxy=<proxy_server>:<proxy_port>
.. 설정 중인 프록시에 인증(사용자 이름/암호)이 있는 경우 다음 명령을 실행합니다.
+
 export http_proxy=<proxy_username>:<proxy_password>@<proxy_server>:<proxy_port>




Kubernetes 클러스터가 데이터 인프라 인사이트 환경과 통신하는 데 사용되는 프록시의 경우, 이 지침을 모두 읽은 후 NetApp Kubernetes 모니터링 운영자를 설치합니다.

NetApp Kubernetes Monitoring Operator를 구축하기 전에 operator-config.yAML에서 AgentConfiguration의 프록시 섹션을 구성하십시오.

[listing]
----
agent:
  ...
  proxy:
    server: <server for proxy>
    port: <port for proxy>
    username: <username for proxy>
    password: <password for proxy>

    # In the noproxy section, enter a comma-separated list of
    # IP addresses and/or resolvable hostnames that should bypass
    # the proxy
    noproxy: <comma separated list>

    isTelegrafProxyEnabled: true
    isFluentbitProxyEnabled: <true or false> # true if Events Log enabled
    isCollectorsProxyEnabled: <true or false> # true if Network Performance and Map enabled
    isAuProxyEnabled: <true or false> # true if AU enabled
  ...
...
----


=== 사용자 지정 또는 프라이빗 Docker 저장소 사용

기본적으로 NetApp Kubernetes 모니터링 운영자는 Data Infrastructure Insights 저장소에서 컨테이너 이미지를 가져옵니다. 모니터링을 위한 타겟으로 사용되는 Kubernetes 클러스터가 있고 해당 클러스터가 사용자 지정 또는 프라이빗 Docker 저장소 또는 컨테이너 레지스트리에서만 컨테이너 이미지를 풀도록 구성된 경우 NetApp Kubernetes Monitoring Operator가 필요로 하는 컨테이너에 대한 액세스를 구성해야 합니다.

NetApp 모니터링 오퍼레이터 설치 타일에서 "이미지 풀 스니펫"을 실행합니다. 이 명령은 Data Infrastructure Insights 저장소에 로그인하고 운영자의 모든 이미지 종속성을 가져온 다음 Data Infrastructure Insights 저장소에서 로그아웃합니다. 메시지가 표시되면 제공된 리포지토리 임시 암호를 입력합니다. 이 명령은 옵션 기능을 포함하여 오퍼레이터가 사용하는 모든 이미지를 다운로드합니다. 이러한 이미지가 사용되는 기능은 아래를 참조하십시오.

핵심 운영자 기능 및 Kubernetes 모니터링

* NetApp - 모니터링
* kubbe-RBAC-proxy입니다
* Kudbe-state-metrics를 나타냅니다
* 텔레그라프
* distroless-root-user.(거리 없는 루트 사용자


이벤트 로그

* 유창한 비트
* Kubernetes - 이벤트 - 수출자


네트워크 성능 및 맵

* CI-NET-관찰자


회사 정책에 따라 운영 Docker 이미지를 프라이빗/로컬/엔터프라이즈 Docker 저장소로 밀어 넣습니다. 리포지토리에 있는 이러한 이미지에 대한 이미지 태그와 디렉터리 경로가 Data Infrastructure Insights 리포지토리에 있는 이미지와 일치하는지 확인합니다.

운영자 배포에서 모니터링 - 운영자 배포를 편집합니다. YAML을 편집하고 모든 이미지 참조를 수정하여 개인 Docker 저장소를 사용하십시오.

....
image: <docker repo of the enterprise/corp docker repo>/kube-rbac-proxy:<kube-rbac-proxy version>
image: <docker repo of the enterprise/corp docker repo>/netapp-monitoring:<version>
....
operator-config.yAML에서 AgentConfiguration을 편집하여 새로운 Docker 저장소 위치를 반영하십시오. 개인 리포지토리에 대한 새 imagePullSecret을 만듭니다. 자세한 내용은 _https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/_ 참조하십시오

[listing]
----
agent:
  ...
  # An optional docker registry where you want docker images to be pulled from as compared to CI's docker registry
  # Please see documentation for link:task_config_telegraf_agent_k8s.html#using-a-custom-or-private-docker-repository[using a custom or private docker repository].
  dockerRepo: your.docker.repo/long/path/to/test
  # Optional: A docker image pull secret that maybe needed for your private docker registry
  dockerImagePullSecret: docker-secret-name
----


=== OpenShift 지침

OpenShift 4.6 이상에서 실행 중인 경우 _operator-config.yAML_에서 AgentConfiguration을 편집하여 _Privileged_setting을 활성화해야 합니다.

....
# Set runPrivileged to true SELinux is enabled on your kubernetes nodes
runPrivileged: true
....
OpenShift는 일부 Kubernetes 구성 요소에 대한 액세스를 차단할 수 있는 수준 높은 보안을 구현할 수 있습니다.



=== 권한

모니터링 중인 클러스터에 ClusterRole이 없는 사용자 지정 리소스가 포함되어 있는 경우 link:https://kubernetes.io/docs/reference/access-authn-authz/rbac/#aggregated-clusterroles["보려는 애그리게이트"]이벤트 로그를 사용하여 이러한 리소스에 대한 액세스를 운영자에게 수동으로 부여해야 합니다.

. edit_operator-additional-permissions.yaml_를 설치하기 전이나 설치 후 resource_ClusterRole/<namespace>-additional-permissions_를 편집합니다
. 동사 ["get", "watch", "list"]를 사용하여 원하는 apiGroups 및 리소스에 대한 새 규칙을 만듭니다. \https://kubernetes.io/docs/reference/access-authn-authz/rbac/ 를 참조하십시오
. 변경 사항을 클러스터에 적용합니다

