---
sidebar: sidebar 
permalink: pre-requisites_for_k8s_operator.html 
keywords: telegraf, installation, install, agent, telegraf agent, kubernetes, eks, operator, k8s 
summary: Data Infrastructure Insights Kubernetes에서 통합 데이터를 수집하는 에이전트로서 Telegraf를 지원합니다. 
---
= NetApp Kubernetes Monitoring Operator를 설치하거나 업그레이드하기 전에
:hardbreaks:
:allow-uri-read: 
:nofooter: 


[role="lead"]
설치 또는 업그레이드하기 전에 이 정보를 읽으십시오.link:task_config_telegraf_agent_k8s.html["쿠버네티스 모니터링 운영자"] .

|===
| 요소 | 요구 사항 


| 쿠버네티스 버전 | Kubernetes v1.20 이상. 


| 쿠버네티스 배포판 | AWS Elastic Kubernetes Service(EKS) Azure Kubernetes Service(AKS) Google Kubernetes Engine(GKE) Red Hat OpenShift Rancher Kubernetes Engine(RKE) VMware Tanzu 


| 리눅스 운영체제 | Data Infrastructure Insights Arm64 아키텍처로 실행되는 노드를 지원하지 않습니다.  네트워크 모니터링: Linux 커널 버전 4.18.0 이상을 실행해야 합니다.  Photon OS는 지원되지 않습니다. 


| 라벨 | Data Infrastructure Insights 다음 플랫폼에서 Kubernetes 레이블을 찾는 Kubernetes 노드 선택기를 지정하여 Linux를 실행하는 Kubernetes 노드의 모니터링을 지원합니다. Kubernetes v1.20 이상: Kubernetes.io/os = linux Rancher + cattle.io(오케스트레이션/Kubernetes 플랫폼): cattle.io/os = linux 


| 명령 | curl 및 kubectl 명령을 사용할 수 있어야 합니다. 최상의 결과를 얻으려면 이러한 명령을 PATH에 추가하세요. 


| 연결성 | kubectl cli는 대상 K8s 클러스터와 통신하도록 구성되었으며, Data Infrastructure Insights 환경에 인터넷으로 연결됩니다.  설치 중에 프록시 뒤에 있는 경우 다음 지침을 따르세요.link:task_config_telegraf_agent_k8s.html#configuring-proxy-support["프록시 지원 구성"] 운영자 설치 섹션입니다.  정확한 감사 및 데이터 보고를 위해 NTP(Network Time Protocol) 또는 SNTP(Simple Network Time Protocol)를 사용하여 에이전트 컴퓨터의 시간을 동기화하세요. 


| 다른 | OpenShift 4.6 이상을 실행 중인 경우 다음을 따라야 합니다.link:task_config_telegraf_agent_k8s.html#openshift-instructions["OpenShift 지침"] 이러한 전제 조건이 충족되는지 확인하는 것 외에도. 


| API 토큰 | Operator를 다시 배포하는 경우(즉, 업데이트하거나 교체하는 경우) 새로운 API 토큰을 만들 필요가 없습니다. 이전 토큰을 다시 사용할 수 있습니다. 
|===


== 시작하기 전에 주의해야 할 중요한 사항

당신이 ~로 달리고 있다면<<configuring-proxy-support,대리>> , 가지고있다<<using-a-custom-or-private-docker-repository,사용자 정의 저장소>> , 또는 사용 중<<openshift-instructions,오픈시프트>> 다음 섹션을 주의 깊게 읽어보세요.

또한 읽어보세요<<권한,권한>> .



=== 프록시 지원 구성

테넌트에서 프록시를 사용하여 NetApp Kubernetes Monitoring Operator를 설치할 수 있는 두 곳이 있습니다.  이는 동일하거나 별도의 프록시 시스템일 수 있습니다.

* 설치 코드 조각을 실행하는 동안 필요한 프록시("curl" 사용)는 조각이 실행되는 시스템을 Data Infrastructure Insights 환경에 연결합니다.
* 대상 Kubernetes 클러스터가 Data Infrastructure Insights 환경과 통신하는 데 필요한 프록시


이 두 가지 중 하나 또는 둘 다에 프록시를 사용하는 경우 NetApp Kubernetes Operating Monitor를 설치하려면 먼저 프록시가 Data Infrastructure Insights 환경과의 원활한 통신을 허용하도록 구성되어 있는지 확인해야 합니다.  예를 들어, Operator를 설치하려는 서버/VM에서 Data Infrastructure Insights 에 액세스하고 Data Infrastructure Insights 에서 바이너리를 다운로드할 수 있어야 합니다.

NetApp Kubernetes Operating Monitor를 설치하는 데 사용되는 프록시의 경우, Operator를 설치하기 전에 _http_proxy/https_proxy_ 환경 변수를 설정하세요.  일부 프록시 환경에서는 _no_proxy 환경 변수도 설정해야 할 수 있습니다.

변수를 설정하려면 NetApp Kubernetes Monitoring Operator를 설치하기 *전에* 시스템에서 다음 단계를 수행하세요.

. 현재 사용자에 대해 _https_proxy_ 및/또는 _http_proxy_ 환경 변수를 설정합니다.
+
.. 설정 중인 프록시에 인증(사용자 이름/비밀번호)이 없는 경우 다음 명령을 실행합니다.
+
 export https_proxy=<proxy_server>:<proxy_port>
.. 설정 중인 프록시에 인증(사용자 이름/비밀번호)이 있는 경우 다음 명령을 실행하세요.
+
 export http_proxy=<proxy_username>:<proxy_password>@<proxy_server>:<proxy_port>




Kubernetes 클러스터가 Data Infrastructure Insights 환경과 통신하는 데 사용되는 프록시의 경우, 이 지침을 모두 읽은 후 NetApp Kubernetes Monitoring Operator를 설치하세요.

NetApp Kubernetes Monitoring Operator를 배포하기 전에 operator-config.yaml에서 AgentConfiguration의 프록시 섹션을 구성합니다.

[listing]
----
agent:
  ...
  proxy:
    server: <server for proxy>
    port: <port for proxy>
    username: <username for proxy>
    password: <password for proxy>

    # In the noproxy section, enter a comma-separated list of
    # IP addresses and/or resolvable hostnames that should bypass
    # the proxy
    noproxy: <comma separated list>

    isTelegrafProxyEnabled: true
    isFluentbitProxyEnabled: <true or false> # true if Events Log enabled
    isCollectorsProxyEnabled: <true or false> # true if Network Performance and Map enabled
    isAuProxyEnabled: <true or false> # true if AU enabled
  ...
...
----


=== 사용자 정의 또는 개인 Docker 저장소 사용

기본적으로 NetApp Kubernetes Monitoring Operator는 Data Infrastructure Insights 저장소에서 컨테이너 이미지를 가져옵니다.  모니터링 대상으로 Kubernetes 클러스터를 사용하고 해당 클러스터가 사용자 지정 또는 개인 Docker 저장소나 컨테이너 레지스트리에서만 컨테이너 이미지를 가져오도록 구성된 경우 NetApp Kubernetes Monitoring Operator에 필요한 컨테이너에 대한 액세스를 구성해야 합니다.

NetApp Monitoring Operator 설치 타일에서 "이미지 풀 스니펫"을 실행합니다.  이 명령은 Data Infrastructure Insights 저장소에 로그인하고, 운영자에 대한 모든 이미지 종속성을 끌어오고, Data Infrastructure Insights 저장소에서 로그아웃합니다.  메시지가 표시되면 제공된 저장소 임시 비밀번호를 입력하세요.  이 명령은 옵션 기능을 포함하여 운영자가 사용하는 모든 이미지를 다운로드합니다.  이 이미지가 어떤 기능에 사용되는지 아래에서 확인하세요.

핵심 운영자 기능 및 Kubernetes 모니터링

* 넷앱 모니터링
* kube-rbac-프록시
* kube-state-metrics
* 텔레그라프
* distroless-root-user


이벤트 로그

* 유창한 비트
* 쿠버네티스 이벤트 내보내기


네트워크 성능 및 맵

* ci-net-observer


회사 정책에 따라 운영자 Docker 이미지를 개인/로컬/엔터프라이즈 Docker 저장소에 푸시합니다.  저장소에 있는 이미지 태그와 해당 이미지의 디렉토리 경로가 Data Infrastructure Insights 저장소의 이미지 태그와 디렉토리 경로와 일치하는지 확인하세요.

operator-deployment.yaml에서 monitoring-operator 배포를 편집하고 모든 이미지 참조를 수정하여 개인 Docker 저장소를 사용합니다.

....
image: <docker repo of the enterprise/corp docker repo>/kube-rbac-proxy:<kube-rbac-proxy version>
image: <docker repo of the enterprise/corp docker repo>/netapp-monitoring:<version>
....
operator-config.yaml의 AgentConfiguration을 편집하여 새로운 docker repo 위치를 반영합니다.  개인 저장소에 대한 새로운 imagePullSecret을 생성하세요. 자세한 내용은 _https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/_를 참조하세요.

[listing]
----
agent:
  ...
  # An optional docker registry where you want docker images to be pulled from as compared to CI's docker registry
  # Please see documentation for link:task_config_telegraf_agent_k8s.html#using-a-custom-or-private-docker-repository[using a custom or private docker repository].
  dockerRepo: your.docker.repo/long/path/to/test
  # Optional: A docker image pull secret that maybe needed for your private docker registry
  dockerImagePullSecret: docker-secret-name
----


=== OpenShift 지침

OpenShift 4.6 이상을 사용하는 경우 _operator-config.yaml_에서 AgentConfiguration을 편집하여 _runPrivileged_ 설정을 활성화해야 합니다.

....
# Set runPrivileged to true SELinux is enabled on your kubernetes nodes
runPrivileged: true
....
Openshift는 일부 Kubernetes 구성 요소에 대한 액세스를 차단할 수 있는 추가 보안 수준을 구현할 수 있습니다.



=== 권한

모니터링하는 클러스터에 ClusterRole이 없는 사용자 지정 리소스가 포함되어 있는 경우link:https://kubernetes.io/docs/reference/access-authn-authz/rbac/#aggregated-clusterroles["보기 위한 집계"] 이벤트 로그를 통해 이러한 리소스를 모니터링하려면 운영자에게 이러한 리소스에 대한 액세스 권한을 수동으로 부여해야 합니다.

. 설치 전 _operator-additional-permissions.yaml_을 편집하거나 설치 후 리소스 _ClusterRole/<namespace>-additional-permissions_를 편집합니다.
. ["get", "watch", "list"] 동사를 사용하여 원하는 apiGroups 및 리소스에 대한 새 규칙을 만듭니다.  https://kubernetes.io/docs/reference/access-authn-authz/rbac/ 참조하세요.
. 클러스터에 변경 사항을 적용합니다.

