---
settings:
  name: Data Infrastructure Insights
  harmony_integration: maestro
  rss_page: concept_whats_new.html
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: ko-kr,us-en,de-de,es-es,fr-fr,it-it,pt-br,ja-jp,zh-cn,zh-tw
sidebar:
  entries:
  - title: Data Infrastructure Insights 문서
    url: "/index.html"
  - title: 새로운 소식
    url: "/concept_whats_new.html"
  - title: Data Infrastructure Insights 등록
    url: "/task_cloud_insights_onboarding_1.html"
  - title: 보안
    entries:
    - title: 보안 관행
      url: "/security_overview.html"
    - title: 우리가 무엇을 저장하고 어디에 저장합니까?
      url: "/security_information_and_region.html"
    - title: 보안 관리 도구
      url: "/security_admin_tool.html"
  - title: 시작하기
    entries:
    - title: 데이터 수집
      entries:
      - title: 개요
        url: "/task_getting_started_with_cloud_insights.html"
      - title: 인수 단위 요구 사항
        url: "/concept_acquisition_unit_requirements.html"
      - title: 수집 단위 구성
        url: "/task_configure_acquisition_unit.html"
      - title: Windows/Linux에서 에이전트 구성
        url: "/task_config_telegraf_agent.html"
      - title: 데이터 수집기 구성
        url: "/task_configure_data_collectors.html"
      - title: 데이터 수집기 인수 상태 확인
        url: "/concept_determining_data_collector_acq_status.html"
      - title: 구성된 데이터 수집기 관리
        url: "/task_view_configured_data_collectors.html"
      - title: 연구 데이터 수집기 오류
        url: "/task_research_failed_collector.html"
    - title: 추천 대시보드 가져오기
      url: "/concept_import_from_dashboard_gallery.html"
    - title: 사용자 계정 및 역할
      url: "/concept_user_roles.html"
  - title: 데이터 수집기 목록
    url: "/data_collector_list.html"
  - title: Data Infrastructure Insights 구독
    url: "/concept_subscribing_to_cloud_insights.html"
  - title: 관찰 가능성
    entries:
    - title: 대시보드 만들기
      entries:
      - title: 대시보드 개요
        url: "/concept_dashboards_overview.html"
      - title: 대시보드의 기능
        url: "/concept_dashboard_features.html"
      - title: 샘플 대시보드
        entries:
        - title: 가상 머신 성능
          url: "/task_dashboard_example_VM_performance.html"
      - title: 대시보드 모범 사례
        url: "/concept_dashboard_best_practices.html"
    - title: 쿼리 작업
      entries:
      - title: 자산 쿼리
        url: "/concept_querying_assets.html"
      - title: 쿼리 생성
        url: "/task_create_query.html"
      - title: 사용 가능한 쿼리 보기
        url: "/task_view_queries.html"
      - title: 쿼리 결과를 .CSV로 내보내기
        url: "/task_export_query_results.html"
      - title: 쿼리 수정 또는 삭제
        url: "/task_modify_delete_query.html"
      - title: 객체에 여러 애플리케이션/주석 할당
        url: "/task_query_assign_multiple_applications.html"
      - title: 테이블 값을 클립보드에 복사
        url: "/task_query_copy_table_values.html"
      - title: 로그 쿼리
        url: "/concept_log_explorer.html"
      - title: 비활성 장치 식별
        url: "/task_identify_inactive_devices.html"
    - title: 통찰력
      entries:
      - title: 개요
        url: "/insights_overview.html"
      - title: 스트레스 하의 공유 자원
        url: "/insights_shared_resources_under_stress.html"
      - title: Kubernetes 네임스페이스 공간 부족
        url: "/insights_k8s_namespaces_running_out_of_space.html"
      - title: ONTAP 냉장 보관소 회수
        url: "/insights_reclaim_ontap_cold_storage.html"
    - title: 모니터 및 알림
      entries:
      - title: 모니터 만들기
        url: "/task_create_monitor.html"
      - title: 알림 보기 및 관리
        url: "/task_view_and_manage_alerts.html"
      - title: 알림 수신자 구성
        url: "/concept_notifications_email.html"
      - title: 이상 감지 모니터
        url: "/concept_anomaly_detection.html"
      - title: 시스템 정의 모니터
        url: "/task_system_monitors.html"
      - title: 알림 수신자 구성
        url: "/concept_notifications_email.html"
      - title: 웹훅 알림
        entries:
        - title: 웹훅 구성
          url: "/task_create_webhook.html"
        - title: 웹훅 예시 - Discord
          url: "/task_webhook_example_discord.html"
        - title: 웹훅 예제 - PagerDuty
          url: "/task_webhook_example_pagerduty.html"
        - title: 웹훅 예시 - Slack
          url: "/task_webhook_example_slack.html"
        - title: 웹훅 예제 - 팀
          url: "/task_webhook_example_teams.html"
    - title: 주석 작업
      entries:
      - title: 주석 정의
        url: "/task_defining_annotations.html"
      - title: 주석 사용
        url: "/task_create_annotation.html"
      - title: 주석 규칙 사용
        url: "/task_create_annotation_rules.html"
      - title: API를 사용하여 주석 가져오기
        url: "/task_annotation_import.html"
    - title: 응용 프로그램 작업
      entries:
      - title: 응용 프로그램 개념
        url: "/concept_about_applications.html"
      - title: 애플리케이션 구성
        url: "/task_create_application.html"
    - title: 자동 장치 해결
      entries:
      - title: 장치 해상도 개요
        url: "/concept_device_resolution_overview.html"
      - title: 장치 확인 규칙
        url: "/task_device_resolution_rules.html"
      - title: 파이버 채널 장치 해상도
        url: "/task_device_resolution_fibre_channel.html"
      - title: IP 장치 해상도
        url: "/task_device_resolution_ip.html"
      - title: 장치 해상도 기본 설정 지정
        url: "/task_device_resolution_preferences.html"
      - title: 정규 표현식 예제
        url: "/concept_device_resolution_regex_examples.html"
    - title: 자산 페이지 정보
      entries:
      - title: 자산 페이지 개요
        url: "/concept_asset_page_overview.html"
      - title: 객체에 대한 컨텍스트 내 필터링
        url: "/concept_in_context_filters.html"
      - title: 스토리지 가상화
        url: "/concept_storage_virtualization.html"
      - title: 자산 검색을 위한 힌트와 팁
        url: "/concept_searching_assets.html"
    - title: 데이터 분석
      entries:
      - title: SAN 분석기
        url: "/san_analyzer_overview.html"
      - title: VM 분석기
        url: "/vm_analyzer_overview.html"
      - title: 인프라 상태 모니터링
        url: "/monitor_infrastructure_health.html"
    - title: 보고
      entries:
      - title: 보고 개요
        url: "/reporting_overview.html"
      - title: 보고 사용자 역할
        url: "/reporting_user_roles.html"
      - title: 미리 정의된 보고서 사용
        url: "/reporting_predefined_reports.html"
      - title: 스토리지 관리자 대시보드
        url: "/reporting_storage_manager_dashboard.html"
      - title: 예제 보고서 만들기
        url: "/reporting_create_example.html"
      - title: 보고서 관리
        url: "/reporting_managing_reports.html"
      - title: 사용자 정의 보고서
        url: "/reporting_creating_custom_reports.html"
      - title: 데이터 모델
        url: "/reporting_creating_custom_reports.html#reporting-data-models"
      - title: 보고 데이터베이스 API
        url: "/reporting_querying_database.html"
      - title: 데이터 보존
        url: "/reporting_data_retention.html"
      - title: 스키마 다이어그램
        url: "/reporting_schema_diagrams.html"
      - title: 스키마 테이블
        url: "/reference_schemas.html"
  - title: 쿠버네티스
    entries:
    - title: 쿠버네티스 개요 페이지
      url: "/kubernetes_landing_page.html"
    - title: 운영자를 설치하거나 업그레이드하기 전에
      url: "/pre-requisites_for_k8s_operator.html"
    - title: 모니터링 운영자 설치
      url: "/task_config_telegraf_agent_k8s.html"
    - title: 모니터링 운영자 옵션
      url: "/telegraf_agent_k8s_config_options.html"
    - title: 쿠버네티스 클러스터 페이지
      url: "/kubernetes_cluster_detail.html"
    - title: 네트워크 모니터링 및 맵
      url: "/concept_kubernetes_network_monitoring_and_map.html"
    - title: 분석 변경
      url: "/kubernetes_change_analytics.html"
  - title: ONTAP 필수 사항
    url: "/concept_ontap_essentials.html"
  - title: 관리 및 기타 작업
    entries:
    - title: API 작업
      url: "/API_Overview.html"
    - title: 환경 모니터링
      entries:
      - title: 감사 이벤트
        url: "/concept_audit.html"
      - title: TTL 및 다운샘플링
        url: concept_ttl_and_downsampling.html
      - title: Active IQ
        url: "/concept_activeiq.html"
  - title: 워크로드 보안
    entries:
    - title: 워크로드 보안에 관하여
      url: "/cs_intro.html"
    - title: 시작하기
      entries:
      - title: 워크로드 보안 시작하기
        url: "/task_cs_getting_started.html"
      - title: 워크로드 보안 에이전트 요구 사항
        url: "/concept_cs_agent_requirements.html"
      - title: 워크로드 보안 에이전트 구성
        url: "/task_cs_add_agent.html"
      - title: 워크로드 보안 에이전트 삭제
        url: "/task_cs_delete_agent.html"
      - title: AD 디렉터리 수집기 구성
        url: "/task_config_user_dir_connect.html"
      - title: LDAP 디렉토리 수집기 구성
        url: "/task_config_user_dir_connect_ldap.html"
      - title: ONTAP SVM 데이터 수집기 ​​구성
        url: "/task_add_collector_svm.html"
      - title: SVM 수집기 문제 해결
        url: "/troubleshooting_collector_svm.html"
      - title: Cloud ONTAP 데이터 수집기 ​​구성
        url: "/task_config_cs_incloud.html"
      - title: 워크로드 보안 사용자 관리
        url: "/task_cs_user_management.html"
      - title: 이벤트 요금 확인기(에이전트 규모 가이드)
        url: "/concept_cs_event_rate_checker.html"
    - title: 알림
      url: "/cs_alert_data.html"
    - title: 법의학
      entries:
      - title: 활동 포렌식 - 모든 활동
        url: "/forensic_activity_history.html"
      - title: 사용자
        url: "/forensic_user_overview.html"
    - title: 자동 응답 정책
      url: "/cs_automated_response_policies.html"
    - title: 허용된 파일 유형 정책
      url: "/ws_allowed_file_types.html"
    - title: ONTAP 자율형 랜섬웨어 보호 통합
      url: "/concept_cs_integration_with_ontap_arp.html"
    - title: ONTAP 액세스 거부 통합
      url: "/concept_ws_integration_with_ontap_access_denied.html"
    - title: 사용자 액세스 차단
      url: "/cs_restrict_user_access.html"
    - title: 랜섬웨어 공격 시뮬레이션
      url: "/concept_cs_attack_simulator.html"
    - title: 이메일 알림
      url: "/cs_notifications_email.html"
    - title: 웹훅 알림
      entries:
      - title: 웹후크 만들기
        url: "/ws_notifications_using_webhooks.html"
      - title: Discord 웹훅 예시
        url: "/ws_webhook_example_discord.html"
      - title: PagerDuty 웹훅 예제
        url: "/ws_webhook_example_pagerduty.html"
      - title: Slack 웹훅 예제
        url: "/ws_webhook_example_slack.html"
      - title: 팀 웹훅 예시
        url: "/ws_webhook_example_teams.html"
    - title: 워크로드 보안 API
      url: "/concept_cs_api.html"
    - title: SVM 수집기 문제 해결
      url: "/troubleshooting_collector_svm.html"
  - title: 문제 해결
    entries:
    - title: 일반적인 문제 해결
      url: "/task_troubleshooting_general_problems.html"
    - title: Linux Acquisition Unit 문제 해결
      url: "/task_troubleshooting_linux_acquisition_unit_problems.html"
    - title: Windows Acquisition Unit 문제 해결
      url: "/task_troubleshooting_windows_acquisition_unit_problems.html"
    - title: 데이터 수집기 오류 조사
      url: "/task_research_failed_collector.html"
  - title: 데이터 수집기 지원 매트릭스
    url: "/reference_data_collector_support_matrix.html"
  - title: 참조 및 지원
    entries:
    - title: 지원 요청
      url: "/concept_requesting_support.html"
    - title: 데이터 수집기 참조 - 인프라
      entries:
      - title: 공급업체 참조 개요
        url: "/concept_data_collector_reference.html"
      - title: AWS
        url: "/task_dc_amazon_ec2.html"
      - title: Amazon FSx for NetApp ONTAP
        url: "/task_dc_na_amazon_fsx.html"
      - title: 하늘빛
        url: "/task_dc_ms_azure.html"
      - title: 브로드컴
        entries:
        - title: Brocade 네트워크 어드바이저
          url: "/task_dc_brocade_bna.html"
        - title: 파이버 채널 스위치
          url: "/task_dc_brocade_fc_switch.html"
        - title: Brocade FOS REST
          url: "/task_dc_brocade_rest.html"
      - title: Cisco
        url: "/task_dc_cisco_fc_switch.html"
      - title: 코히시티 스마트파일
        url: "/task_dc_cohesity_smartfiles.html"
      - title: 작은 골짜기
        entries:
        - title: XC 시리즈
          url: "/task_dc_dell_xc_series.html"
      - title: 델 EMC
        entries:
        - title: 데이터 도메인
          url: "/task_dc_emc_datadomain.html"
        - title: ECS
          url: "/task_dc_emc_ecs.html"
        - title: 파워스케일
          url: "/task_dc_emc_isilon.html"
        - title: Isilon / PowerScale REST
          url: "/task_dc_emc_isilon_rest.html"
        - title: 파워스토어
          url: "/task_dc_emc_powerstore.html"
        - title: 리커버포인트
          url: "/task_dc_emc_recoverpoint.html"
        - title: 스케일IO
          url: "/task_dc_emc_scaleio.html"
        - title: 유니티(VNXe)
          url: "/task_dc_emc_unity.html"
        - title: VMAX/파워맥스
          url: "/task_dc_emc_vmax_powermax.html"
        - title: VNX 블록(클라리온)
          url: "/task_dc_emc_vnx_block.html"
        - title: VNX 파일(Celerra)
          url: "/task_dc_emc_vnx_file.html"
        - title: VNX 통합
          url: "/task_dc_emc_vnx_unified.html"
        - title: 브이플렉스
          url: "/task_dc_emc_vplex.html"
        - title: 익스트림IO
          url: "/task_dc_emc_xio.html"
      - title: 후지쯔
        url: "/task_dc_fujitsu_eternus.html"
      - title: Google
        url: "/task_dc_google_cloud.html"
      - title: Google Cloud NetApp Volumes
        url: "/task_dc_google_cloud_netapp_volumes.html"
      - title: HP 엔터프라이즈
        entries:
        - title: HP Alletra 9000 및 Primera
          url: "/task_dc_hp_3par.html"
        - title: HP 커맨드 뷰 AE
          url: "/task_dc_hpe_commandview.html"
        - title: HPE 알레트라 6000
          url: "/task_dc_hpe_nimble.html"
      - title: 히타치 데이터 시스템즈
        entries:
        - title: HDS 명령 모음
          url: "/task_dc_hds_commandsuite.html"
        - title: HDS HNAS
          url: "/task_dc_hds_nas.html"
        - title: HDS 운영 센터
          url: "/task_dc_hds_ops_center.html"
      - title: 인피니닷
        url: "/task_dc_infinidat_infinibox.html"
      - title: 화웨이
        url: "/task_dc_huawei_oceanstor.html"
      - title: IBM
        entries:
        - title: 클레버세이프
          url: "/task_dc_ibm_cleversafe.html"
        - title: CS 시리즈
          url: "/task_dc_ibm_cs.html"
        - title: 시스템 스토리지 DS8000 시리즈
          url: "/task_dc_ibm_ds.html"
        - title: 파워VM
          url: "/task_dc_ibm_powervm.html"
        - title: San 볼륨 컨트롤러(SVC)
          url: "/task_dc_ibm_svc.html"
        - title: XIV/A9000
          url: "/task_dc_ibm_xiv.html"
      - title: 레노버
        url: "/task_dc_lenovo.html"
      - title: 마이크로소프트
        entries:
        - title: Azure NetApp Files
          url: "/task_dc_ms_anf.html"
        - title: 하이퍼-V
          url: "/task_dc_ms_hyperv.html"
      - title: NetApp
        entries:
        - title: Cloud Volumes ONTAP
          url: "/task_dc_na_cloud_volumes_ontap.html"
        - title: AWS용 Cloud Volumes 서비스
          url: "/task_dc_na_cloud_volumes.html"
        - title: ONTAP ASA (All-SAN 어레이) r2
          url: "/task_dc_na_ontap_all_san_array.html"
        - title: ONTAP 데이터 관리 소프트웨어
          url: "/task_dc_na_cdot.html"
        - title: ONTAP REST 수집기
          url: "/task_dc_na_ontap_rest.html"
        - title: Data ONTAP 7모드
          url: "/task_dc_na_7mode.html"
        - title: E-시리즈
          url: "/task_dc_na_eseries.html"
        - title: E-시리즈 REST
          url: "/task_dc_netapp_eseries_rest.html"
        - title: NetApp HCI 관리 서버
          url: "/task_dc_na_hci.html"
        - title: SolidFire
          url: "/task_dc_na_solidfire.html"
        - title: StorageGRID
          url: "/task_dc_na_storagegrid.html"
      - title: 뉴타닉스
        url: "/task_dc_nutanix.html"
      - title: 신탁
        url: "/task_dc_oracle_zfs.html"
      - title: 순수한
        url: "/task_dc_pure_flasharray.html"
      - title: 레드햇
        url: "/task_dc_redhat_virtualization.html"
      - title: 루브릭 CDM
        url: "/task_dc_rubrik_cdm.html"
      - title: VMware
        url: "/task_dc_vmware.html"
    - title: 데이터 수집기 참조 - 서비스
      entries:
      - title: 호스트/노드
        url: "/task_config_telegraf_node.html"
      - title: 액티브MQ
        url: "/task_config_telegraf_activemq.html"
      - title: 아파치
        url: "/task_config_telegraf_apache.html"
      - title: 영사
        url: "/task_config_telegraf_consul.html"
      - title: 카우치베이스
        url: "/task_config_telegraf_couchbase.html"
      - title: 카우치DB
        url: "/task_config_telegraf_couchdb.html"
      - title: 도커
        url: "/task_config_telegraf_docker.html"
      - title: 엘라스틱서치
        url: "/task_config_telegraf_elasticsearch.html"
      - title: 플링크
        url: "/task_config_telegraf_flink.html"
      - title: 하둡
        url: "/task_config_telegraf_hadoop.html"
      - title: HAProxy
        url: "/task_config_telegraf_haproxy.html"
      - title: 자바
        url: "/task_config_telegraf_jvm.html"
      - title: 카프카
        url: "/task_config_telegraf_kafka.html"
      - title: 커패시터
        url: task_config_telegraf_kapacitor.html
      - title: 키바나
        url: "/task_config_telegraf_kibana.html"
      - title: 쿠버네티스
        url: "/task_config_telegraf_agent_k8s.html"
      - title: 멤캐시드
        url: "/task_config_telegraf_memcached.html"
      - title: 몽고디비
        url: "/task_config_telegraf_mongodb.html"
      - title: MySQL
        url: "/task_config_telegraf_mysql.html"
      - title: 넷스탯
        url: "/task_config_telegraf_netstat.html"
      - title: 엔진엑스
        url: "/task_config_telegraf_nginx.html"
      - title: 오픈ZFS
        url: task_config_telegraf_openzfs.html
      - title: 포스트그레스큐엘
        url: "/task_config_telegraf_postgresql.html"
      - title: 인형
        url: "/task_config_telegraf_puppetagent.html"
      - title: 레디스
        url: "/task_config_telegraf_redis.html"
      - title: 리씽크DB
        url: task_config_telegraf_rethinkdb.html
      - title: 동물원 관리인
        url: task_config_telegraf_zookeeper.html
    - title: 객체 아이콘 참조
      url: "/reference_object_icons.html"
  - title: 법적 고지 사항
    url: "/legal-notices.html"
