---
sidebar: sidebar 
permalink: reporting_overview.html 
summary: Data Infrastructure Insights 사용하면 데이터에 대한 사전 정의 및 사용자 정의 보고서를 작성할 수 있습니다. 
keywords: reporting, cognos, data warehouse, dwh 
---
= Data Infrastructure Insights 보고 개요
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Data Infrastructure Insights 보고는 사전 정의된 보고서를 보거나 사용자 정의 보고서를 만들 수 있는 비즈니스 인텔리전스 도구입니다.


NOTE: 보고 기능은 Data Infrastructure Insights 에서 사용할 수 있습니다.link:concept_subscribing_to_cloud_insights.html["프리미엄 에디션"] .  보고 기능의 사용 가능 여부는 최소 설치 공간 요구 사항에 따라 결정됩니다. link:https://www.netapp.com/forms/cloud-insights-contact-us/["NetApp 영업 담당자에게 문의하세요."] 자세한 내용은.

Data Infrastructure Insights 보고를 사용하면 다음 작업을 수행할 수 있습니다.

* 미리 정의된 보고서 실행
* 사용자 정의 보고서 만들기
* 보고서 형식 및 전달 방법 사용자 지정
* 자동으로 실행되도록 일정 보고서 작성
* 이메일 보고서
* 데이터의 임계값을 나타내기 위해 색상을 사용하세요


Data Infrastructure Insights Reporting은 요금 청구, 소비 분석, 예측과 같은 분야에 대한 사용자 정의 보고서를 생성하고 다음과 같은 질문에 답하는 데 도움이 될 수 있습니다.

* 내 재고는 얼마나 되나요?
* 내 재고는 어디에 있나요?
* 우리 자산을 사용하는 사람은 누구입니까?
* 사업부에 할당된 저장 공간에 대한 요금 환불은 무엇입니까?
* 추가 저장 용량을 구매해야 하는 시점은 언제인가요?
* 사업부가 적절한 저장 계층에 맞춰 정렬되어 있습니까?
* 한 달, 분기 또는 1년 동안 저장 공간 할당은 어떻게 변합니까?




== Data Infrastructure Insights 보고에 액세스

메뉴에서 *보고서* 링크를 클릭하면 Data Infrastructure Insights Reporting에 액세스할 수 있습니다.

보고 인터페이스로 이동하게 됩니다.  Data Infrastructure Insights 보고 엔진으로 IBM Cognos Analytics를 사용합니다.



== ETL란 무엇인가요?

보고 작업을 할 때 "데이터 웨어하우스"와 "ETL"이라는 용어를 들어보셨을 것입니다.  ETL은 "추출, 변환, 로드"를 의미합니다.  ETL 프로세스는 Data Infrastructure Insights 에서 수집된 데이터를 검색하고, 해당 데이터를 보고에 사용할 수 있는 형식으로 변환합니다.  "데이터웨어하우스"는 보고에 사용할 수 있는 수집된 데이터를 말합니다.

ETL 프로세스에는 다음과 같은 개별 프로세스가 포함됩니다.

* *추출*: Data Infrastructure Insights 에서 데이터를 가져옵니다.
* *변환*: Data Infrastructure Insights 에서 추출된 데이터에 비즈니스 로직 규칙이나 함수를 적용합니다.
* *로드*: 변환된 데이터를 보고에 사용하기 위해 데이터웨어하우스에 저장합니다.

