---
sidebar: sidebar 
permalink: reporting_overview.html 
summary: Data Infrastructure Insights를 통해 데이터에 대해 사전 정의된 맞춤형 보고를 제공합니다. 
keywords: reporting, cognos, data warehouse, dwh 
---
= Data Infrastructure Insights 보고 개요
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Data Infrastructure Insights 보고는 사전 정의된 보고서를 보거나 사용자 지정 보고서를 생성할 수 있는 비즈니스 인텔리전스 툴입니다.


NOTE: 보고 기능은 Data Infrastructure Insights에서 사용할 수 link:concept_subscribing_to_cloud_insights.html["Premium Edition을 참조하십시오"]있습니다. 보고 기능을 사용할 수 있는지 여부는 최소 설치 공간 요구 사항에 따라 달라집니다. link:https://www.netapp.com/forms/cloud-insights-contact-us/["NetApp 영업 담당자에게 문의하세요."] 자세한 내용은.

Data Infrastructure Insights 보고를 통해 다음 작업을 수행할 수 있습니다.

* 미리 정의된 보고서를 실행합니다
* 사용자 지정 보고서를 만듭니다
* 보고서의 형식 및 전달 방법을 사용자 지정합니다
* 보고서가 자동으로 실행되도록 예약합니다
* 이메일 보고서
* 색상을 사용하여 데이터의 임계값을 표시합니다


Data Infrastructure Insights Reporting은 비용 청구, 소비 분석 및 예측과 같은 영역에 대한 사용자 지정 보고서를 생성할 수 있으며 다음과 같은 질문에 대한 답변에 도움이 될 수 있습니다.

* 보유하고 있는 재고는 무엇입니까?
* 내 재고는 어디에 있습니까?
* 누가 우리의 자산을 사용하고 있습니까?
* 비즈니스 유닛에 할당된 스토리지에 대한 비용청구는 무엇입니까?
* 추가 스토리지 용량을 구입할 때까지 얼마나 걸립니까?
* 사업부가 적절한 스토리지 계층에 맞게 조정됩니까?
* 월, 분기 또는 연도별로 스토리지 할당이 어떻게 변경됩니까?




== Data Infrastructure Insights 보고 액세스

메뉴에서 * Reports * 링크를 클릭하여 Data Infrastructure Insights Reporting에 액세스할 수 있습니다.

보고 인터페이스로 이동합니다. Data Infrastructure Insights는 보고 엔진에 IBM Cognos Analytics를 사용합니다.



== ETL란 무엇입니까?

보고 작업 시 "데이터 웨어하우스" 및 "ETL"이라는 용어를 듣게 됩니다. ETL은 "추출, 변환 및 로드"를 의미합니다. ETL 프로세스는 Data Infrastructure Insights에서 수집된 데이터를 검색하여 데이터를 Reporting에서 사용할 형식으로 변환합니다. "데이터 웨어하우스"는 보고에 사용할 수 있는 수집된 데이터를 말합니다.

ETL 프로세스는 다음과 같은 개별 프로세스를 포함합니다.

* * Extract *: Data Infrastructure Insights에서 데이터를 가져옵니다.
* * Transform *: Data Infrastructure Insights에서 추출되는 데이터에 비즈니스 로직 규칙 또는 함수를 적용합니다.
* * Load * (로드 *): 변환된 데이터를 보고에서 사용할 데이터 웨어하우스로 저장합니다.

