---
sidebar: sidebar 
permalink: reporting_creating_custom_reports.html 
summary: '보고서 작성 도구를 사용하여 사용자 정의("임시") 보고서 만들기' 
keywords: reporting, cognos, data warehouse, dwh, ad-hoc, custom 
---
= 사용자 정의 보고서 만들기
:hardbreaks:
:allow-uri-read: 


[role="lead"]
보고서 작성 도구를 사용하여 사용자 정의 보고서를 만들 수 있습니다.  보고서를 만든 후에는 저장하고 정기적으로 실행할 수 있습니다.  보고서 결과는 자동으로 본인과 다른 사람에게 이메일로 전송될 수 있습니다.


NOTE: 보고 기능은 Data Infrastructure Insights 에서 사용할 수 있습니다.link:concept_subscribing_to_cloud_insights.html["프리미엄 에디션"] .

이 섹션의 예제에서는 모든 Data Infrastructure Insights Reporting 데이터 모델에 사용할 수 있는 다음 프로세스를 보여줍니다.

* 보고서로 답변해야 할 질문 식별
* 결과를 뒷받침하는 데 필요한 데이터 결정
* 보고서에 대한 데이터 요소 선택


사용자 정의 보고서를 디자인하기 전에 몇 가지 필수 작업을 완료해야 합니다.  이러한 사항을 완료하지 않으면 보고서가 부정확하거나 불완전할 수 있습니다.

예를 들어, 장치 식별 프로세스를 완료하지 않으면 용량 보고서가 정확하지 않습니다.  또는 주석(예: 계층, 사업부, 데이터 센터) 설정을 완료하지 않으면 사용자 지정 보고서가 도메인 전체의 데이터를 정확하게 보고하지 않거나 일부 데이터 포인트에 대해 "해당 없음"을 표시할 수 있습니다.

보고서를 디자인하기 전에 다음 작업을 완료하세요.

* 모두 구성link:task_configure_data_collectors.html["데이터 수집기"] 제대로.
* 테넌트의 장치와 리소스에 주석(예: 계층, 데이터 센터, 사업부)을 입력합니다.  Data Infrastructure Insights Reporting은 과거 정보를 수집하므로 보고서를 생성하기 전에 주석을 안정화하는 것이 좋습니다.




== 보고서 생성 프로세스

맞춤형(임시 보고서라고도 함) 보고서를 만드는 과정에는 여러 가지 작업이 포함됩니다.

* 보고서의 결과를 계획하세요.
* 결과를 뒷받침하는 데이터를 확인하세요.
* 데이터가 포함된 데이터 모델(예: 청구 데이터 모델, 재고 데이터 모델 등)을 선택합니다.
* 보고서의 데이터 요소를 선택합니다.
* 선택적으로 보고서 결과를 서식 지정, 정렬 및 필터링합니다.




=== 사용자 정의 보고서 결과 계획

보고서 작성 도구를 열기 전에 보고서에서 원하는 결과를 계획하는 것이 좋습니다.  보고서 작성 도구를 사용하면 보고서를 쉽게 만들 수 있으며 많은 계획이 필요하지 않을 수도 있습니다. 하지만 보고서 요청자에게 보고서 요구 사항에 대한 감을 잡는 것이 좋습니다.

* 답하고 싶은 질문을 정확하게 파악하세요. 예를 들어:
+
** 남은 용량은 얼마입니까?
** 사업부별 환불 비용은 얼마입니까?
** 각 사업부가 적절한 스토리지 계층에 정렬되도록 하기 위해 계층별 용량은 어떻게 됩니까?
** 전력 및 냉방 요구 사항을 어떻게 예측할 수 있나요?  (리소스에 주석을 추가하여 사용자 정의 메타데이터를 추가합니다.)


* 답변을 뒷받침하는 데 필요한 데이터 요소를 확인하세요.
* 답변에서 보고 싶은 데이터 간의 관계를 파악하세요.  질문에 비논리적인 관계를 포함하지 마세요. 예를 들어, "용량과 관련된 포트를 보고 싶습니다."
* 데이터에 필요한 계산을 식별합니다.
* 결과를 제한하기 위해 어떤 유형의 필터링이 필요한지 결정합니다.
* 현재 데이터나 과거 데이터를 사용해야 하는지 확인하세요.
* 특정 대상에게만 데이터를 제공하기 위해 보고서에 대한 액세스 권한을 설정해야 하는지 확인하세요.
* 보고서가 어떻게 배포될지 확인하세요.  예를 들어, 정해진 일정에 따라 이메일로 보내야 할까요, 아니면 팀 콘텐츠 폴더 영역에 포함해야 할까요?
* 보고서를 누가 관리할지 결정합니다.  이는 디자인의 복잡성에 영향을 미칠 수 있습니다.
* 보고서의 모형을 만듭니다.




=== 보고서 디자인을 위한 팁

보고서를 디자인할 때 도움이 될 만한 몇 가지 팁이 있습니다.

* 현재 데이터나 과거 데이터를 사용해야 하는지 결정하세요.
+
대부분의 보고서는 Data Infrastructure Insights 에서 사용 가능한 최신 데이터만 보고하면 됩니다.

* Data Infrastructure Insights 보고는 용량 및 성능에 대한 과거 정보를 제공하지만, 인벤토리에 대한 정보는 제공하지 않습니다.
* 모든 사람이 모든 데이터를 볼 수 있습니다. 하지만 특정 대상에게만 데이터를 제한해야 할 수도 있습니다.
+
다양한 사용자에 대한 정보를 세분화하려면 보고서를 만들고 해당 보고서에 대한 액세스 권한을 설정할 수 있습니다.





== 보고 데이터 모델

Data Infrastructure Insights 에는 미리 정의된 보고서를 선택하거나 사용자 정의 보고서를 직접 만들 수 있는 여러 가지 데이터 모델이 포함되어 있습니다.

각 데이터 모델에는 간단한 데이터 마트와 고급 데이터 마트가 포함되어 있습니다.

* 간단한 데이터 마트는 가장 일반적으로 사용되는 데이터 요소에 대한 빠른 액세스를 제공하며 데이터 웨어하우스 데이터의 마지막 스냅샷만 포함합니다. 과거 데이터는 포함되지 않습니다.
* 고급 데이터 마트는 단순 데이터 마트에서 사용 가능한 모든 값과 세부 정보를 제공하며 과거 데이터 값에 대한 액세스도 포함합니다.




=== 용량 데이터 모델

저장 용량, 파일 시스템 활용도, 내부 볼륨 용량, 포트 용량, Qtree 용량, 가상 머신(VM) 용량에 대한 질문에 답할 수 있습니다.  용량 데이터 모델은 여러 용량 데이터 모델을 위한 컨테이너입니다.  다음 데이터 모델을 사용하여 다양한 유형의 질문에 답하는 보고서를 만들 수 있습니다.



==== 스토리지 및 스토리지 풀 용량 데이터 모델

스토리지 및 스토리지 풀을 포함한 스토리지 용량 리소스 계획에 대한 질문에 답할 수 있으며, 물리적 스토리지 풀 데이터와 가상 스토리지 풀 데이터가 모두 포함됩니다.  이 간단한 데이터 모델을 사용하면 시간에 따른 계층 및 데이터 센터별 스토리지 풀의 용량 사용량과 관련된 질문에 답하는 데 도움이 될 수 있습니다.  용량 보고를 처음 사용하는 경우 이 데이터 모델이 더 간단하고 타겟팅된 데이터 모델이므로 이 데이터 모델로 시작하는 것이 좋습니다.  이 데이터 모델을 사용하면 다음과 유사한 질문에 답할 수 있습니다.

* 물리적 저장 공간의 80% 용량 임계값에 도달하는 예상 날짜는 언제인가요?
* 주어진 계층의 어레이에 대한 물리적 저장 용량은 얼마입니까?
* 제조업체, 제품군, 데이터 센터별로 저장 용량은 어떻게 되나요?
* 모든 계층의 어레이에서 스토리지 활용 추세는 어떻게 됩니까?
* 가장 활용도가 높은 상위 10개 스토리지 시스템은 무엇입니까?
* 스토리지 풀의 스토리지 활용 추세는 어떻습니까?
* 이미 얼마나 많은 용량이 할당되어 있나요?
* 할당 가능한 용량은 얼마입니까?




==== 파일 시스템 활용 데이터 모델

이 데이터 모델은 파일 시스템 수준에서 호스트의 용량 활용도에 대한 가시성을 제공합니다.  관리자는 파일 시스템별로 할당되고 사용된 용량을 결정하고, 파일 시스템 유형을 파악하고, 파일 시스템 유형별 추세 통계를 파악할 수 있습니다.  이 데이터 모델을 사용하여 다음 질문에 답할 수 있습니다.

* 파일 시스템의 크기는 얼마입니까?
* 데이터는 어디에 보관되며, 어떻게 액세스합니까? 예를 들어 로컬인가요, 아니면 SAN인가요?
* 파일 시스템 용량의 과거 추세는 무엇입니까?  그러면 이를 바탕으로 미래의 수요에 대해 무엇을 예상할 수 있을까요?




==== 내부 볼륨 용량 데이터 모델

내부 볼륨 사용 용량, 할당된 용량 및 시간 경과에 따른 용량 사용량에 대한 질문에 답할 수 있습니다.

* 어떤 내부 볼륨의 활용도가 사전 정의된 임계값보다 높습니까?
* 추세를 기준으로 볼 때 어떤 내부 볼륨이 용량 부족 위험에 처해 있습니까?  8 내부 볼륨의 사용된 용량과 할당된 용량은 어떻게 됩니까?




==== 포트 용량 데이터 모델

시간에 따른 스위치 포트 연결, 포트 상태, 포트 속도에 대한 질문에 답할 수 있습니다.  새로운 스위치 구매를 계획하는 데 도움이 되는 다음과 같은 질문에 답할 수 있습니다. 데이터 센터, 스위치 공급업체 및 포트 속도에 따라 리소스(포트) 가용성을 예측하는 포트 소비 예측을 어떻게 만들 수 있습니까?

* 데이터 속도, 데이터 센터, 공급업체, 호스트 및 스토리지 포트 수를 고려할 때 어떤 포트에서 용량이 부족할 가능성이 높습니까?
* 시간 경과에 따른 스위치 포트 용량 추세는 어떻게 되나요?
* 포트 속도는 어떻게 되나요?
* 어떤 유형의 항구 용량이 필요하며, 어떤 조직이 특정 항구 유형이나 공급업체를 고갈시키려고 하는가?
* 해당 용량을 구매하고 사용할 수 있게 하는 최적의 시기는 언제인가요?




==== Qtree 용량 데이터 모델

시간 경과에 따른 Qtree 활용도(사용된 용량 대비 할당된 용량 등의 데이터 포함) 추세를 파악할 수 있습니다.  다양한 차원(예: 사업체, 애플리케이션, 계층, 서비스 수준)별로 정보를 볼 수 있습니다.  이 데이터 모델을 사용하여 다음 질문에 답할 수 있습니다.

* Qtree의 사용 용량은 애플리케이션이나 비즈니스 엔터티별로 설정된 제한과 어떻게 다릅니까?
* 사용된 용량과 여유 용량의 추세는 어떻게 되는지 알아보고 용량 계획을 세우세요.
* 어떤 사업체가 가장 많은 용량을 사용하고 있나요?
* 어떤 애플리케이션이 가장 많은 용량을 소모합니까?




==== VM 용량 데이터 모델

가상 환경과 용량 사용량을 보고할 수 있습니다.  이 데이터 모델을 사용하면 시간 경과에 따른 VM 및 데이터 저장소의 용량 사용량 변화를 보고할 수 있습니다.  데이터 모델은 또한 씬 프로비저닝과 가상 머신 차지백 데이터를 제공합니다.

* VM과 데이터 저장소에 프로비저닝된 용량을 기준으로 용량 요금 청구를 어떻게 결정할 수 있나요?
* VM에서 사용되지 않는 용량은 얼마이고, 사용되지 않는 용량 중 빈 용량, 버려진 용량 또는 기타 용량은 얼마입니까?
* 소비 트렌드를 바탕으로 무엇을 구매해야 할까?
* 스토리지 씬 프로비저닝과 중복 제거 기술을 사용하면 어떤 스토리지 효율성을 얻을 수 있나요?


VM 용량 데이터 모델의 용량은 가상 디스크(VMDK)에서 가져옵니다.  즉, VM 용량 데이터 모델을 사용하는 VM의 프로비저닝 크기는 가상 디스크의 크기입니다.  이는 Data Infrastructure Insights 의 가상 머신 보기에서 프로비저닝된 용량과 다릅니다. 이 보기에서는 VM 자체의 프로비저닝된 크기가 표시됩니다.



==== 볼륨 용량 데이터 모델

테넌트의 볼륨에 대한 모든 측면을 분석하고 공급업체, 모델, 계층, 서비스 수준 및 데이터 센터별로 데이터를 구성할 수 있습니다.

버려진 볼륨, 사용되지 않은 볼륨, 보호 볼륨(복제에 사용됨)과 관련된 용량을 볼 수 있습니다.  또한 다양한 볼륨 기술(iSCSI 또는 FC)을 살펴보고, 어레이 가상화 문제에 대해 가상 볼륨과 비가상 볼륨을 비교할 수 있습니다.

이 데이터 모델을 사용하면 다음과 유사한 질문에 답할 수 있습니다.

* 어떤 볼륨의 활용도가 사전 정의된 임계값보다 높습니까?
* 내 데이터 센터의 고아 볼륨 용량 추세는 어떻습니까?
* 내 데이터 센터 용량 중 얼마나 많은 부분이 가상화되거나 씬 프로비저닝되었나요?
* 데이터 센터 용량 중 얼마를 복제를 위해 예약해야 합니까?




=== 환불 데이터 모델

스토리지 리소스(볼륨, 내부 볼륨, Q트리)의 사용된 용량과 할당된 용량에 대한 질문에 답할 수 있습니다.  이 데이터 모델은 호스트, 애플리케이션, 비즈니스 엔터티별 스토리지 용량 청구 및 책임 정보를 제공하며 현재 데이터와 과거 데이터를 모두 포함합니다.  보고서 데이터는 서비스 수준 및 스토리지 계층별로 분류할 수 있습니다.

이 데이터 모델을 사용하면 사업체에서 사용하는 용량을 찾아 요금 청구 보고서를 생성할 수 있습니다.  이 데이터 모델을 사용하면 여러 프로토콜(NAS, SAN, FC, iSCSI 포함)에 대한 통합 보고서를 생성할 수 있습니다.

* 내부 볼륨이 없는 저장소의 경우, 요금 청구 보고서는 볼륨별 요금 청구를 보여줍니다.
* 내부 볼륨이 있는 저장소의 경우:
+
** 사업체가 볼륨에 할당된 경우, 환불 보고서에는 볼륨별 환불이 표시됩니다.
** 사업체가 볼륨에 할당되지 않고 Q트리에 할당된 경우, 차지백 보고서에는 Q트리별 차지백이 표시됩니다.
** 사업체가 볼륨과 Q트리에 할당되지 않은 경우, 차지백 보고서에는 내부 볼륨이 표시됩니다.
** 볼륨, Q트리 또는 내부 볼륨별로 차지백을 표시할지 여부는 각 내부 볼륨별로 결정되므로 동일한 스토리지 풀 내의 서로 다른 내부 볼륨이 서로 다른 수준에서 차지백을 표시할 수 있습니다.




기본 시간 간격이 지나면 용량 사실이 삭제됩니다.  자세한 내용은 데이터 웨어하우스 프로세스를 참조하세요.

차지백 데이터 모델을 사용하는 보고서는 스토리지 용량 데이터 모델을 사용하는 보고서와 다른 값을 표시할 수 있습니다.

* NetApp 스토리지 시스템이 아닌 스토리지 어레이의 경우 두 데이터 모델의 데이터는 동일합니다.
* NetApp 및 Celerra 스토리지 시스템의 경우 Chargeback 데이터 모델은 단일 계층(볼륨, 내부 볼륨 또는 Q트리)을 사용하여 요금을 부과하는 반면, Storage Capacity 데이터 모델은 여러 계층(볼륨 및 내부 볼륨)을 사용하여 요금을 부과합니다.




=== 재고 데이터 모델

호스트, 스토리지 시스템, 스위치, 디스크, 테이프, Q트리, 할당량, 가상 머신 및 서버, 일반 장치 등 인벤토리 리소스에 대한 질문에 답할 수 있습니다.  인벤토리 데이터 모델에는 복제, FC 경로, iSCSI 경로, NFS 경로 및 위반 사항에 대한 정보를 볼 수 있는 여러 하위 마트가 포함되어 있습니다.  인벤토리 데이터 모델에는 과거 데이터가 포함되지 않습니다.  이 데이터로 답할 수 있는 질문

* 내가 가지고 있는 자산은 무엇이고, 어디에 있는가?
* 자산을 사용하는 사람은 누구입니까?
* 내가 가지고 있는 기기의 유형은 무엇이고, 해당 기기의 구성 요소는 무엇입니까?
* OS당 호스트는 몇 개이고, 각 호스트에 포트는 몇 개 있나요?
* 각 데이터 센터에는 공급업체별로 어떤 스토리지 어레이가 있습니까?
* 각 데이터 센터에는 공급업체별로 몇 개의 스위치가 있나요?
* 라이센스가 없는 항구는 몇 개입니까?
* 어떤 공급업체의 테이프를 사용하고 있으며 각 테이프에는 몇 개의 포트가 있습니까? 보고서 작업을 시작하기 전에 모든 일반 장치를 식별했습니까?
* 호스트와 저장 볼륨 또는 테이프 간의 경로는 무엇입니까?
* 일반 장치와 저장 볼륨 또는 테이프 간의 경로는 무엇입니까?
* 각 데이터 센터당 각 유형의 위반 건수는 몇 건입니까?
* 각 복제된 볼륨에 대해 소스 볼륨과 대상 볼륨은 무엇입니까?
* 파이버 채널 호스트 HBA와 스위치 사이에 펌웨어 비호환성이나 포트 속도 불일치가 있습니까?




=== 성능 데이터 모델

볼륨, 애플리케이션 볼륨, 내부 볼륨, 스위치, 애플리케이션, VM, VMDK, ESX 대 VM, 호스트 및 애플리케이션 노드의 성능에 대한 질문에 답할 수 있습니다.  이들 중 다수는 _시간_ 데이터, _일_ 데이터 또는 둘 다를 보고합니다.  이 데이터 모델을 사용하면 여러 유형의 성과 관리 질문에 답하는 보고서를 만들 수 있습니다.

* 특정 기간 동안 사용되거나 접근되지 않은 볼륨이나 내부 볼륨은 무엇입니까?
* (사용되지 않는) 애플리케이션의 저장소에 대한 잠재적인 잘못된 구성을 정확히 지적할 수 있나요?
* 애플리케이션의 전반적인 액세스 동작 패턴은 무엇이었나요?
* 계층화된 볼륨이 주어진 애플리케이션에 적절하게 할당되었습니까?
* 현재 실행 중인 애플리케이션에 성능에 영향을 주지 않고 더 저렴한 스토리지를 사용할 수 있을까요?
* 현재 구성된 저장소에 더 많은 액세스를 생성하는 애플리케이션은 무엇입니까?


스위치 성능 표를 사용하면 다음과 같은 정보를 얻을 수 있습니다.

* 연결된 포트를 통한 호스트 트래픽이 균형을 이루고 있나요?
* 어떤 스위치나 포트에서 오류가 많이 발생합니까?
* 포트 성능을 기준으로 가장 많이 사용되는 스위치는 무엇입니까?
* 포트 성능을 기준으로 볼 때 활용도가 낮은 스위치는 무엇입니까?
* 포트 성능을 기준으로 한 호스트 추세 처리량은 얼마입니까?
* 지정된 호스트, 스토리지 시스템, 테이프 또는 스위치의 지난 X일 동안의 성능 활용률은 얼마입니까?
* 어떤 장치가 특정 스위치에서 트래픽을 생성하고 있습니까?(예: 어떤 장치가 활용도가 높은 스위치를 사용하는 데 관여합니까?)
* 우리 환경에서 특정 사업부의 처리량은 얼마입니까?


디스크 성능 표를 사용하면 다음 정보를 얻을 수 있습니다.

* 디스크 성능 데이터를 기반으로 지정된 스토리지 풀의 처리량은 얼마입니까?
* 가장 많이 사용되는 스토리지 풀은 무엇입니까?
* 특정 저장소의 평균 디스크 사용률은 얼마입니까?
* 디스크 성능 데이터를 기반으로 한 스토리지 시스템이나 스토리지 풀의 사용 추세는 어떻습니까?
* 특정 스토리지 풀의 디스크 사용 추세는 어떻습니까?


VM 및 VMDK 성능 표를 사용하면 다음 정보를 얻을 수 있습니다.

* 내 가상 환경이 최적의 성능을 발휘하고 있나요?
* 어떤 VMDK가 가장 높은 작업 부하를 보고하고 있나요?
* 다양한 데이터 저장소에 매핑된 VMD에서 보고된 성능을 사용하여 재계층화에 대한 결정을 내리려면 어떻게 해야 합니까?


성능 데이터 모델에는 계층의 적합성, 애플리케이션에 대한 스토리지 오류 구성, 볼륨과 내부 볼륨의 마지막 액세스 시간을 결정하는 데 도움이 되는 정보가 포함되어 있습니다.  이 데이터 모델은 응답 시간, IOP, 처리량, 보류 중인 쓰기 수, 액세스 상태와 같은 데이터를 제공합니다.



=== 저장 효율성 데이터 모델

시간 경과에 따른 저장 효율성 점수와 잠재력을 추적할 수 있습니다.  이 데이터 모델은 제공된 용량뿐만 아니라 사용되거나 소비된 양(물리적 측정)에 대한 측정값도 저장합니다.  예를 들어, 씬 프로비저닝이 활성화된 경우 Data Infrastructure Insights 장치에서 얼마나 많은 용량이 사용되는지 표시합니다.  중복 제거가 활성화된 경우의 효율성을 확인하는 데도 이 모델을 사용할 수 있습니다.  Storage Efficiency 데이터 마트를 사용하면 다양한 질문에 답할 수 있습니다.

* 씬 프로비저닝과 중복 제거 기술을 구현한 결과 스토리지 효율성은 어떻게 향상되었습니까?
* 데이터 센터 전체에서 저장 공간은 어떻게 절약되나요?
* 과거 용량 추세를 기준으로 볼 때, 언제 추가 저장 공간을 구매해야 할까요?
* 씬 프로비저닝, 중복 제거와 같은 기술을 활성화하면 용량은 얼마나 증가할까요?
* 저장 용량과 관련하여, 지금 위험에 처해 있나요?




=== 데이터 모델 사실 및 차원 테이블

각 데이터 모델에는 사실 테이블과 차원 테이블이 모두 포함됩니다.

* 팩트 테이블: 수량, 원시 용량, 사용 가능한 용량 등 측정된 데이터를 포함합니다.  차원 테이블에 대한 외래 키를 포함합니다.
* 차원 표: 데이터 센터, 사업부 등 사실에 대한 설명 정보를 포함합니다.  차원은 데이터를 분류하는 구조이며, 종종 계층 구조로 구성됩니다.  차원 속성은 차원 값을 설명하는 데 도움이 됩니다.


보고서에서 열로 표시되는 다양한 차원 속성을 사용하여 데이터 모델에 설명된 각 차원의 데이터에 액세스하는 보고서를 구성합니다.



=== 데이터 모델 요소에 사용되는 색상

데이터 모델 요소의 색상은 각기 다른 의미를 갖습니다.

* 노란색 자산: 측정값을 나타냅니다.
* 노란색이 아닌 자산: 속성을 나타냅니다.  이러한 값은 집계되지 않습니다.




=== 하나의 보고서에서 여러 데이터 모델 사용

일반적으로 보고서당 하나의 데이터 모델을 사용합니다.  하지만 여러 데이터 모델의 데이터를 결합한 보고서를 작성할 수 있습니다.

여러 데이터 모델의 데이터를 결합한 보고서를 작성하려면 기반으로 사용할 데이터 모델 중 하나를 선택한 다음, SQL 쿼리를 작성하여 추가 데이터 마트의 데이터에 액세스합니다.  SQL 조인 기능을 사용하면 다양한 쿼리의 데이터를 단일 쿼리로 결합하여 보고서를 작성하는 데 사용할 수 있습니다.

예를 들어, 각 스토리지 어레이의 현재 용량을 알고 싶고 어레이에 대한 사용자 정의 주석을 캡처하고 싶다고 가정해 보겠습니다.  저장 용량 데이터 모델을 사용하여 보고서를 만들 수 있습니다.  현재 용량 및 차원 테이블의 요소를 사용하고 별도의 SQL 쿼리를 추가하여 인벤토리 데이터 모델의 주석 정보에 액세스할 수 있습니다.  마지막으로, 저장소 이름과 조인 기준을 사용하여 인벤토리 저장소 데이터를 저장소 차원 테이블에 연결하여 데이터를 결합할 수 있습니다.
