---
sidebar: sidebar 
permalink: security_overview.html 
summary: Data Infrastructure Insights 릴리스 수명 주기 전반에 걸쳐 보안 모범 사례를 따릅니다. 
keywords: security, risk, protection 
---
= Data Infrastructure Insights 보안
:hardbreaks:
:allow-uri-read: 


[role="lead"]
NetApp 에서는 제품 및 고객 데이터 보안이 무엇보다 중요합니다.  Data Infrastructure Insights 릴리스 수명 주기 전반에 걸쳐 보안 모범 사례를 준수하여 고객 정보와 데이터가 최상의 방식으로 보호되도록 합니다.



== 보안 개요



=== 물리적 보안

Data Infrastructure Insights 프로덕션 인프라는 Amazon Web Services(AWS)에서 호스팅됩니다.  건물은 물론 문에 사용되는 잠금장치나 열쇠를 포함한 Data Infrastructure Insights 프로덕션 서버에 대한 물리적, 환경적 보안 관련 제어는 AWS에서 관리합니다.  AWS에 따르면 "전문 보안 직원이 비디오 감시, 침입 탐지 시스템 및 기타 전자 수단을 활용하여 경계와 건물 진입 지점 모두에서 물리적 접근을 통제합니다.  권한이 있는 직원은 다중 인증 메커니즘을 활용하여 데이터 센터 바닥에 접근합니다."

Data Infrastructure Insights 다음의 모범 사례를 따릅니다.link:https://aws.amazon.com/compliance/shared-responsibility-model/["공유 책임 모델"] AWS에서 설명했습니다.



=== 제품 보안

Data Infrastructure Insights Agile 원칙에 따라 개발 수명 주기를 따르므로, 더 긴 릴리스 주기를 갖는 개발 방법론에 비해 보안 지향적인 소프트웨어 결함을 더 신속하게 해결할 수 있습니다.  지속적인 통합 방법론을 사용하면 기능적 변화와 보안적 변화에 신속하게 대응할 수 있습니다.  변경 관리 절차와 정책은 변경이 언제, 어떻게 발생하는지 정의하고 프로덕션 환경의 안정성을 유지하는 데 도움이 됩니다.  영향을 미치는 모든 변경 사항은 프로덕션 환경에 출시되기 전에 공식적으로 전달, 조정, 적절한 검토 및 승인을 거칩니다.



=== 네트워크 보안

Data Infrastructure Insights 환경의 리소스에 대한 네트워크 액세스는 호스트 기반 방화벽에 의해 제어됩니다.  각 리소스(예: 부하 분산 장치 또는 가상 머신 인스턴스)에는 해당 리소스가 기능을 수행하는 데 필요한 포트로만 인바운드 트래픽을 제한하는 호스트 기반 방화벽이 있습니다.

Data Infrastructure Insights 침입 탐지 서비스를 포함한 다양한 메커니즘을 사용하여 보안 이상이 있는지 프로덕션 환경을 모니터링합니다.



=== 위험 평가

Data Infrastructure Insights 팀은 공식화된 위험 평가 프로세스를 따라 체계적이고 반복 가능한 방식으로 위험을 식별하고 평가하여 위험 처리 계획을 통해 적절하게 관리할 수 있도록 합니다.



=== 데이터 보호

Data Infrastructure Insights 프로덕션 환경은 모든 서비스와 구성 요소에 대해 여러 가용성 영역을 활용하는 고도로 중복된 인프라에 설정됩니다.  가용성이 높고 중복성이 높은 컴퓨팅 인프라를 활용하는 것과 더불어, 중요 데이터는 정기적으로 백업되고 복원은 주기적으로 테스트됩니다.  공식적인 백업 정책과 절차는 비즈니스 활동 중단으로 인한 영향을 최소화하고, 정보 시스템 장애나 재해의 영향으로부터 비즈니스 프로세스를 보호하며, 시기적절하고 적절하게 재개되도록 보장합니다.



=== 인증 및 액세스 관리

모든 고객이 Data Infrastructure Insights 에 접근하는 것은 https를 통한 브라우저 UI 상호작용을 통해 이루어집니다.  인증은 제3자 서비스인 Auth0를 통해 수행됩니다.  NetApp 이를 모든 클라우드 데이터 서비스의 인증 계층으로 중앙화했습니다.

Data Infrastructure Insights Data Infrastructure Insights 프로덕션 환경에 대한 논리적 액세스를 중심으로 "최소 권한" 및 "역할 기반 액세스 제어"를 포함한 업계 모범 사례를 따릅니다.  접근은 엄격한 필요성에 따라 통제되며 다중 인증 메커니즘을 사용하는 일부 승인된 직원에게만 허가됩니다.



=== 고객 데이터 수집 및 보호

모든 고객 데이터는 공용 네트워크를 통해 전송될 때 암호화되고, 저장될 때도 암호화됩니다.  Data Infrastructure Insights TLS(전송 계층 보안) 및 업계 표준 AES-256 알고리즘을 포함한 기술을 사용하여 시스템의 다양한 지점에서 암호화를 활용하여 고객 데이터를 보호합니다.



=== 고객 프로비저닝 해제

다양한 간격으로 이메일 알림이 발송되어 고객에게 구독 만료를 알립니다.  구독이 만료되면 UI가 제한되고 데이터 수집을 위한 유예 기간이 시작됩니다.  그런 다음 고객에게 이메일을 통해 알림이 전달됩니다.  체험 구독에는 14일의 유예 기간이 적용되고, 유료 구독 계정에는 28일의 유예 기간이 적용됩니다.  유예 기간이 만료되면 고객에게 2일 후에 계정이 삭제된다는 내용의 이메일 알림이 전송됩니다.  유료 고객은 서비스 이용 중단을 직접 요청할 수도 있습니다.

만료된 테넌트와 관련된 모든 고객 데이터는 유예 기간이 끝나거나 고객의 계정 종료 요청이 확인되면 SRE( Data Infrastructure Insights 운영) 팀에서 삭제합니다.  어느 경우든 SRE 팀은 API 호출을 실행하여 계정을 삭제합니다.  API 호출은 테넌트 인스턴스와 모든 고객 데이터를 삭제합니다.  고객 삭제는 동일한 API를 호출하고 고객 테넌트 상태가 "삭제됨"인지 확인하여 검증합니다.



=== 보안 사고 관리

Data Infrastructure Insights NetApp의 제품 보안 사고 대응 팀(PSIRT) 프로세스와 통합되어 알려진 취약점을 찾고, 평가하고, 해결합니다.  PSIRT는 고객 보고서, 내부 엔지니어링, CVE 데이터베이스와 같은 널리 알려진 출처를 포함한 여러 채널에서 취약성 정보를 수집합니다.

Data Infrastructure Insights 엔지니어링 팀에서 문제가 감지되면 해당 팀은 PSIRT 프로세스를 시작하고 문제를 평가하며 잠재적으로 해결합니다.

또한 Data Infrastructure Insights 고객이나 연구원이 Data Infrastructure Insights 제품의 보안 문제를 발견하고 기술 지원팀이나 NetApp 사고 대응팀에 직접 보고할 수도 있습니다.  이런 경우, Data Infrastructure Insights 팀은 PSIRT 프로세스를 시작하고 문제를 평가하며 잠재적으로 해결합니다.



=== 취약점 및 침투 테스트

Data Infrastructure Insights 업계 모범 사례를 따르고 내부 및 외부 보안 전문가와 회사를 활용하여 정기적으로 취약성 및 침투 테스트를 수행합니다.



=== 보안 인식 교육

모든 Data Infrastructure Insights 직원은 개별 역할에 맞게 개발된 보안 교육을 받으며, 이를 통해 각 직원이 해당 역할의 특정 보안 관련 과제를 처리할 수 있도록 준비합니다.



=== 규정 준수

Data Infrastructure Insights 보안, 프로세스 및 서비스에 대한 외부 공인 회계사 회사의 독립적인 제3자 감사 및 검증을 수행하며, 여기에는 SOC 2 감사 완료도 포함됩니다.



=== NetApp 보안 권고

NetApp의 사용 가능한 보안 권고 사항을 볼 수 있습니다.link:https://security.netapp.com/advisory/["여기"] .
