---
sidebar: sidebar 
permalink: task_device_resolution_rules.html 
keywords: Automatic, AR, AHR, Host, automatic device resolution 
summary: 장치 확인 기능은 사용자 환경의 성능과 재고를 정확하게 추적하는 데 도움이 됩니다. 
---
= 장치 해결 규칙
:hardbreaks:
:allow-uri-read: 


[role="lead"]
현재 Data Infrastructure Insights 에서 자동으로 식별되지 않는 호스트, 스토리지 및 테이프를 식별하기 위해 장치 확인 규칙을 만듭니다.  사용자가 만든 규칙은 현재 사용자 환경에 있는 장치를 식별하고, 사용자 환경에 추가되는 유사한 장치도 식별합니다.



== 장치 확인 규칙 만들기

규칙을 만들 때는 먼저 규칙이 실행되는 정보의 출처, 정보 추출에 사용된 방법, 규칙 결과에 DNS 조회를 적용할지 여부를 식별합니다.

[cols="2*"]
|===


| 장치를 식별하는 데 사용되는 소스 | * 호스트에 대한 SRM 별칭 * 내장된 호스트 또는 테이프 이름을 포함하는 저장소 별칭 * 내장된 호스트 또는 테이프 이름을 포함하는 스위치 별칭 * 내장된 호스트 이름을 포함하는 영역 이름 


| 소스에서 장치 이름을 추출하는 데 사용되는 방법 | * 있는 그대로(SRM에서 이름 추출) * 구분 기호 * 정규 표현식 


| DNS 조회 | 호스트 이름을 확인하기 위해 DNS를 사용할지 여부를 지정합니다. 
|===
자동 해결 규칙 탭에서 규칙을 만듭니다.  다음 단계에서는 규칙 생성 프로세스를 설명합니다.

.절차
. *관리 > 장치 해상도*를 클릭하세요.
. *자동 해결 규칙* 탭에서 *+ 호스트 규칙* 또는 *+ 테이프 규칙*을 클릭합니다.
+
*해결 규칙* 화면이 표시됩니다.

+

NOTE: 정규 표현식을 만드는 방법에 대한 도움말과 예제를 보려면 _일치 기준 보기_ 링크를 클릭하세요.

. *유형* 목록에서 식별하려는 장치를 선택하세요.
+
_호스트_ 또는 _테이프_를 선택할 수 있습니다.

. *소스* 목록에서 호스트를 식별하는 데 사용할 소스를 선택합니다.
+
선택한 소스에 따라 Data Infrastructure Insights 다음과 같은 응답을 표시합니다.

+
.. *영역*은 Data Infrastructure Insights 에서 식별해야 하는 영역과 WWN을 나열합니다.
.. *SRM*은 Data Infrastructure Insights 에서 식별해야 하는 식별되지 않은 별칭을 나열합니다.
.. *저장소 별칭*은 Data Infrastructure Insights 에서 식별해야 하는 저장소 별칭 및 WWN을 나열합니다.
.. *스위치 별칭*은 Data Infrastructure Insights 에서 식별해야 하는 스위치 별칭을 나열합니다.


. *방법* 목록에서 호스트를 식별하는 데 사용할 방법을 선택합니다.
+
|===


| 원천 | 방법 


| 에스알엠 | 그대로, 구분 기호, 정규 표현식 


| 저장소 별칭 | 구분 기호, 정규 표현식 


| 별칭 전환 | 구분 기호, 정규 표현식 


| 구역 | 구분 기호, 정규 표현식 
|===
+
** 구분 기호를 사용하는 규칙에는 구분 기호와 호스트 이름의 최소 길이가 필요합니다.  호스트 이름의 최소 길이는 Data Infrastructure Insights 호스트를 식별하는 데 사용해야 하는 문자 수입니다.  Data Infrastructure Insights 이 길이 또는 그보다 긴 호스트 이름에 대해서만 DNS 조회를 수행합니다.
+
구분 기호를 사용하는 규칙의 경우, 입력 문자열은 구분 기호로 토큰화되고, 인접 토큰의 여러 조합을 만들어 호스트 이름 후보 목록이 생성됩니다.  그런 다음 목록을 가장 큰 것부터 가장 작은 것까지 정렬합니다.  예를 들어, _vipsnq03_hba3_emc3_12ep0_의 입력 sring에 대한 목록은 다음과 같습니다.

+
*** vipsnq03_hba3_emc3_12ep0
*** vipsnq03_hba3_emc3
*** hba3 emc3_12ep0
*** vipsnq03_hba3
*** emc3_12ep0
*** hba3_emc3
*** vipsnq03
*** 12ep0
*** emc3
*** hba3


** 정규 표현식을 사용하는 규칙에는 정규 표현식, 형식, 대소문자 구분 선택이 필요합니다.


. *AR 실행*을 클릭하여 모든 규칙을 실행하거나, 버튼의 아래쪽 화살표를 클릭하여 직접 만든 규칙(및 마지막 AR 전체 실행 이후에 만들어진 다른 규칙)을 실행합니다.
+
규칙 실행 결과는 *FC 식별* 탭에 표시됩니다.





== 자동 장치 확인 업데이트 시작

장치 확인 업데이트는 마지막 전체 자동 장치 확인 실행 이후 추가된 수동 변경 사항을 커밋합니다.  업데이트를 실행하면 장치 확인 구성에 대해 새로 입력한 수동 항목만 커밋하고 실행할 수 있습니다.  전체 장치 확인 실행이 수행되지 않습니다.

.절차
. Data Infrastructure Insights 웹 UI에 로그인합니다.
. *관리 > 장치 해상도*를 클릭하세요.
. *기기 해상도* 화면에서 *AR 실행* 버튼의 아래쪽 화살표를 클릭합니다.
. 업데이트를 시작하려면 *업데이트*를 클릭하세요.




== 규칙 지원 수동 식별

이 기능은 알 수 없는 호스트, 스토리지 및 테이프 장치를 해결하기 위해 특정 규칙이나 규칙 목록(일회성 재정렬 여부와 관계 없음)을 실행하려는 특수한 경우에 사용됩니다.

.시작하기 전에
식별되지 않은 장치가 여러 개 있고, 다른 장치를 성공적으로 식별한 규칙도 여러 개 있습니다.


NOTE: 소스에 호스트나 장치 이름의 일부만 포함되어 있는 경우 정규 표현식 규칙을 사용하여 누락된 텍스트를 추가하도록 서식을 지정합니다.

.절차
. Data Infrastructure Insights 웹 UI에 로그인합니다.
. *관리 > 장치 해상도*를 클릭하세요.
. *파이버 채널 식별* 탭을 클릭합니다.
+
시스템은 장치와 해당 해상도 상태를 표시합니다.

. 식별되지 않은 여러 장치를 선택하세요.
. *대량 작업*을 클릭하고 *호스트 해상도 설정* 또는 *테이프 해상도 설정*을 선택합니다.
+
시스템은 장치를 성공적으로 식별한 모든 규칙 목록을 포함하는 식별 화면을 표시합니다.

. 귀하의 필요에 맞게 규칙의 순서를 변경하세요.
+
규칙의 순서는 식별 화면에서 변경되지만 전역적으로 변경되지는 않습니다.

. 귀하의 필요에 맞는 방법을 선택하세요.


Data Infrastructure Insights 메서드가 나타나는 순서대로 호스트 확인 프로세스를 실행합니다. 맨 위에 있는 메서드부터 시작합니다.

적용되는 규칙이 발견되면 규칙 이름이 규칙 열에 표시되고 수동으로 식별됩니다.

관련된:link:task_device_resolution_fibre_channel.html["파이버 채널 장치 해상도"] link:task_device_resolution_ip.html["IP 장치 해상도"] link:task_device_resolution_preferences.html["장치 해상도 기본 설정 지정"]
