---
sidebar: sidebar 
permalink: task_dc_netapp_eseries_rest.html 
keywords: data collector, ontap, clustered ontap, REST 
summary: NetApp E-Series REST 데이터 수집기를 구성합니다. 
---
= NetApp E-Series REST 데이터 수집기
:hardbreaks:
:allow-uri-read: 


[role="lead"]
NetApp E-Series REST 데이터 수집기는 인벤토리, 로그 및 성능 데이터를 수집합니다. 수집기는 동일한 구성을 사용하고 동일한 데이터를 보고하는 펌웨어 7.x+를 지원합니다.  REST 수집기는 스토리지 풀, 디스크 및 볼륨의 암호화 상태, 스토리지 노드 CPU 사용률, 기존 SANtricity E-Series 수집기에서 제공되지 않는 로그 기능을 모니터링합니다.



== 술어

Data Infrastructure Insights REST를 사용하여 NetApp E-Series에서 다음과 같은 인벤토리 정보를 수집합니다. 인수한 각 자산 유형에 대해 해당 자산에 사용되는 가장 일반적인 용어가 표시됩니다. 이 데이터 수집기를 보거나 문제를 해결할 때 다음 용어를 염두에 두십시오.

[cols="2*"]
|===
| 공급업체/모델 용어 | Data Infrastructure Insights 용어 


| 디스크 | 디스크 


| 볼륨 그룹 | 디스크 그룹 


| 스토리지 어레이 | 스토리지 


| 제어 장치 | 저장 노드 


| 볼륨 그룹 | 스토리지 풀 


| 용량 | 용량 
|===
참고: 이는 일반적인 용어 매핑일 뿐이며 이 데이터 수집기의 모든 사례를 나타내지 않을 수 있습니다.



== 요구 사항

* 어레이의 각 컨트롤러의 IP 주소
* 이 수집기는 *기본 REST API 기능*을 갖춘 E-시리즈 모델 배열만 지원합니다.  E-Series 조직은 이전 E-Series 어레이를 위한 오프 어레이 설치 가능 REST API 배포판을 제공합니다. 이 수집기는 해당 시나리오를 지원하지 않습니다.  이전 배열을 사용하는 사용자는 계속해서 Data Infrastructure Insights 사용해야 합니다.link:task_dc_na_eseries.html["E-시리즈 SANtricity API"] 수집기.
* "E-시리즈 컨트롤러 IP 주소" 필드는 쉼표로 구분된 2개의 IP/호스트 이름 문자열을 지원합니다. 수집기는 첫 번째 IP/호스트 이름에 접근할 수 없는 경우 두 번째 IP/호스트 이름을 지능적으로 시도합니다.
* HTTPS 포트: 기본값은 8443입니다.




== 구성

[cols="2*"]
|===
| 필드 | 설명 


| E-시리즈 컨트롤러 IP 주소 | 어레이 컨트롤러에 대한 쉼표로 구분된 IP 주소 및/또는 정규화된 도메인 이름 
|===


== 고급 구성

[cols="2*"]
|===
| 필드 | 설명 


| 재고 폴링 간격(분) | 기본값은 30분입니다 


| 최대 3600초의 성능 폴링 간격 | 기본값은 300초입니다 
|===


== E-시리즈 용어(랜딩 페이지)

다음 용어는 NetApp E-Series 자산 랜딩 페이지에서 찾을 수 있는 객체나 참조에 적용됩니다.  이러한 용어의 대부분은 다른 데이터 수집자에게도 적용됩니다.



=== 스토리지

* 모델 – 장치의 모델 이름.
* 공급업체 - 새 데이터 소스를 구성하는 경우와 동일한 공급업체 이름입니다.
* 일련 번호 – 배열 일련 번호.  NetApp Clustered Data Ontap과 같은 클러스터 아키텍처 스토리지 시스템에서 이 일련 번호는 개별 "스토리지 노드" 일련 번호보다 덜 유용할 수 있습니다.
* IP – 일반적으로 데이터 소스에 구성된 IP 또는 호스트 이름이 됩니다.
* 마이크로코드 버전 - 펌웨어
* 원시 용량 – 시스템의 모든 물리적 디스크의 역할에 관계없이 2진법 합계
* 대기 시간 - 호스트가 읽기와 쓰기 모두에서 작업 부하를 경험하는 것을 표현한 것입니다.  이상적으로는 Data Infrastructure Insights 이 가치를 직접 소싱하는 것이 좋지만, 그렇지 않은 경우가 많습니다.  이를 제공하는 배열 대신, Data Infrastructure Insights 일반적으로 개별 볼륨의 통계에서 파생된 IOPS 가중치 계산을 수행합니다.
* 처리량 – 어레이의 총 호스트 처리량입니다.  이상적으로는 어레이에서 직접 소싱되지만 사용할 수 없는 경우 Data Infrastructure Insights 볼륨의 처리량을 합산하여 이 값을 도출합니다.
* 관리 – 여기에는 장치의 관리 인터페이스에 대한 하이퍼링크가 포함될 수 있습니다.  재고 보고의 일부로 Data Infrastructure Insights 데이터 소스에 의해 프로그래밍 방식으로 생성됨  




=== 스토리지 풀

* 저장소 – 이 풀이 어떤 저장소 배열에 있는지. 필수적인
* 유형 – 가능성의 열거된 목록에서 나온 설명적 값입니다.  가장 일반적으로는 "씬 프로비저닝" 또는 "RAID 그룹"입니다.
* 노드 - 이 스토리지 어레이의 아키텍처가 풀이 특정 스토리지 노드에 속하도록 되어 있는 경우 해당 이름은 여기에서 자체 랜딩 페이지에 대한 하이퍼링크로 표시됩니다.
* Flash Pool 사용 – 예/아니요 값
* 중복성 – RAID 수준 또는 보호 체계.  E-Series는 DDP 풀에 대해 "RAID 7"을 보고합니다.
* 용량 – 여기의 값은 논리적으로 사용된 용량, 사용 가능한 용량, 논리적 총 용량, 그리고 이들에 사용된 백분율입니다.  이 값에는 E-시리즈 "보존" 용량이 모두 포함되어 있어 숫자와 백분율이 E-시리즈 자체 사용자 인터페이스에서 표시되는 것보다 더 높습니다.
* 과도하게 할당된 용량 – 효율성 기술을 통해 스토리지 풀의 논리적 용량보다 큰 볼륨 또는 내부 볼륨 용량의 총합을 할당한 경우 여기의 백분율 값은 0%보다 커집니다.
* 스냅샷 - 스토리지 풀 아키텍처가 스냅샷 전용 세그먼트 영역에 용량의 일부를 할당하는 경우 사용된 스냅샷 용량과 총 용량
* 활용도 – 이 스토리지 풀에 용량을 제공하는 모든 디스크 중 가장 높은 디스크 사용률을 나타내는 백분율 값입니다.  디스크 사용률은 반드시 어레이 성능과 강한 상관관계가 있는 것은 아닙니다. 호스트 기반 워크로드가 없는 경우 디스크 재구축, 중복 제거 활동 등으로 인해 사용률이 높을 수 있습니다.  또한 많은 어레이의 복제 구현은 볼륨 작업 부하로 표시되지 않으면서 디스크 활용도를 높일 수 있습니다.
* IOPS – 이 스토리지 풀에 용량을 제공하는 모든 디스크의 합계 IOPS입니다.  주어진 플랫폼에서 디스크 IOP를 사용할 수 없는 경우 이 값은 이 스토리지 풀에 있는 모든 볼륨의 볼륨 IOP 합계에서 제공됩니다.
* 처리량 – 이 스토리지 풀에 용량을 제공하는 모든 디스크의 총 처리량입니다.  주어진 플랫폼에서 디스크 처리량을 사용할 수 없는 경우 이 값은 이 스토리지 풀에 있는 모든 볼륨의 전체 볼륨 처리량 합계에서 제공됩니다.




=== 저장 노드

* 저장소 – 이 노드가 속한 저장소 배열입니다. 필수적인
* HA 파트너 - 노드가 다른 노드로만 장애 조치되는 플랫폼에서는 일반적으로 여기에 표시됩니다.
* 상태 - 노드의 상태.  데이터 소스에서 인벤토리를 수행할 수 있을 만큼 어레이가 정상 상태인 경우에만 사용 가능
* 모델 - 노드의 모델 이름
* 버전 – 장치의 버전 이름.
* 일련 번호 - 노드 일련 번호
* 메모리 - 사용 가능한 경우 기본 2 메모리
* 활용도 – 일반적으로 CPU 활용도 수치이거나 NetApp Ontap의 경우 컨트롤러 스트레스 지수입니다.  현재 NetApp E-Series에서는 활용이 불가능합니다.
* IOPS – 이 컨트롤러에서 호스트가 구동하는 IOP를 나타내는 숫자입니다.  이상적으로는 어레이에서 직접 소싱하지만, 이를 사용할 수 없는 경우 해당 노드에만 속하는 볼륨의 모든 IOP를 합산하여 계산합니다.
* 대기 시간 - 이 컨트롤러에서 일반적인 호스트 대기 시간 또는 응답 시간을 나타내는 숫자입니다.  이상적으로는 어레이에서 직접 소싱하지만, 이를 사용할 수 없는 경우 해당 노드에만 속한 볼륨에서 IOP 가중 계산을 수행하여 계산합니다.
* 처리량 – 이 컨트롤러에서 호스트가 구동하는 처리량을 나타내는 숫자입니다.  이상적으로는 어레이에서 직접 소싱하지만, 이를 사용할 수 없는 경우 해당 노드에만 속한 볼륨의 모든 처리량을 합산하여 계산합니다.
* 프로세서 - CPU 수




== 문제 해결

이 데이터 수집기에 대한 추가 정보는 다음에서 찾을 수 있습니다.link:concept_requesting_support.html["지원하다"] 페이지 또는link:reference_data_collector_support_matrix.html["데이터 수집기 지원 매트릭스"] .
