---
sidebar: sidebar 
permalink: task_dc_ms_hyperv.html 
keywords: data collector, Microsoft, Hyper-V 
summary: Microsoft Hyper-V 데이터 수집기를 구성합니다. 
---
= Microsoft Hyper-V 데이터 수집기
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Microsoft Hyper-V 데이터 수집기는 가상화된 서버 컴퓨팅 환경에서 인벤토리 및 성능 데이터를 수집합니다.  이 데이터 수집기는 독립 실행형 Hyper-V 호스트나 전체 클러스터를 검색할 수 있습니다. 독립 실행형 호스트나 클러스터당 하나의 수집기를 생성하세요.



== 술어

Data Infrastructure Insights Microsoft Hyper-V(WMI)에서 다음과 같은 인벤토리 정보를 수집합니다.  Data Infrastructure Insights 에서 수집한 각 자산 유형에 대해 해당 자산에 가장 일반적으로 사용되는 용어가 표시됩니다.  이 데이터 수집기를 보거나 문제를 해결할 때 다음 용어를 염두에 두십시오.

[cols="2*"]
|===
| 공급업체/모델 용어 | Data Infrastructure Insights 용어 


| 가상 하드 디스크 | 가상 디스크 


| 주인 | 주인 


| 가상 머신 | 가상 머신 


| 클러스터 공유 볼륨(CSV), 파티션 볼륨 | 데이터 저장소 


| 인터넷 SCSI 장치, 다중 경로 SCSI LUN | LUN 


| 파이버 채널 포트 | 포트 
|===
참고: 이는 일반적인 용어 매핑일 뿐이며 이 데이터 수집기의 모든 사례를 나타내지 않을 수 있습니다.



== 요구 사항

이 데이터 수집기를 구성하려면 다음이 필요합니다.

* Hyper-V에서는 데이터 수집 및 원격 액세스/관리를 위해 포트 5985가 열려 있어야 합니다.
* 클러스터 또는 독립형 하이퍼바이저의 IP 주소 또는 FQDN입니다.  클러스터의 특정 노드 하나에만 수집기를 지정하는 것보다는 부동 클러스터 호스트 이름이나 IP를 사용하는 것이 가장 안정적인 방법일 가능성이 높습니다.
* 클러스터의 모든 하이퍼바이저에서 작동하는 관리자 수준의 사용자 계정입니다.
* WinRM은 모든 하이퍼바이저에서 활성화되고 수신되어야 합니다.
* 포트 요구 사항: WMI를 통한 포트 135 및 Windows 2003 이하 버전의 경우 1024-65535가 할당된 동적 TCP 포트, Windows 2008의 경우 49152-65535가 할당됩니다.
* 데이터 수집기가 IP 주소만을 가리키더라도 DNS 확인은 성공해야 합니다.
* 각 Hyper-V 하이퍼바이저는 모든 호스트의 모든 VM에 대해 "리소스 측정"을 켜야 합니다.  이를 통해 각 하이퍼바이저는 각 게스트에 대한 Data Infrastructure Insights 에 사용할 수 있는 데이터가 더 많아집니다.  이 설정이 없으면 각 게스트에 대해 수집되는 성능 지표가 줄어듭니다.  리소스 측정에 대한 자세한 내용은 Microsoft 설명서에서 확인할 수 있습니다.
+
link:https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-R2-and-2012/hh831661(v=ws.11)["Hyper-V 리소스 측정 개요"]

+
link:https://docs.microsoft.com/en-us/powershell/module/hyper-v/enable-vmresourcemetering?view=win10-ps["Enable-VMResourceMetering"]




NOTE: Hyper-V 데이터 수집기에는 Windows Acquisition Unit이 필요합니다.



== 구성

[cols="2*"]
|===
| 필드 | 설명 


| 클러스터 IP 주소 또는 플로팅 클러스터 FQDN | 클러스터 또는 독립 실행형 비클러스터형 하이퍼바이저의 IP 주소 또는 정규화된 도메인 이름 


| 사용자 이름 | 하이퍼바이저의 관리자 사용자 이름 


| 비밀번호 | 하이퍼바이저의 비밀번호 


| DNS 도메인 접미사 | 하이퍼바이저의 FQDN을 렌더링하기 위해 단순 호스트 이름과 결합되는 호스트 이름 접미사 
|===


== 고급 구성

[cols="2*"]
|===
| 필드 | 설명 


| 재고 폴링 간격(분) | 기본값은 20분입니다. 
|===


== 문제 해결

이 데이터 수집기에 대한 추가 정보는 다음에서 찾을 수 있습니다.link:concept_requesting_support.html["지원하다"] 페이지 또는link:reference_data_collector_support_matrix.html["데이터 수집기 지원 매트릭스"] .
