---
sidebar: sidebar 
permalink: task_dc_infinidat_infinibox.html 
keywords: data collector, infinidat, InfiniBox 
summary: Infinidat InfiniBox 데이터 수집기를 구성합니다. 
---
= Infinidat InfiniBox 데이터 수집기
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Infinidat InfiniBox(HTTP) 데이터 수집기는 Infinidat InfiniBox 저장 시스템에서 인벤토리 정보를 수집하는 데 사용됩니다.



== 술어

Data Infrastructure Insights Infinidat InfiniBox 데이터 수집기에서 다음과 같은 인벤토리 정보를 수집합니다.  Data Infrastructure Insights 에서 수집한 각 자산 유형에 대해 해당 자산에 가장 일반적으로 사용되는 용어가 표시됩니다.  이 데이터 수집기를 보거나 문제를 해결할 때 다음 용어를 염두에 두십시오.

[cols="2*"]
|===
| 공급업체/모델 용어 | Data Infrastructure Insights 용어 


| 스토리지 풀 | 스토리지 풀 


| 마디 | 제어 장치 


| 파일 시스템 | 내부 볼륨 


| 파일 시스템 | 파일 공유 


| 파일 시스템 내보내기 | 공유하다 
|===


== 요구 사항

이 데이터 수집기를 구성할 때 필요한 사항은 다음과 같습니다.

* InfiniBox 관리 노드의 IP 주소 또는 FQDN
* 관리자 사용자 ID 및 비밀번호
* REST API를 통한 포트 443




== 구성

[cols="2*"]
|===
| 필드 | 설명 


| InfiniBox 호스트 | InfiniBox 관리 노드의 IP 주소 또는 정규화된 도메인 이름 


| 사용자 이름 | InfiniBox 관리 노드의 사용자 이름 


| 비밀번호 | InfiniBox 관리 노드의 비밀번호 
|===


== 고급 구성

[cols="2*"]
|===
| 필드 | 설명 


| TCP 포트 | InfiniBox 서버에 연결하는 데 사용되는 TCP 포트입니다.  기본값은 443입니다. 


| 재고 폴링 간격 | 재고 조사 간격. 기본값은 60분입니다. 
|===


== 문제 해결

이 데이터 수집기에 대한 추가 정보는 다음에서 찾을 수 있습니다.link:concept_requesting_support.html["지원하다"] 페이지 또는link:reference_data_collector_support_matrix.html["데이터 수집기 지원 매트릭스"] .
