---
sidebar: sidebar 
permalink: task_dc_huawei_oceanstor.html 
keywords: data collector, Huawei, OceanStor, Dorado 
summary: 'Huawei OceanStor(REST/HTTPS) 데이터 수집기를 구성합니다.' 
---
= Huawei OceanStor 데이터 수집기
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Data Infrastructure Insights Huawei OceanStor(REST/HTTPS) 데이터 수집기를 사용하여 Huawei OceanStor 및 OceanStor Dorado 스토리지의 인벤토리와 성능을 파악합니다.



== 술어

Data Infrastructure Insights Huawei OceanStor에서 다음과 같은 인벤토리 및 성능 정보를 수집합니다.  Data Infrastructure Insights 에서 수집한 각 자산 유형에 대해 해당 자산에 가장 일반적으로 사용되는 용어가 표시됩니다.  이 데이터 수집기를 보거나 문제를 해결할 때 다음 용어를 염두에 두십시오.

[cols="2*"]
|===
| 공급업체/모델 용어 | Data Infrastructure Insights 용어 


| 스토리지 풀 | 스토리지 풀 


| 파일 시스템 | 내부 볼륨 


| 제어 장치 | 저장 노드 


| FC 포트(매핑됨) | 볼륨 맵 


| 호스트 FC 이니시에이터(매핑됨) | 볼륨 마스크 


| NFS/CIFS 공유 | 공유하다 


| iSCSI 링크 대상 | iSCSI 대상 노드 


| iSCSI 링크 이니시에이터 | iSCSI 초기자 노드 


| 디스크 | 디스크 


| LUN | 용량 
|===


== 요구 사항

이 데이터 수집기를 구성하려면 다음 요구 사항이 필요합니다.

* 장치 IP 주소
* OceanStor 장치 관리자에 액세스하기 위한 자격 증명
* 포트 8088을 사용할 수 있어야 합니다.




== 구성

[cols="2*"]
|===
| 필드 | 설명 


| OceanStor 호스트 IP 주소 | OceanStor Device Manager의 IP 주소 또는 정규화된 도메인 이름 


| 사용자 이름 | OceanStor Device Manager에 로그인하는 데 사용되는 이름 


| 비밀번호 | OceanStor Device Manager에 로그인하는 데 사용되는 비밀번호 
|===


== 고급 구성

[cols="2*"]
|===
| 필드 | 설명 


| TCP 포트 | OceanStor Device Manager에 연결하는 데 사용되는 TCP 포트입니다.  기본값은 8088입니다. 


| 재고 폴링 간격(분) | 재고 조사 간격. 기본값은 60분입니다. 


| 성능 폴링 간격(초). | 기본값은 300초입니다. 
|===


== 문제 해결

이 데이터 수집기에 대한 추가 정보는 다음에서 찾을 수 있습니다.link:concept_requesting_support.html["지원하다"] 페이지 또는link:reference_data_collector_support_matrix.html["데이터 수집기 지원 매트릭스"] .
