---
sidebar: sidebar 
permalink: task_dc_ibm_ds4000.html 
keywords: data collector, IBM, DS4000 
summary: IBM TotalStorage DS4000 데이터 수집기 
---
= IBM TotalStorage DS4000 데이터 수집기
:hardbreaks:
:allow-uri-read: 


[role="lead"]
이 데이터 수집기는 IBM DS4000 스토리지 시스템에서 인벤토리 및 성능 정보를 수집합니다.  가능한 구성은 두 가지(펌웨어 6.x 및 펌웨어 7.x+)이며, 두 구성 모두 동일한 값을 갖습니다.



== 술어

Data Infrastructure Insights IBM DS4000 데이터 수집기에서 다음과 같은 인벤토리 정보를 수집합니다.  인수한 각 자산 유형에 대해 해당 자산에 사용되는 가장 일반적인 용어가 표시됩니다.  이 데이터 수집기를 보거나 문제를 해결할 때 다음 용어를 염두에 두십시오.

[cols="2*"]
|===
| 공급업체/모델 용어 | Data Infrastructure Insights 용어 


| 디스크 | 디스크 


| 볼륨 그룹 | 디스크 그룹 


| 스토리지 어레이 | 스토리지 


| 제어 장치 | 저장 노드 


| 볼륨 그룹 | 스토리지 풀 


| 용량 | 용량 
|===
참고: 이는 일반적인 용어 매핑일 뿐이며 이 데이터 수집기의 모든 사례를 나타내지 않을 수 있습니다.



== 요구 사항

* 각 DS5 또는 FAStT 어레이의 IP 주소
* 어레이의 두 컨트롤러의 IP 주소를 ping하여 액세스 검증
* 포트 요구 사항: 2463




== 구성

[cols="2*"]
|===
| 필드 | 설명 


| Array SANtricity Controller IP의 쉼표로 구분된 목록 | 어레이 컨트롤러에 대한 IP 주소 및/또는 정규화된 도메인 이름 
|===


== 고급 구성

[cols="2*"]
|===
| 필드 | 설명 


| 재고 폴링 간격(분) | 기본값은 30분입니다 


| 최대 3600초의 성능 폴링 간격 | 기본값은 300초입니다 
|===


== 문제 해결

이 데이터 수집기에 대한 추가 정보는 다음에서 찾을 수 있습니다.link:concept_requesting_support.html["지원하다"] 페이지 또는link:reference_data_collector_support_matrix.html["데이터 수집기 지원 매트릭스"] .
