---
sidebar: sidebar 
permalink: task_dc_emc_isilon.html 
keywords: data collector, isilon, EMC, DELL, PowerScale 
summary: 'Dell EMC PowerScale(이전 Isilon) 데이터 수집기를 구성합니다.' 
---
= Dell EMC PowerScale 데이터 수집기
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Data Infrastructure Insights Dell EMC PowerScale(이전 Isilon) SSH 데이터 수집기를 사용하여 PowerScale 확장형 NAS 스토리지에서 인벤토리 및 성능 데이터를 수집합니다.



== 술어

Data Infrastructure Insights 이 데이터 수집기로부터 다음과 같은 인벤토리 정보를 수집합니다.  Data Infrastructure Insights 에서 수집한 각 자산 유형에 대해 해당 자산에 가장 일반적으로 사용되는 용어가 표시됩니다.  이 데이터 수집기를 보거나 문제를 해결할 때 다음 용어를 염두에 두십시오.

[cols="2*"]
|===
| 공급업체/모델 용어 | Data Infrastructure Insights 용어 


| 운전하다 | 디스크 


| 무리 | 스토리지 


| 마디 | 저장 노드 


| 파일 시스템 | 내부 볼륨 
|===
참고: 이는 일반적인 용어 매핑일 뿐이며 이 데이터 수집기의 모든 사례를 나타내지 않을 수 있습니다.



== 요구 사항

이 데이터 수집기를 구성하려면 다음 정보가 필요합니다.

* PowerScale 스토리지에 대한 관리자 권한
* PowerScale 클러스터의 IP 주소
* 포트 22에 대한 SSH 접속




== 구성

[cols="2*"]
|===
| 필드 | 설명 


| IP 주소 | PowerScale 클러스터의 IP 주소 또는 정규화된 도메인 이름 


| 사용자 이름 | PowerScale 클러스터의 사용자 이름 


| 비밀번호 | PowerScale 클러스터에 사용되는 비밀번호 
|===


== 고급 구성

[cols="2*"]
|===
| 필드 | 설명 


| 재고 폴링 간격(분) | 재고 조사 간격.  기본값은 20입니다. 


| 성능 폴링 간격(초) | 성과 여론조사 간격.  기본값은 300입니다. 


| SSH 포트 | SSH 서비스 포트.  기본값은 22입니다. 
|===


== 문제 해결

이 데이터 수집기에 문제가 발생하면 시도해 볼 수 있는 몇 가지 사항은 다음과 같습니다.



=== 목록

[cols="2*"]
|===
| 문제: | 다음을 시도해 보세요: 


| "잘못된 로그인 자격 증명"과 "역할 기반 관리에 사용할 수 없는 명령에는 루트 사용자 액세스가 필요합니다"라는 오류 메시지가 표시됩니다. | * 사용자에게 장치에서 다음 명령을 실행할 권한이 있는지 확인합니다. > isi version osrelease > isi status -q > isi status -n > isi devices -d %s > isi license * 마법사에서 사용된 자격 증명이 장치 자격 증명과 일치하는지 확인합니다. 


| "내부 오류"와 함께 "명령 <사용자의 명령> 실행이 권한 <사용자의 현재 권한>으로 인해 실패했습니다."라는 오류 메시지가 표시됩니다.  Sudo 명령어 실행 권한 문제” | 사용자에게 장치에서 다음 명령을 실행할 수 있는 sudo 권한이 있는지 확인하세요. 
|===
추가 정보는 다음에서 찾을 수 있습니다.link:concept_requesting_support.html["지원하다"] 페이지 또는link:reference_data_collector_support_matrix.html["데이터 수집기 지원 매트릭스"] .
