---
sidebar: sidebar 
permalink: task_create_annotation_rules.html 
summary: 주석을 여러 자산에 자동으로 적용하는 주석 규칙을 작성합니다. 
keywords: annotate, annotation, rules 
---
= 주석 규칙 작성
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
주석 규칙을 사용하여 정의한 기준에 따라 여러 자산에 주석을 자동으로 적용할 수 있습니다. Data Infrastructure Insights는 이러한 규칙을 기반으로 자산에 주석을 할당합니다. Cloud Insight에서 주석 규칙을 평가할 때 개별 자산 페이지에 수동으로 설정된 주석이 규칙 기반 주석보다 우선합니다.

.시작하기 전에
주석 규칙에 대한 쿼리를 만들어야 합니다.

.단계
. Data Infrastructure Insights 메뉴에서 * 관리 > 주석 규칙 * 을 클릭합니다.
. 새 주석 규칙을 추가하려면 * + 규칙 * 을 클릭합니다.
+
규칙 추가 대화 상자가 표시됩니다.

. 다음을 수행합니다.
+
.. 이름 * 상자에 규칙을 설명하는 고유한 이름을 입력합니다.
+
주석 규칙 페이지에 이름이 나타납니다.

.. Query * 를 클릭하고 Data Infrastructure Insights에서 주석이 적용되는 자산을 식별하는 데 사용하는 쿼리를 선택합니다.
.. Annotation(주석) * 을 클릭하고 적용할 주석을 선택합니다.
.. 값 * 을 클릭하고 주석 값을 선택합니다.
+
예를 들어 주석으로 생일 을 선택한 경우 값의 날짜를 지정합니다.

.. 저장 * 을 클릭합니다
.. 모든 규칙을 즉시 실행하려면 * 모든 규칙 실행 * 을 클릭합니다. 그렇지 않으면 규칙들이 정기적으로 예약된 간격으로 실행됩니다.
+

NOTE: 대규모 Data Infrastructure Insights 환경에서는 주석 규칙을 실행하는 데 시간이 오래 걸리는 것처럼 보일 수 있습니다. 이는 인덱서가 먼저 실행되고 규칙을 실행하기 전에 완료되어야 하기 때문입니다. 인덱서는 Data Infrastructure Insights에서 데이터에서 새 개체 또는 업데이트된 개체 및 카운터를 검색하거나 필터링할 수 있는 기능을 제공합니다. 규칙 엔진은 인덱서가 업데이트를 완료할 때까지 기다렸다가 규칙을 적용합니다.







== 주석 규칙 수정

주석 규칙을 수정하여 규칙 이름, 주석, 주석 값 또는 규칙과 연결된 쿼리를 변경할 수 있습니다.

.단계
. Data Infrastructure Insights 메뉴에서 * 관리 > 주석 규칙 * 을 클릭합니다.
+
주석 규칙 페이지에는 기존 주석 규칙 목록이 표시됩니다.

. 수정할 주석 규칙을 찾습니다.
+
필터 상자에 값을 입력하여 주석 규칙을 필터링하거나 페이지 번호를 클릭하여 페이지별로 주석 규칙을 찾아볼 수 있습니다.

. 수정할 규칙의 메뉴 아이콘을 클릭합니다.
. 편집 * 을 클릭합니다
+
규칙 편집 대화 상자가 표시됩니다.

. 주석 규칙 이름, 주석, 값 또는 쿼리를 수정합니다.




== 규칙 순서 변경

주석 규칙은 규칙 목록의 맨 위에서 맨 아래로 처리됩니다. 규칙이 처리되는 순서를 변경하려면 다음을 실행합니다.

.단계
. 이동할 규칙의 메뉴 아이콘을 클릭합니다.
. 원하는 위치에 규칙이 나타날 때까지 필요에 따라 * 위로 이동 * 또는 * 아래로 이동 * 을 클릭합니다.


한 자산에서 동일한 주석을 업데이트하는 여러 규칙을 실행할 때 첫 번째 규칙(위에서 아래로 실행)이 주석을 적용하고 자산을 업데이트한 다음 두 번째 규칙이 적용되지만 이전 규칙에 의해 이미 설정된 주석은 변경되지 않습니다.



== 주석 규칙 삭제

더 이상 사용되지 않는 주석 규칙을 삭제할 수 있습니다.

.단계
. Data Infrastructure Insights 메뉴에서 * 관리 > 주석 규칙 * 을 클릭합니다.
+
주석 규칙 페이지에는 기존 주석 규칙 목록이 표시됩니다.

. 삭제할 주석 규칙을 찾습니다.
+
필터 상자에 값을 입력하여 주석 규칙을 필터링하거나 페이지 번호를 클릭하여 페이지별로 주석 규칙을 찾아볼 수 있습니다.

. 삭제할 규칙의 메뉴 아이콘을 클릭합니다.
. 삭제 * 를 클릭합니다
+
규칙을 삭제할 것인지 묻는 확인 메시지가 표시됩니다.

. 확인 * 을 클릭합니다

