---
sidebar: sidebar 
permalink: task_dc_hds_ops_center.html 
keywords: data collector, Hitachi Ops Center 
summary: HDS Ops Center 데이터 수집기를 구성합니다. 
---
= 히타치 Ops Center 데이터 수집기
:hardbreaks:
:allow-uri-read: 


[role="lead"]
이 데이터 수집기는 Hitachi Ops Center의 통합 애플리케이션 제품군을 사용하여 여러 저장 장치의 인벤토리 및 성능 데이터에 액세스합니다.  재고 및 용량 검색을 위해 Ops Center 설치에는 "공통 서비스"와 "관리자" 구성 요소가 모두 포함되어야 합니다.  성능 수집을 위해서는 "분석기"를 추가로 배포해야 합니다.



== 술어

Data Infrastructure Insights 이 데이터 수집기로부터 다음과 같은 인벤토리 정보를 수집합니다.  Data Infrastructure Insights 에서 수집한 각 자산 유형에 대해 해당 자산에 가장 일반적으로 사용되는 용어가 표시됩니다.  이 데이터 수집기를 보거나 문제를 해결할 때 다음 용어를 염두에 두십시오.

[cols="2*"]
|===
| 공급업체/모델 용어 | Data Infrastructure Insights 용어 


| 저장 시스템 | 스토리지 


| 용량 | 용량 


| 패리티 그룹 | 스토리지 풀(RAID), 디스크 그룹 


| 디스크 | 디스크 


| 스토리지 풀 | 스토리지 풀(씬, SNAP) 


| 외부 패리티 그룹 | 스토리지 풀(백엔드), 디스크 그룹 


| 포트 | 스토리지 노드 → 컨트롤러 노드 → 포트 


| 호스트 그룹 | 볼륨 매핑 및 마스킹 


| 볼륨 쌍 | 스토리지 동기화 
|===
참고: 이는 일반적인 용어 매핑일 뿐이며 이 데이터 수집기의 모든 사례를 나타내지 않을 수 있습니다.



== 재고 요구 사항

재고 데이터를 수집하려면 다음이 필요합니다.

* "공통 서비스" 구성 요소를 호스팅하는 Ops Center 서버의 IP 주소 또는 호스트 이름
* Ops Center 구성 요소를 호스팅하는 모든 서버에 있는 루트/시스템 관리자 사용자 계정과 비밀번호입니다.  HDS는 Ops Center 10.8+까지 LDAP/SSO 사용자가 사용할 수 있는 REST API 지원을 구현하지 않았습니다.




== 성능 요구 사항

성과 데이터를 수집하려면 다음 요구 사항을 충족해야 합니다.

HDS Ops Center "Analyzer" 모듈이 설치되어야 합니다. 스토리지 어레이는 Ops Center "Analyzer" 모듈에 전원을 공급해야 합니다.



== 구성

[cols="2*"]
|===
| 필드 | 설명 


| 히타치 운영 센터 IP 주소 | "공통 서비스" 구성 요소를 호스팅하는 Ops Center 서버의 IP 주소 또는 정규화된 도메인 이름 


| 사용자 이름 | Ops Center 서버의 사용자 이름입니다. 


| 비밀번호 | Ops Center 서버에 사용되는 비밀번호입니다. 
|===


== 고급 구성

|===


| 필드 | 설명 


| 연결 유형 | HTTPS(포트 443)가 기본값입니다. 


| TCP 포트 재정의 | 기본값이 아닌 경우 사용할 포트를 지정하세요. 


| 재고 폴링 간격(분) | 재고 조사 간격.  기본값은 40입니다. 


| '제외' 또는 '포함'을 선택하여 목록을 지정합니다. | 데이터를 수집할 때 아래의 배열 목록을 포함할지 제외할지 지정하세요. 


| 필터 장치 목록 | 포함하거나 제외할 장치 일련 번호의 쉼표로 구분된 목록 


| 성능 폴링 간격(초) | 성과 여론조사 간격.  기본값은 300입니다. 
|===
추가 정보는 다음에서 찾을 수 있습니다.link:concept_requesting_support.html["지원하다"] 페이지 또는link:reference_data_collector_support_matrix.html["데이터 수집기 지원 매트릭스"] .
