---
sidebar: sidebar 
permalink: task_dc_brocade_rest.html 
keywords: data collector, Brocade, FC switch, FOS, Rest 
summary: Brocade FOS REST 데이터 수집기를 구성하는 중입니다. 
---
= Brocade FOS REST Data Collector
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Data Infrastructure Insights는 Brocade FOS REST Collector를 사용하여 FabricOS(FabricOS) 펌웨어 8.2 이상을 실행하는 Brocade 스위치 장치의 인벤토리 및 성능을 검색합니다.

참고: FOS의 기본 "사용자" 수준은 장치의 모든 논리적 측면을 Data Infrastructure Insights에서 볼 수 있는 기능이 충분하지 않습니다. "섀시 역할"이 활성화된 사용자 계정과 스위치에서 구성된 모든 가상 패브릭에 대한 권한이 필요합니다.

다음은 FOS 디바이스에 대한 SSH 세션에서 Data Infrastructure Insights 사용에 대한 "최소 권한" 사용자 계정을 생성하는 방법의 예입니다.

userConfig--add NetAppCIUser-r user-l 1-128-c user-p QWERTY!

이렇게 하면 암호가 "QWERTY!"인 "NetAppCIUser" 사용자가 생성됩니다. 이 사용자는 128개의 가능한 모든 가상 Fabric(-l)에서 "user" 역할(-r)을 갖습니다. 또한 이 사용자는 사용자 수준 액세스 권한이 할당된 필수 “섀시” 역할(-c)을 갖습니다.

기본적으로 이 컬렉터는 스위치가 속한 모든 패브릭의 일부인 모든 FOS 장치를 검색하려고 시도합니다.

참고: FOS의 기본 읽기 전용 사용자 "user"에는 모든 가상 패브릭에 대한 보기 권한이 없으며 "섀시 역할" 권한도 없습니다. 즉, FOS 장치의 물리적 구성과 논리적 구성을 모두 이해해야 하는 Data Infrastructure Insights에서 "사용자"를 사용하면 성공할 가능성이 낮습니다.



== 용어

Data Infrastructure Insights는 Brocade FOS REST 데이터 수집기에서 다음과 같은 인벤토리 정보를 수집합니다. Data Infrastructure Insights에서 구입한 각 자산 유형에 대해 이 자산에 사용되는 가장 일반적인 용어가 표시되어 있습니다. 이 데이터 수집기를 보거나 문제를 해결할 때 다음 용어를 염두에 두십시오.

[cols="2*"]
|===
| 공급업체/모델 기간 | Data Infrastructure Insights 용어 


| 스위치 | 스위치 


| 포트 | 포트 


| 가상 패브릭, 물리적 패브릭 | 패브릭 


| Zone(영역) | Zone(영역) 


| 논리 스위치 | 논리 스위치 


| LSAN 구역 | IVR 구역 
|===
참고: 이러한 용어 매핑은 일반적인 용어 매핑일 뿐이며 이 데이터 수집기의 모든 경우를 나타내는 것은 아닙니다.



== 요구 사항

* Fabric의 모든 스위치에 TCP 연결이 있어야 합니다. 이 데이터 수집기 유형은 패브릭의 각 장치에 대해 HTTP와 HTTPS를 모두 원활하게 시도합니다. fabric_에서 모든 스위치 검색 확인란을 선택하면 Data Infrastructure Insights에서 패브릭의 모든 스위치를 식별하지만, 이러한 추가 스위치를 검색하려면 TCP 연결이 필요합니다.
* Fabric의 모든 스위치에서 동일한 계정이 전 세계적으로 필요합니다. 장치의 웹 인터페이스를 사용하여 액세스를 확인할 수 있습니다.




== 구성

[cols="2*"]
|===
| 필드에 입력합니다 | 설명 


| 스위치 IP | FOS 스위치의 IP 주소 또는 정규화된 도메인 이름입니다 


| 사용자 이름 | 스위치의 사용자 이름입니다 


| 암호 | 스위치에 대한 암호입니다 
|===


== 고급 구성

[cols="2*"]
|===
| 필드에 입력합니다 | 설명 


| 제외된 장치 | 폴링에서 제외할 장치 IPv4 주소의 쉼표로 구분된 목록입니다. 


| 재고 폴링 간격(분) | 재고 조사 사이의 간격입니다. 기본값은 60입니다. 


| 패브릭의 모든 스위치를 살펴보십시오 | 패브릭의 모든 스위치를 검색하려면 선택합니다. 


| HBA와 Zone Aliases를 선택합니다 | HBA 또는 존 별칭을 사용할지 여부를 선택합니다. 


| 연결 유형 | HTTP 또는 HTTPS. 


| 이 설정은 장치별로 먼저 사용을 시도하는 프로토콜 CI만 변경합니다. 기본값이 실패할 경우 CI가 자동으로 반대 프로토콜을 시도합니다 | TCP 포트를 재정의합니다 


| 기본값을 사용하지 않는 경우 포트를 지정합니다. | 성능 폴링 간격(초) 
|===


== 문제 해결

이 데이터 수집기에서 문제가 발생할 경우 다음과 같은 방법을 시도해 보십시오.



=== 인벤토리

[cols="2*"]
|===
| 문제: | 다음을 시도해 보십시오. 


| 테스트 기능은 프로토콜에 액세스할 수 없다는 경고 메시지를 표시합니다 | 특정 Brocade FOS 8.2+ 장치는 HTTP 또는 HTTPS에서만 통신하려고 합니다. - 스위치에 디지털 인증서가 설치되어 있는 경우 암호화되지 않은 HTTP와 HTTPS를 사용하여 통신하려고 하면 스위치에서 HTTP 오류가 발생합니다. 테스트 기능은 HTTP와 HTTPS 모두와 통신을 시도합니다. - 테스트에서 한 프로토콜이 통과한다고 말하면 수집기를 안전하게 저장할 수 있으며 다른 프로토콜이 실패해도 걱정할 필요가 없습니다. 수집기는 수집 중에 두 프로토콜을 모두 시도하며 두 프로토콜이 작동하지 않을 경우에만 실패합니다. 


| 오류: "Data Infrastructure Insights가 잘못된 섀시 역할을 수신했습니다." | 이 데이터 원본에 구성된 사용자에게 섀시 역할 권한이 부여되었는지 확인합니다. 


| 오류: "섀시 IP 주소가 일치하지 않습니다." | 섀시 IP 주소를 사용하도록 데이터 소스 구성을 변경합니다. 


| 403 금지됨으로 인해 재고가 실패합니다 | 이는 단순히 잘못된 자격 증명이거나, 사용자가 충분히 강력한 역할을 사용하려 한다는 것을 나타낼 수 있습니다. "사용자" 수준의 사용자에게 필요한 "섀시 역할" 권한이 없거나 기본값이 아닌 가상 패브릭에 대한 액세스 권한을 볼 수 없다는 점을 기억하십시오. 
|===
추가 정보는 페이지 또는 에서 찾을 link:concept_requesting_support.html["지원"]link:reference_data_collector_support_matrix.html["Data Collector 지원 매트릭스"]수 있습니다.
