---
sidebar: sidebar 
permalink: task_dc_oracle_zfs.html 
keywords: data collector, Oracle, ZFS, storage applicance 
summary: Oracle ZFS 데이터 수집기 구성. 
---
= Oracle ZFS Storage Appliance 데이터 수집기
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Data Infrastructure Insights는 Oracle ZFS Storage Appliance 데이터 수집기를 사용하여 인벤토리 및 성능 데이터를 수집합니다.



== 용어

Data Infrastructure Insights는 Oracle ZFS 데이터 수집기를 사용하여 재고 정보를 수집합니다. Data Infrastructure Insights에서 구입한 각 자산 유형에 대해 이 자산에 사용되는 가장 일반적인 용어가 표시되어 있습니다. 이 데이터 수집기를 보거나 문제를 해결할 때 다음 용어를 염두에 두십시오.

[cols="2*"]
|===
| 공급업체/모델 기간 | Data Infrastructure Insights 용어 


| 디스크(SSD) | 디스크 


| 클러스터 | 스토리지 


| 컨트롤러 | 스토리지 노드 


| LUN입니다 | 볼륨 


| LUN 매핑 | 볼륨 맵 


| 초기자, 대상 | 볼륨 마스크 


| 공유 | 내부 볼륨 
|===
참고: 이러한 용어 매핑은 일반적인 용어 매핑일 뿐이며 이 데이터 소스의 모든 경우를 나타내는 것은 아닙니다.



== 요구 사항

* ZFS Controller-1 및 ZFS Controller-2의 호스트 이름
* 관리자 사용자 이름 및 암호
* 포트 요구 사항: 215 HTTP/HTTPS




== 필수 성능 메트릭

Oracle ZFS 어플라이언스는 스토리지 관리자에게 성능 통계를 수집할 수 있는 많은 유연성을 제공합니다. Data Infrastructure Insights에서는 고가용성 쌍의 _ Each_컨트롤러를 다음 메트릭을 캡처하도록 구성할 것으로 예상합니다.

* SMB2.ops [공유]
* NFS3.ops [share]
* NFS4.ops [share]
* NFS4-1.ops [공유]


컨트롤러가 이러한 중 일부 또는 전부를 캡처하지 못하면 Data Infrastructure Insights가 "내부 볼륨"의 워크로드를 수행하지 않거나 과소 보고할 수 있습니다.



== 구성

[cols="2*"]
|===
| 필드에 입력합니다 | 설명 


| ZFS Controller-1 호스트 이름 | 스토리지 컨트롤러의 호스트 이름 1 


| ZFS Controller-2 호스트 이름 | 스토리지 컨트롤러의 호스트 이름 2 


| 사용자 이름입니다 | 스토리지 시스템 관리자 사용자 계정의 사용자 이름입니다 


| 암호 | 관리자 사용자 계정의 암호입니다 
|===


== 고급 구성

[cols="2*"]
|===
| 필드에 입력합니다 | 설명 


| 연결 유형 | HTTPS 또는 HTTP도 기본 포트를 표시합니다 


| 연결 포트를 재정의합니다 | 비어 있는 경우 연결 유형 필드에서 기본 포트를 사용하고, 그렇지 않으면 사용할 연결 포트를 입력합니다 


| 인벤토리 폴링 간격입니다 | 기본값은 60초입니다 


| 성능 폴링 간격(초) | 기본값은 300입니다. 
|===


== 문제 해결

이 데이터 수집기에서 문제가 발생할 경우 다음과 같은 방법을 시도해 보십시오.



=== 인벤토리

[cols="2a, 2a"]
|===
| 문제: | 다음을 시도해 보십시오. 


 a| 
"잘못된 로그인 자격 증명"
 a| 
ZFS 사용자 계정 및 암호를 확인합니다



 a| 
"404 \https://.....:215/api/access/v1" 상태로 인해 요청이 실패했습니다
 a| 
ZFS 어레이가 너무 오래되어 REST API를 지원할 수 없습니다. AK 2014.1.3.0은 최초의 REST API를 지원하는 ZFS OS 릴리스였으며, 일부 ZFS 어플라이언스가 이 버전으로 업그레이드할 수 있는 것은 아닙니다.



 a| 
"REST 서비스가 비활성화되었습니다" 오류 메시지와 함께 "구성 오류"
 a| 
이 장치에서 REST 서비스가 활성화되어 있는지 확인합니다.



 a| 
"User unauthorized for command" 오류 메시지와 함께 "구성 오류"
 a| 
이 오류는 구성된 사용자에 대해 특정 역할(예: 'advanced_analytics')이 포함되지 않았기 때문일 수 있습니다.

읽기 전용 역할을 가진 사용자에 대해 분석 범위를 적용하면 오류가 제거될 수 있습니다. 다음 단계를 수행하십시오.

. ZFS 시스템의 Configuration -> Users 화면에서 해당 역할 위로 마우스를 이동한 후 두 번 클릭하여 편집할 수 있습니다
. 범위 드롭다운 메뉴에서 "분석"을 선택합니다. 가능한 속성 목록이 나타납니다.
. 맨 위에 있는 확인란을 클릭하면 세 개의 속성이 모두 선택됩니다.
. 오른쪽에 있는 추가 버튼을 클릭합니다.
. 팝업 창의 오른쪽 위에 있는 적용 단추를 클릭합니다. 팝업 창이 닫힙니다.


|===
추가 정보는 페이지 또는 에서 찾을 link:concept_requesting_support.html["지원"]link:reference_data_collector_support_matrix.html["Data Collector 지원 매트릭스"]수 있습니다.
