---
sidebar: sidebar 
permalink: task_dc_rubrik_cdm.html 
keywords: data collector, Rubrik, 
summary: Rubrik CDM 데이터 수집기를 구성합니다. 
---
= Rubrik CDM 데이터 수집기
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Data Infrastructure Insights Rubrik 데이터 수집기를 사용하여 Rubrik 스토리지 어플라이언스에서 인벤토리 및 성능 데이터를 수집합니다.



== 술어

Data Infrastructure Insights Rubrik 데이터 수집기에서 다음과 같은 인벤토리 정보를 수집합니다.  Data Infrastructure Insights 에서 수집한 각 자산 유형에 대해 해당 자산에 가장 일반적으로 사용되는 용어가 표시됩니다.  이 데이터 수집기를 보거나 문제를 해결할 때 다음 용어를 염두에 두십시오.

[cols="2*"]
|===
| 공급업체/모델 용어 | Data Infrastructure Insights 용어 


| 무리 | 보관, 보관 풀 


| 마디 | 저장 노드 


| 디스크 | 디스크 
|===
참고: 이는 일반적인 용어 매핑일 뿐이며 이 데이터 소스의 모든 사례를 나타내지 않을 수 있습니다.



== 요구 사항

이 데이터 수집기를 구성하려면 다음이 필요합니다.

* Data Infrastructure Insights 수집 부서는 Rubrik 클러스터에 TCP 포트 443을 통해 연결을 시작합니다.  클러스터당 수집기 1개.
* 루브릭 클러스터 IP 주소.
* 클러스터의 사용자 이름과 비밀번호입니다.
* Rubrik 클러스터 IP 주소 또는 호스트 이름.
* 기본 인증의 경우 클러스터에 대한 사용자 이름과 비밀번호가 필요합니다.  서비스 계정 기반 인증을 사용하려면 서비스 계정, 비밀번호 및 조직 ID가 필요합니다.
* 포트 요구 사항: HTTPS 443




== 구성

[cols="2*"]
|===
| 필드 | 설명 


| 아이피 | Rubrik 클러스터의 IP 주소 


| 사용자 이름/서비스 계정 | 클러스터의 사용자 이름 


| 비밀번호 / 비밀 | 클러스터의 비밀번호 


| 서비스 계정에 대한 조직 ID | 이는 "Organization:::nnnnnn-nnnn....."와 같은 전체 문자열이어야 합니다. 
|===


== 고급 구성

[cols="2*"]
|===
| 재고 폴링 간격(분) | 기본값은 60입니다 


| 성능 폴링 간격(초) | 기본값은 300입니다 
|===


== 문제 해결

이 데이터 수집기에 문제가 발생하면 시도해 볼 수 있는 몇 가지 사항은 다음과 같습니다.



=== 목록

[cols="2*"]
|===
| 문제: | 다음을 시도해 보세요: 


| 두 개 이상의 저장소가 생성되었다는 메시지를 받았습니다. | 클러스터가 올바르게 구성되었는지, 수집기가 단일 클러스터를 가리키는지 확인하세요. 


| 400 [잘못된 요청] 오류로 폴링이 실패합니다. 관리 ID가 잘못되었습니다. | 조직 ID 필드에 값을 채웠지만 Rubrik 클러스터는 Rubrik의 오류 메시지에서 "ManagedId"로 언급되었음에도 불구하고 해당 조직 ID가 유효한 조직 ID라고 믿지 않습니다. 
|===
추가 정보는 다음에서 찾을 수 있습니다.link:concept_requesting_support.html["지원하다"] 페이지 또는link:reference_data_collector_support_matrix.html["데이터 수집기 지원 매트릭스"] .
