---
sidebar: sidebar 
permalink: task_view_configured_data_collectors.html 
keywords: acquisition, AU, data collector, collector, bulk edit, postpone polling, resume polling 
summary: 요약. 
---
= 구성된 데이터 수집기 관리
:hardbreaks:
:allow-uri-read: 


[role="lead"]
설치된 데이터 수집기 ​​페이지는 Data Infrastructure Insights 에 대해 구성된 데이터 수집기에 대한 액세스를 제공합니다.  이 페이지를 사용하여 기존 데이터 수집기를 수정할 수 있습니다.

.단계
. Data Infrastructure Insights 메뉴에서 *관찰성 > 수집기*를 클릭합니다.
+
사용 가능한 데이터 수집기 화면이 표시됩니다.

. *설치된 데이터 수집기*를 클릭하세요.
+
설치된 모든 데이터 수집기 목록이 표시됩니다.  이 목록에는 수집기 이름, 상태, 수집기가 액세스하는 IP 주소, 장치에서 마지막으로 데이터를 수집한 날짜가 제공됩니다.  이 화면에서 수행할 수 있는 작업은 다음과 같습니다.

+
** 폴링 제어
** 데이터 수집기 자격 증명 변경
** 복제 데이터 수집기






== 데이터 수집기 폴링 제어

데이터 수집기를 변경한 후에는 변경 사항을 확인하기 위해 즉시 폴링을 실행하거나, 문제를 해결하는 동안 데이터 수집기를 통한 데이터 수집을 1일, 3일 또는 5일 연기할 수 있습니다.

.단계
. Data Infrastructure Insights 메뉴에서 *관찰성 > 수집기*를 클릭합니다.
. *설치된 데이터 수집기*를 클릭하세요.
. 변경하려는 데이터 수집기의 왼쪽에 있는 확인란을 선택하세요.
. *대량 작업*을 클릭하고 수행할 여론조사 작업을 선택하세요.
+
대량 작업은 여러 데이터 수집기에서 동시에 수행할 수 있습니다.  데이터 수집기를 선택하고, *대량 작업* 메뉴에서 수행할 작업을 선택합니다.





== 데이터 수집기 정보 편집

기존 데이터 수집기 설정 정보를 편집할 수 있습니다.

.단일 데이터 수집기를 편집하려면:
. Data Infrastructure Insights 메뉴에서 *관찰성 > 수집기*를 클릭하여 설치된 데이터 수집기 ​​목록을 엽니다.
. 수정하려는 데이터 수집기의 오른쪽에 있는 옵션 메뉴에서 *편집*을 클릭합니다.
+
수집기 편집 대화 상자가 열립니다.

. 변경 사항을 입력하고 *구성 테스트*를 클릭하여 새 구성을 테스트하거나 *저장*을 클릭하여 구성을 저장합니다.


여러 데이터 수집기를 편집할 수도 있습니다.

. 변경하려는 각 데이터 수집기의 왼쪽에 있는 확인란을 선택합니다.
. *대량 작업* 버튼을 클릭하고 *편집*을 선택하여 데이터 수집기 편집 대화 상자를 엽니다.
. 위와 같이 필드를 수정하세요.
+

NOTE: 선택한 데이터 수집기는 동일한 공급업체와 모델이어야 하며, 동일한 인수 단위에 있어야 합니다.

+
여러 데이터 수집기를 편집할 때 데이터 수집기 이름 필드에 "혼합"이 표시되며 편집할 수 없습니다.  사용자 이름 및 비밀번호와 같은 다른 필드는 "혼합"으로 표시되며 편집이 가능합니다.  선택한 데이터 수집기에서 동일한 값을 공유하는 필드는 현재 값을 표시하고 편집할 수 있습니다.

+
여러 데이터 수집기를 편집하는 경우 *테스트 구성* 버튼을 사용할 수 없습니다.





== 데이터 수집기 복제

복제 기능을 사용하면 다른 데이터 소스와 동일한 자격 증명 및 속성을 가진 데이터 소스를 빠르게 추가할 수 있습니다.  복제를 사용하면 동일한 장치 유형의 여러 인스턴스를 쉽게 구성할 수 있습니다.

.단계
. Data Infrastructure Insights 메뉴에서 *관찰성 > 수집기*를 클릭합니다.
. *설치된 데이터 수집기*를 클릭합니다.
. 복사하려는 데이터 수집기의 왼쪽에 있는 확인란을 클릭합니다.
. 선택한 데이터 수집기의 오른쪽에 있는 옵션 메뉴에서 *복제*를 클릭합니다.
+
복제 데이터 수집기 대화 상자가 표시됩니다.

. 필수 필드에 새로운 정보를 입력하세요.
. *저장*을 클릭하세요.


.당신이 완료한 후
복제 작업은 다른 모든 속성과 설정을 복사하여 새 데이터 수집기를 만듭니다.



== 데이터 수집기에서 대량 작업 수행

여러 데이터 수집기의 일부 정보를 동시에 편집할 수 있습니다.  이 기능을 사용하면 여러 데이터 수집기에서 여론조사를 시작하고, 여론조사를 연기하고, 여론조사를 재개할 수 있습니다.  또한 여러 개의 데이터 수집기를 삭제할 수 있습니다.

.단계
. Data Infrastructure Insights 메뉴에서 *관찰성 > 수집기*를 클릭합니다.
. *설치된 데이터 수집기*를 클릭하세요.
. 수정하려는 데이터 수집기의 왼쪽에 있는 확인란을 클릭합니다.
. 오른쪽의 옵션 메뉴에서 수행하려는 옵션을 클릭합니다.


.당신이 완료한 후
선택한 작업은 데이터 수집기에서 수행됩니다.  데이터 수집기를 삭제하도록 선택하면 작업을 수행하라는 대화 상자가 표시됩니다.
