---
sidebar: sidebar 
permalink: task_dc_redhat_virtualization.html 
keywords: data collector, Red Hat Virtualization 
summary: Red Hat Virtualization 데이터 수집기를 구성합니다. 
---
= Red Hat Virtualization 데이터 수집기
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Data Infrastructure Insights Red Hat Virtualization 데이터 수집기를 사용하여 가상화된 Linux 및 Microsoft Windows 워크로드에서 인벤토리 데이터를 수집합니다.



== 술어

Data Infrastructure Insights 에서 수집한 각 자산 유형에 대해 해당 자산에 가장 일반적으로 사용되는 용어가 표시됩니다.  이 데이터 수집기를 보거나 문제를 해결할 때 다음 용어를 염두에 두십시오.

[cols="2*"]
|===
| 공급업체/모델 용어 | Data Infrastructure Insights 용어 


| 디스크 | 가상 디스크 


| 주인 | 주인 


| 가상 머신 | 가상 머신 


| 스토리지 도메인 | 데이터 저장소 


| 논리 장치 | LUN 
|===
참고: 이는 일반적인 용어 매핑일 뿐이며 이 데이터 수집기의 모든 사례를 나타내지 않을 수 있습니다.



== 요구 사항

* REST API를 통한 포트 443을 통한 RHEV 서버의 IP 주소
* 읽기 전용 사용자 이름 및 비밀번호
* RHEV 버전 3.0+




== 구성

[cols="2*"]
|===
| 필드 | 설명 


| RHEV 서버 IP 주소 | 저장 시스템의 IP 주소 


| 사용자 이름 | 관리자 권한이 있는 사용자 이름 


| 관리자 권한 계정의 비밀번호 | 비밀번호 
|===


== 고급 구성

[cols="2*"]
|===
| 필드 | 설명 


| HTTPS 통신 포트 | RHEV와의 HTTPS 통신에 사용되는 포트 


| 재고 폴링 간격(분) | 기본값은 20분입니다. 
|===


== 문제 해결

이 데이터 수집기에 대한 추가 정보는 다음에서 찾을 수 있습니다.link:concept_requesting_support.html["지원하다"] 페이지 또는link:reference_data_collector_support_matrix.html["데이터 수집기 지원 매트릭스"] .
