---
sidebar: sidebar 
permalink: task_dc_brocade_bna.html 
keywords: data collector, Brocade, BNA 
summary: Brocade BNA 수집기 구성. 
---
= Brocade Network Advisor 데이터 수집기
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Data Infrastructure Insights Brocade Network Advisor 데이터 수집기를 사용하여 Brocade 스위치에서 인벤토리 및 성능 데이터를 수집합니다.



== 술어

Data Infrastructure Insights Brocade Network Advisor 데이터 수집기에서 다음과 같은 인벤토리 정보를 수집합니다.  Data Infrastructure Insights 에서 수집한 각 자산 유형에 대해 해당 자산에 가장 일반적으로 사용되는 용어가 표시됩니다.  이 데이터 수집기를 보거나 문제를 해결할 때 다음 용어를 염두에 두십시오.

[cols="2*"]
|===
| 공급업체/모델 용어 | Data Infrastructure Insights 용어 


| 스위치 | 스위치 


| 포트 | 포트 


| 가상 패브릭, 물리적 패브릭 | 구조 


| 논리 스위치 | 논리 스위치 
|===
참고: 이는 일반적인 용어 매핑일 뿐이며 이 데이터 수집기의 모든 사례를 나타내지 않을 수 있습니다.



== 요구 사항

이 데이터 수집기를 구성하려면 다음이 필요합니다.

* Data Infrastructure Insights 수집 부서는 BNA 서버의 TCP 포트 443에 대한 연결을 시작합니다.  BNA 서버는 14.2.1 이상 버전을 실행해야 합니다.
* Brocade Network Advisor 서버 IP 주소
* 관리자 계정의 사용자 이름과 비밀번호
* 포트 요구 사항: HTTP/HTTPS 443




== 구성

[cols="2*"]
|===
| 필드 | 설명 


| Brocade Network Advisor 서버 IP | Network Advisor 서버의 IP 주소 


| 사용자 이름 | 스위치의 사용자 이름 


| 사용자 이름 | 관리자 사용자 이름 


| 비밀번호 | 관리자 비밀번호 
|===


== 고급 구성

[cols="2*"]
|===
| 필드 | 설명 


| 연결 유형 | HTTPS(기본 포트 443) 또는 HTTP(기본 포트 80) 


| 연결 포트 재정의 | 비어 있는 경우 연결 유형 필드에서 기본 포트를 사용하고, 그렇지 않은 경우 사용할 연결 포트를 입력합니다. 


| 비밀번호 | 스위치의 비밀번호 


| 재고 폴링 간격(분) | 기본값은 40입니다 


| 액세스 게이트웨이 보고서 | Access Gateway 모드에 장치를 포함하려면 체크하세요. 


| 성능 폴링 간격(초) | 기본값은 1800입니다 
|===


== 문제 해결

이 데이터 수집기에 문제가 발생하면 시도해 볼 수 있는 몇 가지 사항은 다음과 같습니다.



=== 목록

[cols="2*"]
|===
| 문제: | 다음을 시도해 보세요: 


| 2개 이상의 노드가 Access Gateway 포트에 로그인되어 있거나 데이터 수집기가 Access Gateway 장치를 검색하지 못했다는 메시지가 나타납니다. | NPV 장치가 올바르게 작동하는지, 연결된 모든 WWN이 예상대로인지 확인하세요.  NPV 장치를 직접 구입하지 마세요.  대신, 코어 패브릭 스위치를 획득하면 NPV 장치 데이터가 수집됩니다. 
|===
추가 정보는 다음에서 찾을 수 있습니다.link:concept_requesting_support.html["지원하다"] 페이지 또는link:reference_data_collector_support_matrix.html["데이터 수집기 지원 매트릭스"] .
