---
sidebar: sidebar 
permalink: task_cs_user_management.html 
keywords: Workload Security, User, Login, account, cloud secure 
summary: 워크로드 보안 사용자 계정은 Data Infrastructure Insights 사용자 관리를 통해 관리됩니다. 
---
= 사용자 관리
:hardbreaks:
:allow-uri-read: 


[role="lead"]
워크로드 보안 사용자 계정은 Data Infrastructure Insights 통해 관리됩니다.

Data Infrastructure Insights 계정 소유자, 관리자, 사용자, 게스트의 네 가지 사용자 계정 수준을 제공합니다.  각 계정에는 특정 권한 수준이 지정됩니다.  관리자 권한이 있는 사용자 계정은 사용자를 생성하거나 수정할 수 있으며, 각 사용자에게 다음 워크로드 보안 역할 중 하나를 할당할 수 있습니다.

|===


| 역할 | 워크로드 보안 액세스 


| 관리자 | 알림, 포렌식, 데이터 수집기, 자동 응답 정책, 워크로드 보안 API 등 모든 워크로드 보안 기능을 수행할 수 있습니다.  관리자는 다른 사용자를 초대할 수도 있지만 워크로드 보안 역할만 할당할 수 있습니다. 


| 사용자 | 알림을 보고 관리하고 포렌식을 볼 수 있습니다.  사용자 역할은 알림 상태를 변경하고, 메모를 추가하고, 수동으로 스냅샷을 찍고, 사용자 액세스를 제한할 수 있습니다. 


| 손님 | 알림과 포렌식을 볼 수 있습니다.  게스트 역할은 알림 상태를 변경하거나, 메모를 추가하거나, 수동으로 스냅샷을 찍거나, 사용자 액세스를 제한할 수 없습니다. 
|===
.단계
. Workload Security에 로그인하세요
. 메뉴에서 *관리자 > 사용자 관리*를 클릭하세요.
+
Data Infrastructure Insights의 사용자 관리 페이지로 이동하게 됩니다.

. 각 사용자별로 원하는 역할을 선택하세요.


새로운 사용자를 추가할 때 원하는 역할(일반적으로 사용자 또는 게스트)을 선택하기만 하면 됩니다.

사용자 계정 및 역할에 대한 자세한 내용은 Data Infrastructure Insights 에서 확인할 수 있습니다.link:https://docs.netapp.com/us-en/cloudinsights/concept_user_roles.html["사용자 역할"] 선적 서류 비치.
