---
sidebar: sidebar 
permalink: task_dc_na_solidfire.html 
summary: NetApp SolidFire 데이터 수집기 ​​구성 
keywords: data collector, queries, create 
---
= NetApp SolidFire All-Flash Array 데이터 수집기
:hardbreaks:
:allow-uri-read: 


[role="lead"]
NetApp SolidFire All-Flash Array 데이터 수집기는 iSCSI와 Fibre Channel SolidFire 구성 모두에서 인벤토리 및 성능 수집을 지원합니다.

SolidFire 데이터 수집기는 SolidFire REST API를 활용합니다.  데이터 수집기가 있는 수집 장치는 SolidFire 클러스터 관리 IP 주소의 TCP 포트 443에 HTTPS 연결을 시작할 수 있어야 합니다.  데이터 수집기에는 SolidFire 클러스터에서 REST API 쿼리를 수행할 수 있는 자격 증명이 필요합니다.



== 술어

Data Infrastructure Insights NetApp SolidFire All-Flash Array 데이터 수집기에서 다음과 같은 인벤토리 정보를 수집합니다.  Data Infrastructure Insights 에서 수집한 각 자산 유형에 대해 해당 자산에 가장 일반적으로 사용되는 용어가 표시됩니다.  이 데이터 수집기를 보거나 문제를 해결할 때 다음 용어를 염두에 두십시오.

[cols="2*"]
|===
| 공급업체/모델 용어 | Data Infrastructure Insights 용어 


| 운전하다 | 디스크 


| 무리 | 스토리지 


| 마디 | 저장 노드 


| 용량 | 용량 


| 파이버 채널 포트 | 포트 


| 볼륨 액세스 그룹, LUN 할당 | 볼륨 맵 


| iSCSI 세션 | 볼륨 마스크 
|===
참고: 이는 일반적인 용어 매핑일 뿐이며 이 데이터 수집기의 모든 사례를 나타내지 않을 수 있습니다.



== 요구 사항

이 데이터 수집기를 구성하기 위한 요구 사항은 다음과 같습니다.

* 관리 가상 IP 주소
* 읽기 전용 사용자 이름 및 자격 증명
* 포트 443




== 구성

[cols="2*"]
|===
| 필드 | 설명 


| 관리 가상 IP 주소(MVIP) | SolidFire 클러스터의 관리 가상 IP 주소 


| 사용자 이름 | SolidFire 클러스터에 로그인하는 데 사용되는 이름 


| 비밀번호 | SolidFire 클러스터에 로그인하는 데 사용되는 비밀번호 
|===


== 고급 구성

[cols="2*"]
|===
| 필드 | 설명 


| 연결 유형 | 연결 유형을 선택하세요 


| 통신 포트 | NetApp API에 사용되는 포트 


| 재고 폴링 간격(분) | 기본값은 20분입니다 


| 성능 폴링 간격(초) | 기본값은 300초입니다 
|===


== 문제 해결

SolidFire 오류를 보고하면 다음과 같이 Data Infrastructure Insights 에 표시됩니다.

SolidFire 장치에서 데이터를 검색하는 동안 오류 메시지가 수신되었습니다.  호출은 <method> (<parameterString> )입니다.  장치의 오류 메시지는 다음과 같습니다(장치 설명서를 확인하세요): <message>_

어디:

* <method>는 GET이나 PUT과 같은 HTTP 메서드입니다.
* <parameterString>은 REST 호출에 포함된 매개변수의 쉼표로 구분된 목록입니다.
* <메시지>는 장치가 오류 메시지로 반환한 내용입니다.


이 데이터 수집기에 대한 추가 정보는 다음에서 찾을 수 있습니다.link:concept_requesting_support.html["지원하다"] 페이지 또는link:reference_data_collector_support_matrix.html["데이터 수집기 지원 매트릭스"] .
