---
sidebar: sidebar 
permalink: task_dc_na_storagegrid.html 
summary: NetApp StorageGRID 데이터 수집기를 구성합니다 
keywords: data collector, queries, create, storagegrid 
---
= NetApp StorageGRID 데이터 수집기
:hardbreaks:
:allow-uri-read: 


[role="lead"]
NetApp StorageGRID 데이터 수집기는 StorageGRID 구성의 인벤토리 및 성능 수집을 지원합니다.

[NOTE]
====
기본 하드웨어 토폴로지 및 구성에 관계 없이 모든 StorageGRID 시스템에서 DII 권한에 대한 일관된 측정을 제공하기 위해 Data Infrastructure Insights 물리적 디스크 레이아웃을 기반으로 하는 RAW 용량 대신 사용 가능한 총 용량(storagegrid_storage_utilization_total_space_bytes)을 사용합니다.

용량 기반 라이선스 모델을 사용하는 고객의 경우 StorageGRID "객체" 스토리지로 측정됩니다.

레거시(MU) 라이선스 모델을 사용하는 고객의 경우 StorageGRID 1MU당 40TiB의 비율로 보조 스토리지로 측정됩니다.

====


== 용어

Data Infrastructure Insights는 NetApp StorageGRID 수집기에서 다음과 같은 인벤토리 정보를 수집합니다. 획득한 각 자산 유형에 대해 이 자산에 가장 일반적으로 사용되는 용어가 표시됩니다. 이 데이터 수집기를 보거나 문제를 해결할 때 다음 용어를 염두에 두십시오.

[cols="2*"]
|===
| 공급업체/모델 기간 | Data Infrastructure Insights 용어 


| StorageGRID | 스토리지 


| 노드 | 노드 


| 테넌트 | 스토리지 풀 


| 버킷 | 내부 볼륨 
|===


== 요구 사항

다음은 이 데이터 소스를 구성하기 위한 요구 사항입니다.

* StorageGRID 호스트 IP 주소입니다
* 메트릭 쿼리 및 테넌트 액세스 역할이 할당된 사용자의 사용자 이름 및 암호입니다
* 포트 443




== 구성

[cols="2*"]
|===
| 필드에 입력합니다 | 설명 


| StorageGRID 호스트 IP 주소입니다 | StorageGRID 어플라이언스의 관리 가상 IP 주소입니다 


| 사용자 이름 | StorageGRID 어플라이언스에 로그인하는 데 사용되는 이름입니다 


| 암호 | StorageGRID 어플라이언스에 로그인하는 데 사용되는 암호입니다 
|===


== 고급 구성

[cols="2*"]
|===
| 필드에 입력합니다 | 설명 


| 재고 폴링 간격(분) | 기본값은 60분입니다 


| 성능 폴링 간격(초) | 기본값은 900초입니다 
|===


== SSO(Single Sign-On)

link:https://docs.netapp.com/sgws-112/index.jsp["StorageGRID"]펌웨어 버전은 해당 API 버전을 사용하며 3.0 API 이상 버전은 SSO(Single Sign-On) 로그인을 지원합니다.

|===


| 펌웨어 버전입니다 | API 버전 | SSO(Single Sign On) 지원 


| 11.1 | 2 | 아니요 


| 11.2 | 3.0 | 예 


| 11.5 | 3.3 | 예 
|===


== 문제 해결

이 데이터 수집기에 대한 추가 정보는 페이지 또는 에서 찾을 link:concept_requesting_support.html["지원"]link:reference_data_collector_support_matrix.html["Data Collector 지원 매트릭스"]수 있습니다.
