---
sidebar: sidebar 
permalink: task_dc_qumulo_rest.html 
keywords: data collector, qumulo, rest 
summary: Qumulo REST 데이터 수집기 구성. 
---
= Qumulo REST 데이터 수집기
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Data Infrastructure Insights는 이 수집기를 사용하여 Qumulo 스토리지에서 인벤토리 및 성능 데이터를 수집합니다.



[[terminology]]
== 술어

Data Infrastructure Insights 이 데이터 수집기로부터 다음과 같은 인벤토리 정보를 수집합니다.  Data Infrastructure Insights 에서 수집한 각 자산 유형에 대해 해당 자산에 가장 일반적으로 사용되는 용어가 표시됩니다.  이 데이터 수집기를 보거나 문제를 해결할 때 다음 용어를 염두에 두십시오.

[cols="50,50"]
|===
| 공급업체/모델 용어 | Data Infrastructure Insights 용어 


| 운전하다 | 디스크 


| 무리 | 스토리지 


| 마디 | 저장 노드 
|===
참고: 이는 일반적인 용어 매핑일 뿐이며 이 데이터 수집기의 모든 사례를 나타내지 않을 수 있습니다.



[[requirements]]
== 요구 사항

이 데이터 수집기를 구성하려면 다음 정보가 필요합니다.

* 읽기 권한 이상이 있는 사용자 계정과 비밀번호.
* Qumulo 클러스터의 IP 주소/정규화된 도메인 이름
* 8000번 포트로의 HTTPS 접속




[[configuration]]
== 구성

[cols="50,50"]
|===
| 필드 | 설명 


| Qumulo IP 주소 | Qumulo 스토리지의 IP 주소 또는 정규화된 도메인 이름 


| 사용자 이름 | Qumulo 사용자 이름 


| 비밀번호 | Qumulo에 사용되는 암호 
|===


[[advanced-configuration]]
== 고급 구성

[cols="50,50"]
|===
| 필드 | 설명 


| HTTPS 포트 | 기본값은 8000입니다. 


| 재고 폴링 간격(분) | 재고 조사 간격입니다. 기본값은 30입니다. 


| 성능 폴링 간격(분) | 성능 폴링 간격입니다. 기본값은 5입니다. 
|===


[[troubleshooting]]
== 문제 해결

추가 정보는 다음에서 찾을 수 있습니다.link:concept_requesting_support.html["지원하다"] 페이지 또는link:reference_data_collector_support_matrix.html["데이터 수집기 지원 매트릭스"] .
