---
sidebar: sidebar 
permalink: task_device_resolution_preferences.html 
keywords: Automatic, AR, AHR, Host, automatic device resolution, FC, Identify 
summary:  
---
= 환경 설정 탭에서 옵션 설정
:hardbreaks:
:allow-uri-read: 


[role="lead"]
장치 확인 환경 설정 탭을 사용하면 자동 확인 일정을 만들고, 식별에 포함하거나 제외할 스토리지 및 테이프 공급업체를 지정하고, DNS 조회 옵션을 설정할 수 있습니다.



== 자동 해결 일정

자동 해결 일정은 자동 장치 해결이 실행되는 시기를 지정할 수 있습니다.

|===


| 옵션 | 설명 


| 모든 | 이 옵션을 사용하면 일, 시간 또는 분 간격으로 자동 장치 확인을 실행할 수 있습니다. 


| 매일 | 이 옵션을 사용하면 매일 특정 시간에 자동으로 장치 확인을 실행할 수 있습니다. 


| 수동으로 | 이 옵션을 사용하면 자동 장치 확인만 수동으로 실행할 수 있습니다. 


| 모든 환경 변화에 대하여 | 이 옵션을 사용하면 환경에 변화가 있을 때마다 자동으로 장치 확인을 실행합니다. 
|===
_Manually_를 지정하면 매일 밤 자동 장치 확인이 비활성화됩니다.



== DNS 처리 옵션

DNS 처리 옵션을 사용하면 다음 기능을 선택할 수 있습니다.

* DNS 조회 결과 처리가 활성화된 경우 확인된 장치에 추가할 DNS 이름 목록을 추가할 수 있습니다.
* IP 자동 확인을 선택할 수 있습니다. DNS 조회를 사용하여 NFS 공유에 액세스하는 iSCSI 이니시에이터와 호스트에 대한 자동 호스트 확인을 활성화합니다.  이것이 지정되지 않으면 FC 기반 해결만 수행됩니다.
* 호스트 이름에 밑줄을 허용하고 결과에 표준 포트 별칭 대신 "connected to" 별칭을 사용할 수 있습니다.




=== 특정 스토리지 및 테이프 공급업체 포함 또는 제외

자동 해결을 위해 특정 스토리지 및 테이프 공급업체를 포함하거나 제외할 수 있습니다.  예를 들어, 특정 호스트가 레거시 호스트가 되어 새로운 환경에서 제외해야 하는 경우 특정 공급업체를 제외하는 것이 좋습니다.  이전에 제외했지만 더 이상 제외하지 않으려는 공급업체를 다시 추가할 수도 있습니다.


NOTE: 테이프에 대한 장치 확인 규칙은 공급업체 환경 설정에서 해당 WWN의 공급업체가 _테이프로만 포함_으로 설정된 WWN에만 적용됩니다.

또한 참조하세요:link:concept_device_resolution_regex_examples.html["정규 표현식 예제"]
