---
sidebar: sidebar 
permalink: task_create_application.html 
summary: 필요에 따라 테넌트의 자산에 적용할 애플리케이션을 정의합니다. 
keywords: application, create application, 
---
= 애플리케이션 만들기
:hardbreaks:
:allow-uri-read: 


[role="lead"]
테넌트에서 실행되는 특정 애플리케이션과 관련된 데이터를 추적하려면 Data Infrastructure Insights 에서 애플리케이션을 정의할 수 있습니다.

.이 작업에 관하여
Data Infrastructure Insights 사용하면 사용량이나 비용 보고 등을 위해 애플리케이션과 연결된 자산의 데이터를 추적할 수 있습니다.

.단계
. Data Infrastructure Insights 메뉴에서 *관찰성 > 강화 > 애플리케이션*을 클릭합니다.  선택하다
+
애플리케이션 추가 대화 상자가 표시됩니다.

. 애플리케이션에 대한 고유한 이름을 입력하세요.
. 신청서의 우선순위를 선택하세요.
. *저장*을 클릭하세요.


애플리케이션을 정의한 후 자산에 할당할 수 있습니다.



== 자산에 애플리케이션 할당

이 절차에서는 예를 들어 애플리케이션을 호스트에 할당합니다.  애플리케이션에 호스트, 가상 머신, 볼륨 또는 내부 볼륨을 할당할 수 있습니다.

.단계
. 애플리케이션에 할당할 자산을 찾으세요.
. *쿼리 > +새 쿼리*를 클릭하고 호스트를 검색합니다.
. 애플리케이션과 연결할 호스트의 왼쪽에 있는 확인란을 클릭합니다.
. *대량 작업 > 애플리케이션 추가*를 클릭합니다.
. 자산을 할당할 애플리케이션을 선택하세요.


새로 할당한 모든 애플리케이션은 다른 자산에서 파생된 자산의 모든 애플리케이션을 재정의합니다.  예를 들어, 볼륨은 호스트로부터 애플리케이션을 상속받으며, 볼륨에 새 애플리케이션이 할당되면 새 애플리케이션이 파생된 애플리케이션보다 우선합니다.


NOTE: 관련 자산이 대량으로 있는 환경의 경우 해당 자산에 대한 애플리케이션 할당을 상속하는 데 몇 분이 걸릴 수 있습니다.  관련 자산이 많은 경우 상속이 이루어지는 데 더 많은 시간이 소요될 수 있습니다.

.당신이 완료한 후
호스트를 애플리케이션에 할당한 후 나머지 자산을 애플리케이션에 할당할 수 있습니다.  애플리케이션의 랜딩 페이지에 액세스하려면 *관리 > 애플리케이션*을 클릭하고 생성한 애플리케이션을 선택하세요.
