---
sidebar: sidebar 
permalink: task_dc_amazon_ec2.html 
keywords: data collector, EC2, 
summary: Amazon EC2 데이터 수집기 구성. 
---
= Amazon EC2 데이터 수집기 구성
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Data Infrastructure Insights Amazon EC2 데이터 수집기를 사용하여 EC2 인스턴스에서 인벤토리 및 성능 데이터를 수집합니다.



== 요구 사항

Amazon EC2 장치에서 데이터를 수집하려면 다음 정보가 필요합니다.

* 다음 중 하나가 있어야 합니다.
+
** IAM 역할 인증을 사용하는 경우 Amazon EC2 클라우드 계정의 *IAM 역할*입니다.  IAM 역할은 인수 단위가 AWS 인스턴스에 설치된 경우에만 적용됩니다.
** IAM 액세스 키 인증을 사용하는 경우 Amazon EC2 클라우드 계정의 *IAM 액세스 키* ID 및 비밀 액세스 키입니다.


* "목록 구성" 권한이 있어야 합니다.
* 포트 443 HTTPS
* EC2 인스턴스는 가상 머신 또는 (덜 자연스럽게도) 호스트로 보고될 수 있습니다.  EBS 볼륨은 VM에서 사용되는 VirtualDisk와 VirtualDisk의 용량을 제공하는 DataStore로 모두 보고될 수 있습니다.


액세스 키는 액세스 키 ID(예: AKIAIOSFODNN7EXAMPLE)와 비밀 액세스 키(예: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY)로 구성됩니다.  Amazon EC2 SDK, REST 또는 쿼리 API 작업을 사용하는 경우 액세스 키를 사용하여 EC2에 대한 프로그래밍 요청에 서명합니다.  이러한 키는 Amazon과의 계약서와 함께 제공됩니다.



== 구성

아래 표에 따라 데이터 수집기 필드에 데이터를 입력합니다.

[cols="2*"]
|===
| 필드 | 설명 


| AWS 지역 | AWS 지역 선택 


| IAM 역할 | AWS의 AU에서 획득한 경우에만 사용 가능합니다.  자세한 내용은 아래를 참조하세요.<<iam-role,IAM 역할>> . 


| AWS IAM 액세스 키 ID | AWS IAM 액세스 키 ID를 입력하세요.  IAM 역할을 사용하지 않는 경우 필수입니다. 


| AWS IAM 비밀 액세스 키 | AWS IAM 비밀 액세스 키를 입력하세요.  IAM 역할을 사용하지 않는 경우 필수입니다. 


| AWS에서 API 요청에 대해 요금을 청구한다는 것을 알고 있습니다. | Data Infrastructure Insights 폴링을 통해 이루어진 API 요청에 대해 AWS에서 요금을 청구한다는 사실을 이해했는지 확인하려면 여기를 선택하세요. 
|===


== 고급 구성

[cols="2*"]
|===
| 필드 | 설명 


| 추가 지역 포함 | 여론조사에 포함할 추가 지역을 지정합니다. 


| 교차 계정 역할 | 다양한 AWS 계정의 리소스에 액세스하기 위한 역할입니다. 


| 재고 폴링 간격(분) | 기본값은 60입니다 


| 태그로 VM 필터링을 적용하려면 '제외' 또는 '포함'을 선택하세요. | 데이터를 수집할 때 태그별로 VM을 포함할지 제외할지 지정합니다.  '포함'을 선택한 경우 태그 키 필드는 비워둘 수 없습니다. 


| VM을 필터링할 태그 키 및 값 | *+ 태그 필터링*을 클릭하여 VM(및 관련 디스크)을 포함/제외하고, VM의 태그 키 및 값과 일치하는 키와 값을 필터링합니다.  태그 키는 필수이고, 태그 값은 선택 사항입니다.  태그 값이 비어 있으면 태그 키와 일치하는 한 VM이 필터링됩니다. 


| 성능 폴링 간격(초) | 기본값은 1800입니다 


| CloudWatch 에이전트 메트릭 네임스페이스 | 데이터를 수집할 EC2/EBS의 네임스페이스입니다.  이 네임스페이스의 기본 메트릭 이름이 변경되면 Data Infrastructure Insights 이름이 변경된 데이터를 수집하지 못할 수 있습니다.  기본 메트릭 이름을 그대로 두는 것이 좋습니다. 
|===


== IAM 액세스 키

액세스 키는 IAM 사용자 또는 AWS 계정 루트 사용자의 장기 자격 증명입니다.  액세스 키는 AWS CLI 또는 AWS API에 대한 프로그래밍 요청에 서명하는 데 사용됩니다(직접 또는 AWS SDK 사용).

액세스 키는 액세스 키 ID와 비밀 액세스 키의 두 부분으로 구성됩니다.  _IAM 액세스 키_ 인증(_IAM 역할_ 인증과 반대)을 사용하는 경우 요청 인증을 위해 액세스 키 ID와 비밀 액세스 키를 함께 사용해야 합니다.  자세한 내용은 Amazon 설명서를 참조하세요.link:https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_access-keys.html["액세스 키"] .



== IAM 역할

_IAM 역할_ 인증(IAM 액세스 키 인증과 반대)을 사용하는 경우, 생성하거나 지정하는 역할에 리소스에 액세스하는 데 필요한 적절한 권한이 있는지 확인해야 합니다.

예를 들어, _InstanceEc2ReadOnly_라는 IAM 역할을 생성하는 경우 이 IAM 역할에 대한 모든 EC2 리소스에 대한 EC2 읽기 전용 목록 액세스 권한을 부여하는 정책을 설정해야 합니다.  또한, 이 역할이 여러 계정에서 역할을 수행할 수 있도록 STS(보안 토큰 서비스) 액세스 권한을 부여해야 합니다.

IAM 역할을 생성한 후에는 새 EC2 인스턴스나 기존 EC2 인스턴스를 생성할 때 해당 역할을 연결할 수 있습니다.

EC2 인스턴스에 IAM 역할 _InstanceEc2ReadOnly_를 연결하면 IAM 역할 이름으로 인스턴스 메타데이터를 통해 임시 자격 증명을 검색하고 이를 사용하여 이 EC2 인스턴스에서 실행되는 모든 애플리케이션에서 AWS 리소스에 액세스할 수 있습니다.

자세한 내용은 Amazon 문서를 참조하세요.link:https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles.html["IAM 역할"] .

참고: IAM 역할은 인수 부서가 AWS 인스턴스에서 실행되는 경우에만 사용할 수 있습니다.



== Amazon 태그를 Data Infrastructure Insights 주석에 매핑

Amazon EC2 데이터 수집기에는 EC2에 구성된 태그로 Data Infrastructure Insights 주석을 채울 수 있는 옵션이 포함되어 있습니다.  주석의 이름은 EC2 태그와 정확히 일치해야 합니다.  Data Infrastructure Insights 항상 동일한 이름의 텍스트 유형 주석을 채우고, 다른 유형(숫자, 부울 등)의 주석을 채우기 위해 최선을 다합니다.  주석이 다른 유형이고 데이터 수집기가 주석을 채우지 못하는 경우 주석을 제거하고 텍스트 유형으로 다시 만들어야 할 수도 있습니다.

AWS는 대소문자를 구분하지만, Data Infrastructure Insights 대소문자를 구분하지 않습니다.  따라서 Data Infrastructure Insights 에서 "OWNER"라는 이름의 주석을 생성하고 EC2에서 "OWNER", "Owner", "owner"라는 이름의 태그를 생성하면 EC2의 모든 "owner" 변형이 Cloud Insight의 "OWNER" 주석에 매핑됩니다.



== 추가 지역 포함

AWS 데이터 수집기 *고급 구성* 섹션에서 *추가 지역 포함* 필드를 설정하여 쉼표나 세미콜론으로 구분하여 추가 지역을 포함할 수 있습니다.  기본적으로 이 필드는 모든 미국 AWS 지역에서 데이터를 수집하는 *_us-.*_*로 설정됩니다.  _모든_ 지역에서 수집하려면 이 필드를 *_.*_*로 설정하세요.  *추가 지역 포함* 필드가 비어 있으면 데이터 수집기는 *구성* 섹션에 지정된 대로 *AWS 지역* 필드에 지정된 자산을 수집합니다.



== AWS 자식 계정에서 수집

Data Infrastructure Insights 단일 AWS 데이터 수집기 ​​내에서 AWS에 대한 자식 계정 수집을 지원합니다.  이 컬렉션에 대한 구성은 AWS 환경에서 수행됩니다.

* 각 자식 계정에 AWS 역할을 구성하여 기본 계정 ID가 자식 계정의 EC2 세부 정보에 액세스할 수 있도록 해야 합니다.
* 각 자식 계정에는 동일한 문자열로 구성된 역할 이름이 있어야 합니다.
* 이 역할 이름 문자열을 Data Infrastructure Insights AWS Data Collector *고급 구성* 섹션의 *교차 계정 역할* 필드에 입력합니다.
* 수집기가 설치된 계정에는 _대리인 액세스 관리자_ 권한이 있어야 합니다.  를 참조하십시오link:https://docs.aws.amazon.com/accounts/latest/reference/using-orgs-delegated-admin.html["AWS 문서"] 자세한 내용은.


모범 사례: AWS에서 미리 정의한 _AmazonEC2ReadOnlyAccess_ 정책을 EC2 기본 계정에 할당하는 것이 좋습니다.  또한, AWS에 쿼리를 실행하려면 데이터 소스에 구성된 사용자에게 최소한 사전 정의된 _AWSOrganizationsReadOnlyAccess_ 정책이 할당되어야 합니다.

Data Infrastructure Insights AWS 자식 계정에서 데이터를 수집할 수 있도록 환경을 구성하는 방법에 대한 자세한 내용은 다음을 참조하세요.

link:https://docs.aws.amazon.com/IAM/latest/UserGuide/tutorial_cross-account-with-roles.html["튜토리얼: IAM 역할을 사용하여 AWS 계정 간 액세스 위임"]

link:https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_common-scenarios_aws-accounts.html["AWS 설정: 자신이 소유한 다른 AWS 계정의 IAM 사용자에게 액세스 권한 제공"]

link:https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_create_for-user.html["IAM 사용자에게 권한을 위임하는 역할 생성"]



== 문제 해결

이 데이터 수집기에 대한 추가 정보는 다음에서 찾을 수 있습니다.link:concept_requesting_support.html["지원하다"] 페이지 또는link:reference_data_collector_support_matrix.html["데이터 수집기 지원 매트릭스"] .
