---
sidebar: sidebar 
permalink: task_dc_emc_unisphere_rest.html 
keywords: data collector, Unisphere, EMC 
summary: Dell EMC Unisphere REST 데이터 수집기를 구성합니다. 
---
= Dell EMC Unisphere REST 데이터 수집기 구성
:hardbreaks:
:allow-uri-read: 


[role="lead"]
이 데이터 수집기는 Dell EMC Unisphere for PowerMax/Vmax 3 관리 시스템에서 인벤토리 및 성능 데이터를 수집합니다.

Dell/EMC는 Unisphere 10.0까지 볼륨별 통계를 도입하지 않았습니다. 이 데이터 수집기는 9.2.0 이상을 지원하지만 볼륨 통계가 존재하지 않으므로 이를 수집할 수 없습니다.

Vmax/PowerMax 인스턴스용 Unisphere 하나가 Symmetrix Vmax 3 이상 스토리지 어레이를 하나 이상 관리할 수 있습니다. 이 수집기는 기본적으로 해당 Unisphere 인스턴스에 "로컬"인 모든 스토리지 어레이를 검색하려고 시도합니다.  Unisphere 인스턴스가 "원격" 어레이(즉, SRDF 복제를 통해 연결된 어레이)를 발견하면 해당 어레이는 무시되며, 해당 어레이를 발견하려면 Data Infrastructure Insights 에서 추가 Unisphere 수집기를 생성하여 해당 사이트에서 해당 어레이를 로컬로 발견한 Unisphere 인스턴스를 지정해야 합니다.

구성을 위해 데이터 수집기에는 Unisphere 서버의 IP 주소/FQDN, 포트 8443에 대한 TCP 연결, 사용자 이름 및 비밀번호가 필요합니다.



== 요구 사항

* Unisphere 서버의 IP 주소/정규화된 도메인 이름
* 사용자 이름과 비밀번호
* 포트 8443.




== 구성

[cols="2*"]
|===
| 필드 | 설명 


| Unisphere 서버의 IP 주소 | Unisphere 서버의 IP 주소 또는 정규화된 도메인 이름 


| 유니스피어 포트 | 기본값은 8443입니다 


| 사용자 이름 | Unisphere 서버의 사용자 이름 


| 비밀번호 | Unisphere 서버에 사용되는 비밀번호 
|===


== 고급 구성

[cols="2*"]
|===
| 필드 | 설명 


| 재고 폴링 간격(분) | 기본값은 40분입니다. 


| 성능 폴링 간격(초) | 성과 여론조사 간격. 


| '제외' 또는 '포함'을 선택하여 목록을 지정하세요. | VM을 포함할지 제외할지 지정 


| 인벤토리 필터 장치 목록 | 필터링을 위한 VM 목록(쉼표로 구분, 값에 쉼표가 사용된 경우 세미콜론으로 구분) 


| Unisphere 성능 폴링 간격(초) | 기본값은 300초입니다 
|===


== 문제 해결

이 데이터 수집기에 문제가 발생하면 시도해 볼 수 있는 몇 가지 사항은 다음과 같습니다.



=== 목록

[cols="2*"]
|===
| 문제: | 다음을 시도해 보세요: 


| 오류: 사용자 인증에 실패했습니다. | 이 장치에 대한 자격 증명이 올바른지 확인하세요. 


| 인벤토리 최근 상태: 예기치 않은 데이터 검색됨 - 어레이에서 0 볼륨 보고됨 | 일반적으로 권한 부여(인증이 아님) 문제를 나타냅니다.  자격 증명이 정확한지, 사용자 이름에 모든 볼륨을 나열하고 해당 속성을 볼 수 있는 권한이 있는지 확인하세요. 
|===
추가 정보는 다음에서 찾을 수 있습니다.link:concept_requesting_support.html["지원하다"] 페이지 또는link:reference_data_collector_support_matrix.html["데이터 수집기 지원 매트릭스"] .
