---
sidebar: sidebar 
permalink: task_dc_emc_recoverpoint.html 
keywords: data collector, RecoverPoint, EMC, DELL 
summary: DELL EMC RecoverPoint 데이터 수집기를 구성합니다. 
---
= Dell EMC RecoverPoint 데이터 수집기
:hardbreaks:
:allow-uri-read: 


[role="lead"]
EMC RecoverPoint 데이터 수집기의 주요 사용 사례는 RecoverPoint 스토리지 어플라이언스가 지원하는 볼륨 간 복제 관계를 검색하는 것입니다.  이 수집기는 Recoverpoint 어플라이언스 자체도 검색합니다.  Dell/EMC는 이 수집기에서 지원하지 않는 VM용 VMware 백업 솔루션인 "VM용 RecoverPoint"를 판매합니다.

구성을 위해 데이터 수집기에는 스토리지 프로세서의 IP 주소와 읽기 전용 사용자 이름과 비밀번호가 필요합니다.

EMC RecoverPoint 데이터 수집기는 RecoverPoint가 다른 스토리지 어레이에서 조정하는 볼륨 간 복제 관계를 수집합니다.  Data Infrastructure Insights 각 RecoverPoint 클러스터에 대한 스토리지 배열을 보여주고 해당 클러스터의 노드와 스토리지 포트에 대한 인벤토리 데이터를 수집합니다.  스토리지 풀이나 볼륨 데이터는 수집되지 않습니다.



== 요구 사항

이 데이터 수집기를 구성하려면 다음 정보가 필요합니다.

* 저장 프로세서의 IP 주소 또는 정규화된 도메인 이름
* 읽기 전용 사용자 이름 및 비밀번호
* 포트 443을 통한 REST API 접근




== 구성

[cols="2*"]
|===
| 필드 | 설명 


| RecoverPoint 주소 | RecoverPoint 클러스터의 IP 주소 또는 정규화된 도메인 이름 


| 사용자 이름 | RecoverPoint 클러스터의 사용자 이름 


| 비밀번호 | RecoverPoint 클러스터에 사용되는 비밀번호 
|===


== 고급 구성

[cols="2*"]
|===
| 필드 | 설명 


| TCP 포트 | Recoverpoint 클러스터에 연결하는 데 사용되는 TCP 포트 


| 재고 폴링 간격(분) | 재고 조사 간격. 기본값은 20분입니다. 


| 제외된 클러스터 | 폴링 시 제외할 클러스터 ID 또는 이름의 쉼표로 구분된 목록입니다. 
|===


== 문제 해결

이 데이터 수집기에 대한 추가 정보는 다음에서 찾을 수 있습니다.link:concept_requesting_support.html["지원하다"] 페이지 또는link:reference_data_collector_support_matrix.html["데이터 수집기 지원 매트릭스"] .
