---
sidebar: sidebar 
permalink: task_dc_redhat_openshift_virtualization.html 
keywords: data collector, Red Hat OpenShift Virtualization 
summary: Red Hat OpenShift Virtualization 데이터 수집기 구성. 
---
= Red Hat OpenShift Virtualization 데이터 수집기
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
DII Red Hat OpenShift Virtualization 컬렉터는 OpenShift Virtualization 환경에서 실행 중인 OSV 컴퓨팅 워크로드를 검색하려고 시도합니다. 이 컬렉터는 모든 Open Shift Pod를 검색하지는 않습니다. 이 컬렉터는 HTTPS REST API 기반입니다. OSV 클러스터당 하나의 컬렉터를 생성하는 것이 좋습니다.

이 컬렉터의 인증 방식은 서비스 계정에 연결된 인증 토큰입니다. 사용자 계정과 토큰을 모두 생성하려면:

....
oc create sa acq-readonly-cluster-user -n default
oc adm policy add-cluster-role-to-user cluster-reader -z acq-readonly-cluster-user --rolebinding-name acq-readonly-cluster-user-binding
oc adm policy add-cluster-role-to-user cluster-monitoring-view -z acq-readonly-cluster-user --rolebinding-name acq-readonly-cluster-monitor-user-binding
....
이 3가지 명령을 실행하고 오류가 있는지 확인하십시오.

명령 실행이 완료되면:

 oc sa new-token acq-readonly-cluster-user
이렇게 하면 사용자에게 바인딩된 토큰이 생성됩니다.

마지막으로 OSV 관리자가 다음 명령을 실행하도록 요청할 수도 있습니다.

 oc cluster-info
이렇게 하면 관리용 호스트 이름/IP 주소가 반환됩니다. 각 DII OSV 컬렉터는 OSV 관리를 위해 해당 IP/호스트 이름을 가리키도록 설정해야 합니다.



== 술어

Data Infrastructure Insights 에서 수집한 각 자산 유형에 대해 해당 자산에 가장 일반적으로 사용되는 용어가 표시됩니다.  이 데이터 수집기를 보거나 문제를 해결할 때 다음 용어를 염두에 두십시오.

[cols="2*"]
|===
| 공급업체/모델 용어 | Data Infrastructure Insights 용어 


| 디스크 | 가상 디스크 


| 주인 | 주인 


| 가상 머신 | 가상 머신 


| 스토리지 도메인 | 데이터 저장소 


| 논리 장치 | LUN 
|===
참고: 이는 일반적인 용어 매핑일 뿐이며 이 데이터 수집기의 모든 사례를 나타내지 않을 수 있습니다.



== 요구 사항

* REST API를 통해 포트 443을 사용하는 Red Hat OpenShift Virtualization 서버의 IP 주소
* 읽기 전용 사용자 이름 및 비밀번호
* RHEV 버전 3.0+




== 구성

[cols="2*"]
|===
| 필드 | 설명 


| RHEV 서버 IP 주소 | 저장 시스템의 IP 주소 


| 사용자 이름 | 관리자 권한이 있는 사용자 이름 


| 관리자 권한 계정의 비밀번호 | 비밀번호 
|===


== 고급 구성

[cols="2*"]
|===
| 필드 | 설명 


| HTTPS 통신 포트 | RHOV와의 HTTPS 통신에 사용되는 포트 


| 재고 폴링 간격(분) | 기본값은 20분입니다. 
|===


== 문제 해결

이 데이터 수집기에 대한 추가 정보는 다음에서 찾을 수 있습니다.link:concept_requesting_support.html["지원하다"] 페이지 또는link:reference_data_collector_support_matrix.html["데이터 수집기 지원 매트릭스"] .
