---
sidebar: sidebar 
permalink: task_io_density_report_no_root.html 
summary: 높은 I/O 밀도를 쿼리할 때는 루트 볼륨을 제외해야 합니다. 
keywords: NetApp, root volume, high I/O, 
---
= IO 밀도 보고서가 내부 데이터 볼륨만 설명하도록 보장
:hardbreaks:
:allow-uri-read: 


[role="lead"]
NetApp 루트 볼륨에는 스토리지 시스템을 관리하기 위한 디렉토리와 구성 파일이 포함되어 있습니다.  높은 I/O 밀도를 쿼리할 때는 이러한 루트 볼륨을 제외해야 합니다.

환경을 모니터링할 때 높은 I/O 밀도 수치를 생성하는 내부 데이터 볼륨을 확인하는 것이 더 중요합니다.  데이터 볼륨만 정확하게 식별하려면 I/O 밀도를 모니터링하는 데 사용하는 쿼리에서 NetApp 내부 볼륨을 분리해야 합니다.

이 가이드에서는 NetApp 루트 집계를 쉽게 식별하고, 내부 볼륨 쿼리 결과에서 이를 분리하고, 시스템에 새로운 NetApp 루트 집계가 추가될 때 이를 제외하는 규칙을 만드는 방법을 설명합니다.  다음 Insight 기능은 I/O 밀도 보고서가 내부 데이터 볼륨에서 파생되도록 보장하는 데 사용됩니다.

* Insight에서 모니터링하는 모든 NetApp 루트 집계를 식별하기 위한 쿼리가 생성됩니다.
* 각 NetApp 루트 집계에 주석이 할당됩니다.
* 새로운 NetApp 루트 집계에 주석을 적용하기 위해 주석 규칙이 생성됩니다.


이 가이드의 단계는 다른 공급업체의 스토리지 시스템에도 적용할 수 있습니다.  스토리지 시스템을 관리하기 위한 디렉토리와 구성 파일이 포함된 볼륨을 식별하고 비슷한 단계를 사용하여 이러한 볼륨을 제외해야 합니다.



== NetApp 루트 집계를 식별하기 위한 쿼리 생성

쿼리는 사용자가 선택한 기준에 따라 세부적인 수준의 검색을 제공합니다.  쿼리를 사용하면 NetApp 루트 집계가 포함된 테넌트의 내부 볼륨을 검색할 수 있습니다.

.단계
. 테넌트에서 NetApp 루트 집계를 식별하기 위한 쿼리를 만듭니다. *쿼리 > 새 쿼리 > 리소스 유형 선택* (?)을 클릭합니다.
. *저장 풀*을 클릭하세요
. 루트 집계의 이름을 입력하세요
+
이 예에서는 이름으로 "aggr0"을 사용합니다.  집계를 생성할 때 이름에 대한 다음 요구 사항만 따라야 합니다.

+
.. 문자나 밑줄(_)로 시작해야 합니다.
.. 문자, 숫자, 밑줄만 포함할 수 있습니다.
.. 250자 이하여야 합니다.  대부분의 경우 집계의 이름은 aggr0, aggr_0 또는 이와 비슷한 이름입니다.  테넌트의 모든 NetApp 루트 집계를 식별하려면 반복적인 프로세스가 필요할 수 있습니다.


. *저장*을 클릭하고 새 쿼리의 이름을 입력합니다.
+
앞서 언급했듯이 이는 반복적인 프로세스일 수 있으며 모든 NetApp 루트 집계를 식별하려면 여러 개의 쿼리가 필요할 수 있습니다.





== 쿼리에서 반환된 루트 볼륨에 대한 주석을 만듭니다.

주석은 자산에 할당하는 특수한 메모로, 이를 통해 주석을 기준으로 자산을 필터링할 수 있습니다.  귀하가 만든 주석은 테넌트의 NetApp 루트 집계를 식별하고 해당 집계가 특정 보고서에 포함되지 않도록 하는 데 사용됩니다.

.시작하기 전에
"높은 I/O 밀도" 보고서에서 제외하려는 모든 루트 집계를 식별했어야 합니다.

.단계
. Data Infrastructure Insights 메뉴에서 *관리 > 주석*을 클릭합니다.
. *추가*를 클릭하세요
+
.. 주석의 이름을 입력하세요: *RootAggr*
.. 주석에 대한 설명을 입력하세요: *"높은 I/O 밀도" 보고서에서 루트 집계 제거*
.. 주석 유형을 입력하세요: *Boolean*


. *저장*을 클릭하세요




== I/O 밀도 보고서에서 특정 집계를 자동으로 제외하기 위한 주석 규칙을 만듭니다.

개별 자산에 수동으로 주석을 적용하는 대신, 주석 규칙을 사용하여 여러 자산에 자동으로 주석을 적용할 수 있습니다.  주석 규칙은 사용자가 만든 쿼리를 기반으로 하며 시스템에서 실행되면 기존 자산 세트에 새 자산을 추가합니다.  이러한 자산 집합을 보고서에서 제외하면 새 자산도 자동으로 제외됩니다.

.시작하기 전에
테넌트에서 식별한 NetApp 루트 집계를 식별하는 쿼리를 만들고 저장했어야 합니다.

.단계
. Data Infrastructure Insights 도구 모음에서 *관리 > 주석 규칙*을 클릭합니다.
. *추가*를 클릭하세요. 규칙 추가 대화 상자가 표시됩니다.
+
.. 이름 상자에 규칙을 설명하는 고유한 이름을 입력합니다: *"RootAggrExclude"*
.. 쿼리를 클릭하고 Insight가 주석 규칙을 적용하는 데 사용해야 하는 쿼리를 선택합니다: *"Aggregate0"*
.. 주석을 클릭하고 "루트 집계 제외"를 선택하세요.
.. *값*을 클릭하고 *참*을 입력하세요.



