---
sidebar: sidebar 
permalink: task_dc_ibm_powervm.html 
keywords: IBM, powerVM, 
summary: IBM PowerVM 데이터 수집기 구성. 
---
= IBM PowerVM 데이터 수집기 구성
:hardbreaks:
:allow-uri-read: 


[role="lead"]
IBM PowerVM(SSH) 데이터 수집기는 하드웨어 관리 콘솔(HMC)에서 관리하는 IBM POWER 하드웨어 인스턴스에서 실행되는 가상 파티션에 대한 정보를 수집하는 데 사용됩니다.



== 술어

Data Infrastructure Insights IBM POWER 하드웨어 인스턴스에서 실행되는 가상 파티션에서 인벤토리 정보를 수집합니다.  인수한 각 자산 유형에 대해 해당 자산에 사용되는 가장 일반적인 용어가 표시됩니다.  이 데이터 수집기를 보거나 문제를 해결할 때 다음 용어를 염두에 두십시오.

[cols="2*"]
|===
| 공급업체/모델 용어 | Data Infrastructure Insights 용어 


| hdisk | 가상 디스크 


| 관리 시스템 | 주인 


| LPAR, VIO 서버 | 가상 머신 


| 볼륨 그룹 | 데이터 저장소 


| 물리적 볼륨 | LUN 
|===
참고: 이는 일반적인 용어 매핑일 뿐이며 이 데이터 수집기의 모든 사례를 나타내지 않을 수 있습니다.



== 요구 사항

이 데이터 수집기를 구성하고 사용하려면 다음 요구 사항을 충족해야 합니다.

* 하드웨어 관리 콘솔(HMC)의 IP 주소
* SSH를 통해 하드웨어 관리 콘솔(HMC)에 액세스할 수 있는 사용자 이름과 비밀번호
* 포트 요구 사항 SSH-22
* 모든 관리 시스템 및 논리 파티션 보안 도메인에 대한 보기 권한
+
사용자는 HMC 구성에 대한 보기 권한과 HMC 콘솔 보안 그룹에 대한 VPD 정보를 수집할 수 있는 권한도 있어야 합니다.  사용자는 논리 파티션 보안 그룹에서 Virtual IO Server 명령 액세스도 허용되어야 합니다.  운영자 역할부터 시작하여 모든 역할을 제거하는 것이 가장 좋은 방법입니다.  HMC의 읽기 전용 사용자는 AIX 호스트에서 프록시 명령을 실행할 권한이 없습니다.

* IBM의 모범 사례는 두 개 이상의 HMC를 통해 장치를 모니터링하는 것입니다.  이로 인해 OnCommand Insight 중복된 장치를 보고할 수 있으므로 이 데이터 수집기의 고급 구성에서 "제외 장치" 목록에 중복된 장치를 추가하는 것이 좋습니다.




== 구성

[cols="2*"]
|===
| 필드 | 설명 


| 하드웨어 관리 콘솔(HMC) IP 주소 | PowerVM 하드웨어 관리 콘솔의 IP 주소 또는 정규화된 도메인 이름 


| HMC 사용자 | 하드웨어 관리 콘솔의 사용자 이름 


| 비밀번호 | 하드웨어 관리 콘솔에 사용되는 비밀번호 
|===


== 고급 구성

[cols="2*"]
|===
| 필드 | 설명 


| 재고 폴링 간격(분) | 재고 조사 간격. 기본값은 20분입니다. 


| SSH 포트 | PowerVM에 대한 SSH에 사용되는 포트 


| 비밀번호 | 하드웨어 관리 콘솔에 사용되는 비밀번호 


| 재시도 횟수 | 재고 재시도 횟수 


| 장치 제외 | 제외할 장치 ID 또는 표시 이름의 쉼표로 구분된 목록 
|===


== 문제 해결

이 데이터 수집기에 대한 추가 정보는 다음에서 찾을 수 있습니다.link:concept_requesting_support.html["지원하다"] 페이지 또는link:reference_data_collector_support_matrix.html["데이터 수집기 지원 매트릭스"] .
