---
sidebar: sidebar 
permalink: task_dc_aws_s3.html 
keywords: data collector, S3, Storage 
summary: 스토리지 데이터 수집기로 AWS S3 구성. 
---
= AWS S3를 스토리지 데이터 수집기로 구성
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Data Infrastructure Insights는 AWS S3를 스토리지 데이터 수집기로 사용하여 AWS S3 인스턴스의 인벤토리 및 성능 데이터를 가져옵니다.



== 요구 사항

AWS S3에서 스토리지 디바이스로 데이터를 수집하려면 다음 정보가 있어야 합니다.

* 다음 중 하나가 있어야 합니다.
+
** IAM 역할 인증을 사용하는 경우 AWS 클라우드 계정에 대한 * IAM Role * 입니다. IAM Role은 AWS 인스턴스에 획득 장치가 설치된 경우에만 적용됩니다.
** IAM 액세스 키 인증을 사용하는 경우 AWS 클라우드 계정의 * IAM 액세스 키 * ID 및 비밀 액세스 키


* "조직 목록" 권한이 있어야 합니다
* 포트 443 HTTPS
* AWS S3 인스턴스를 가상 머신 또는 (자연스럽게) 호스트로 보고할 수 있습니다. EBS 볼륨은 VM에서 사용하는 가상 디스크와 가상 디스크의 용량을 제공하는 데이터 저장소로 보고될 수 있습니다.


액세스 키는 액세스 키 ID(예: AKIAIOSFODN7EXAMPLE)와 비밀 액세스 키(예: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY)로 구성됩니다. AWS SDK, REST 또는 쿼리 API 작업을 사용하는 경우 액세스 키를 사용하여 AWS에 대해 수행하는 프로그래밍 방식 요청에 서명할 수 있습니다. 이러한 키는 아마존에서 귀하의 계약과 함께 제공됩니다.



== 구성

아래 표에 따라 데이터 수집기 필드에 데이터를 입력합니다.

[cols="2*"]
|===
| 필드에 입력합니다 | 설명 


| AWS 지역 | AWS 지역을 선택하십시오 


| IAM 역할입니다 | AWS의 AU에서 획득한 경우에만 사용합니다. 에 대한 자세한 내용은 아래를 <<iam-role,IAM 역할입니다>>참조하십시오. 


| AWS IAM 액세스 키 ID | AWS IAM 액세스 키 ID를 입력합니다. IAM Role을 사용하지 않는 경우 필수입니다. 


| AWS IAM 비밀 액세스 키 | AWS IAM 비밀 액세스 키를 입력합니다. IAM Role을 사용하지 않는 경우 필수입니다. 


| API 요청에 대한 AWS 청구 내용을 알고 있습니다 | Data Infrastructure Insights 폴링을 통해 생성된 API 요청에 대해 AWS가 청구한다는 이해도를 확인하려면 이 점검 목록을 확인하십시오. 
|===


== 고급 구성

[cols="2*"]
|===
| 필드에 입력합니다 | 설명 


| 교차 계정 역할 | 서로 다른 AWS 계정의 리소스에 액세스하는 역할입니다. 


| 재고 폴링 간격(분) | 기본값은 60입니다 


| 태그별로 VM 필터링에 적용하려면 '제외' 또는 '포함'을 선택합니다 | 데이터를 수집할 때 태그별로 VM을 포함할지 제외할지 여부를 지정합니다. '포함'을 선택한 경우 태그 키 필드를 비워 둘 수 없습니다. 


| 성능 폴링 간격(초) | 기본값은 1800입니다 
|===


== IAM 액세스 키

액세스 키는 IAM 사용자 또는 AWS 계정 루트 사용자에 대한 장기 자격 증명입니다. 액세스 키는 AWS CLI 또는 AWS API(직접 또는 AWS SDK 사용)에 프로그래밍 방식으로 요청을 서명하는 데 사용됩니다.

액세스 키는 액세스 키 ID와 비밀 액세스 키의 두 부분으로 구성됩니다. IAM Role_authentication과 달리 _IAM Access Key_authentication을 사용할 때는 요청 인증을 위해 액세스 키 ID와 비밀 액세스 키를 함께 사용해야 합니다. 자세한 내용은 의 아마존 설명서를 참조하십시오link:https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_access-keys.html["액세스 키"].



== IAM 역할입니다

IAM Access Key 인증과 달리 _IAM Role_authentication을 사용할 때는 생성하거나 지정하는 역할에 리소스에 액세스하는 데 필요한 적절한 권한이 있는지 확인해야 합니다.

예를 들어, 이름이 _InstanceS3ReadOnly_인 IAM 역할을 생성하는 경우 이 IAM 역할에 대한 모든 S3 읽기 전용 목록 액세스 권한을 부여하도록 정책을 설정해야 합니다. 또한 이 역할이 계정 간에 역할을 수행할 수 있도록 STS(보안 토큰 서비스) 액세스를 부여해야 합니다.

IAM 역할을 생성한 후 새 S3 인스턴스 또는 기존 S3 인스턴스를 생성할 때 연결할 수 있습니다.

IAM role_InstanceS3ReadOnly_를 S3 인스턴스에 연결하면 IAM 역할 이름으로 인스턴스 메타데이터를 통해 임시 자격 증명을 검색하고 이 S3 인스턴스에서 실행되는 모든 응용 프로그램에서 이 자격 증명을 사용하여 AWS 리소스에 액세스할 수 있습니다.

자세한 내용은 의 아마존 문서를 참조하십시오link:https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles.html["IAM 역할"].

참고: IAM 역할은 획득 장치가 AWS 인스턴스에서 실행 중인 경우에만 사용할 수 있습니다.



== Amazon 태그를 Data Infrastructure Insights 주석에 매핑

AWS S3를 스토리지 데이터 수집기로 사용하려면 Data Infrastructure Insights 주석을 S3에 구성된 태그로 채울 수 있는 옵션이 포함되어 있습니다. 주석 이름은 AWS 태그와 정확히 일치해야 합니다. Data Infrastructure Insights는 항상 같은 이름의 텍스트 유형 주석을 채우고 다른 유형(숫자, 부울 등)의 주석을 채우려는 "최선의 시도"를 합니다. 주석이 다른 유형이고 데이터 수집기가 주석을 채우지 못할 경우 주석을 제거하고 텍스트 유형으로 다시 생성해야 할 수 있습니다.

AWS는 대소문자를 구분하지만 Data Infrastructure Insights는 대소문자를 구분하지 않습니다. 따라서 Data Infrastructure Insights에서 "owner"라는 주석을 작성하고 S3에서 "owner", "owner" 및 "owner"라는 태그를 생성하면 모든 S3 버전의 "owner"가 Cloud Insight의 "소유자" 주석에 매핑됩니다.



== AWS 하위 계정에서 수집 중

Data Infrastructure Insights는 단일 AWS 데이터 수집기 내에서 AWS용 하위 계정 수집을 지원합니다. 이 컬렉션에 대한 구성은 AWS 환경에서 수행됩니다.

* 기본 계정 ID가 하위 계정에서 S3 세부 정보에 액세스할 수 있도록 각 하위 계정에 AWS 역할을 구성해야 합니다.
* 각 하위 계정에는 동일한 문자열로 구성된 역할 이름이 있어야 합니다.
* Data Infrastructure Insights AWS Data Collector * 고급 구성 * 섹션의 * 교차 계정 역할 * 필드에 이 역할 이름 문자열을 입력합니다.
* Collector가 설치된 계정에는 _delegate 액세스 권한이 있는 administrator_Privileges가 있어야 합니다. link:https://docs.aws.amazon.com/accounts/latest/reference/using-orgs-delegated-admin.html["AWS 설명서"]자세한 내용은 를 참조하십시오.


모범 사례: AWS Predefined_AmazonS3ReadOnlyAccess_policy를 S3 메인 계정에 할당하는 것이 좋습니다. 또한 데이터 소스에서 구성된 사용자는 AWS를 쿼리하기 위해 미리 정의된 _AWSOrganizationReadOnlyAccess_policy 이상을 할당해야 합니다.

Data Infrastructure Insights가 AWS 하위 계정에서 수집할 수 있도록 환경을 구성하는 방법은 다음을 참조하십시오.

link:https://docs.aws.amazon.com/IAM/latest/UserGuide/tutorial_cross-account-with-roles.html["자습서: IAM 역할을 사용하여 AWS 계정 전체에서 대리인 액세스"]

link:https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_common-scenarios_aws-accounts.html["AWS 설정: 사용자가 소유한 다른 AWS 계정에서 IAM 사용자에 대한 액세스 제공"]

link:https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_create_for-user.html["IAM 사용자에 대한 권한을 위임하기 위한 역할 생성"]



== 문제 해결

이 데이터 수집기에 대한 추가 정보는 페이지 또는 에서 찾을 link:concept_requesting_support.html["지원"]link:reference_data_collector_support_matrix.html["Data Collector 지원 매트릭스"]수 있습니다.
