---
sidebar: sidebar 
permalink: task_dc_nutanix_ahv.html 
keywords: data collector, Nutanix, AHV Series 
summary: Nutanix AHV 데이터 수집기 구성. 
---
= Nutanix AHV 데이터 수집기
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Nutanix AHV 컬렉터는 Prism Central v4 REST API(클러스터 관리 및 가상 머신 관리 네임스페이스)를 사용하여 Nutanix Prism Central에서 Nutanix Acropolis Hypervisor(AHV) 인벤토리 및 가상화 성능 데이터를 수집합니다. 수집된 데이터는 가상화 OData 모델(VirtualizationRoot 및 관련 엔티티: 호스트, 가상 머신, 데이터 저장소, 가상 디스크 및 관계) 형식으로 보고됩니다.



[[terminology]]
== 술어

[cols="50,50"]
|===
| 공급업체/모델 용어 | Data Infrastructure Insights 용어 


| AHV 노드(호스트) | 주인 


| Prism Central 클러스터 | 하이퍼바이저(가상 서버) 


| Acropolis VM | 가상 머신 


| 스토리지 컨테이너 | 데이터 저장소 


| ADSF 볼륨 그룹 | LUN 


| VM 디스크 | 가상 디스크 
|===
참고: 이는 일반적인 용어 매핑일 뿐이며 이 데이터 수집기의 모든 사례를 나타내지 않을 수 있습니다.



[[requirements]]
== 요구 사항

* Prism Central IP 주소 또는 정규화된 도메인 이름
* Prism Central 로컬 또는 LDAP 사용자 이름과 비밀번호 (인벤토리 및 성능 분석에는 읽기 전용 계정이면 충분하며, 관리자 권한은 필요하지 않습니다)
* 포트 요구 사항: HTTPS 9440
* Prism Central 버전 pc.2023.x 이상(v3 API), pc.7.x 이상 권장(v4 API)
* 성능 지표를 사용하려면 Prism Central API v4.0.b1 이상(pc.7.3 이상) 버전이 필요합니다. 이전 버전에서는 인벤토리 데이터는 수집되지만 성능 데이터는 보고되지 않습니다.




[[configuration]]
== 구성

[cols="50,50"]
|===
| 필드 | 설명 


| Prism Central IP 주소 | Prism Central 인스턴스의 IP 주소 또는 FQDN 


| 사용자 이름 | Prism Central 사용자 이름 


| 비밀번호 | Prism Central 암호 
|===


[[advanced-configuration]]
== 고급 구성

[cols="50,50"]
|===
| 필드 | 설명 


| TCP 포트 | Prism Central에 연결하는 데 사용되는 TCP 포트입니다. 기본값은 9440입니다. 


| 재고 폴링 간격(분) | 재고 조사 간격. 기본값은 60분입니다. 


| 성능 폴링 간격(초) | 성과 여론조사 간격. 기본값은 300초입니다. 


| HTTP 타임아웃(초) | HTTP 요청 시간 초과. 기본값은 60초입니다. 


| HTTP 재시도 횟수 | 일시적인 오류 발생 시 HTTP 재시도 횟수입니다. 기본값은 3입니다. 
|===


[[troubleshooting]]
== 문제 해결

이 데이터 수집기에 대한 추가 정보는 다음에서 찾을 수 있습니다.link:concept_requesting_support.html["지원하다"] 페이지 또는link:reference_data_collector_support_matrix.html["데이터 수집기 지원 매트릭스"] .
