---
sidebar: sidebar 
permalink: task_dc_na_cdot.html 
keywords: data collector, ontap, ontap, CDOT 
summary: ONTAP 데이터 수집기 
---
= NetApp ONTAP 데이터 관리 소프트웨어 데이터 수집기
:hardbreaks:
:allow-uri-read: 


[role="lead"]
이 데이터 수집기는 ONTAP 계정의 읽기 전용 API 호출을 사용하여 ONTAP 실행하는 스토리지 시스템에서 인벤토리 및 성능 데이터를 수집합니다.  이 데이터 수집기는 또한 지원을 가속화하기 위해 클러스터 애플리케이션 레지스트리에 레코드를 생성합니다.



== 술어

Data Infrastructure Insights ONTAP 데이터 수집기에서 인벤토리 및 성능 데이터를 수집합니다.  인수한 각 자산 유형에 대해 해당 자산에 사용되는 가장 일반적인 용어가 표시됩니다.  이 데이터 수집기를 보거나 문제를 해결할 때 다음 용어를 염두에 두십시오.

[cols="2*"]
|===
| 공급업체/모델 용어 | Data Infrastructure Insights 용어 


| 디스크 | 디스크 


| 레이드 그룹 | 디스크 그룹 


| 무리 | 스토리지 


| 마디 | 저장 노드 


| 골재 | 스토리지 풀 


| LUN | 용량 


| 용량 | 내부 볼륨 
|===


== ONTAP 데이터 관리 용어

다음 용어는 ONTAP 데이터 관리 스토리지 자산 랜딩 페이지에서 찾을 수 있는 객체나 참조에 적용됩니다.  이러한 용어의 대부분은 다른 데이터 수집자에게도 적용됩니다.



=== 스토리지

* 모델 – 이 클러스터 내의 고유하고 개별적인 노드 모델 이름을 쉼표로 구분하여 나열한 목록입니다.  클러스터의 모든 노드가 동일한 모델 유형인 경우 모델 이름은 하나만 나타납니다.
* 공급업체 – 새 데이터 소스를 구성하는 경우와 동일한 공급업체 이름입니다.
* 일련 번호 – 배열 일련 번호.  ONTAP Data Management와 같은 클러스터 아키텍처 스토리지 시스템에서 이 일련 번호는 개별 "스토리지 노드" 일련 번호보다 덜 유용할 수 있습니다.
* IP – 일반적으로 데이터 소스에 구성된 IP 또는 호스트 이름이 됩니다.
* 마이크로코드 버전 - 펌웨어.
* 원시 용량 – 역할에 관계없이 시스템의 모든 물리적 디스크의 2진 합산입니다.
* 대기 시간 - 호스트가 읽기와 쓰기 모두에서 작업 부하를 경험하는 것을 표현한 것입니다.  이상적으로는 Data Infrastructure Insights 이 가치를 직접 소싱하는 것이 좋지만, 그렇지 않은 경우가 많습니다.  이를 제공하는 배열 대신, Data Infrastructure Insights 일반적으로 개별 내부 볼륨의 통계에서 파생된 IOPS 가중치 계산을 수행합니다.
* 처리량 – 내부 볼륨에서 집계됨.  관리 – 여기에는 장치의 관리 인터페이스에 대한 하이퍼링크가 포함될 수 있습니다.  인벤토리 보고의 일부로 Data Infrastructure Insights 데이터 소스에 의해 프로그래밍 방식으로 생성되었습니다.




=== 스토리지 풀

* 저장소 – 이 풀이 어떤 저장소 배열에 있는지.  필수적인.
* 유형 – 가능성의 열거된 목록에서 나온 설명적 값입니다.  가장 일반적으로는 "집계" 또는 "RAID 그룹"입니다.
* 노드 - 이 스토리지 어레이의 아키텍처가 풀이 특정 스토리지 노드에 속하도록 되어 있는 경우, 해당 이름은 자체 랜딩 페이지로 연결되는 하이퍼링크로 여기에 표시됩니다.
* 플래시 풀 사용 – 예/아니요 값 – 이 SATA/SAS 기반 풀에 캐싱 가속에 사용되는 SSD가 있습니까?
* 중복성 – RAID 수준 또는 보호 체계.  RAID_DP는 듀얼 패리티이고, RAID_TP는 트리플 패리티입니다.
* 용량 – 여기의 값은 논리적으로 사용된 용량, 사용 가능한 용량, 논리적 총 용량, 그리고 이들에 사용된 백분율입니다.
* 과도하게 할당된 용량 – 효율성 기술을 사용하여 스토리지 풀의 논리적 용량보다 큰 볼륨 또는 내부 볼륨 용량의 총합을 할당한 경우 여기의 백분율 값은 0%보다 커집니다.
* 스냅샷 – 스토리지 풀 아키텍처가 용량의 일부를 스냅샷 전용 세그먼트 영역에 할당하는 경우 사용된 스냅샷 용량과 총 용량입니다.  MetroCluster 구성의 ONTAP 에서는 이런 현상이 나타날 가능성이 높지만, 다른 ONTAP 구성에서는 그렇지 않습니다.
* 활용도 – 이 스토리지 풀에 용량을 제공하는 모든 디스크 중 가장 높은 디스크 사용률을 나타내는 백분율 값입니다.  디스크 사용률은 반드시 어레이 성능과 강한 상관관계가 있는 것은 아닙니다. 호스트 기반 워크로드가 없는 경우 디스크 재구축, 중복 제거 활동 등으로 인해 사용률이 높을 수 있습니다.  또한 많은 어레이의 복제 구현은 내부 볼륨이나 볼륨 작업 부하로 표시되지 않으면서도 디스크 활용도를 높일 수 있습니다.
* IOPS – 이 스토리지 풀에 용량을 제공하는 모든 디스크의 합계 IOPS입니다.  처리량 – 이 스토리지 풀에 용량을 제공하는 모든 디스크의 총 처리량입니다.




=== 저장 노드

* 저장소 – 이 노드가 속한 저장소 배열입니다.  필수적인.
* HA 파트너 – 노드가 다른 노드로만 장애 조치되는 플랫폼에서 일반적으로 여기에 표시됩니다.
* 상태 - 노드의 상태.  데이터 소스에서 인벤토리를 수행할 수 있을 만큼 배열이 건강한 경우에만 사용할 수 있습니다.
* 모델 – 노드의 모델 이름.
* 버전 – 장치의 버전 이름.
* 일련 번호 – 노드 일련 번호.
* 메모리 – 가능하다면 2진수 메모리를 사용합니다.
* 활용도 – ONTAP 에서 이는 독점 알고리즘의 컨트롤러 스트레스 지수입니다.  모든 성능 폴링에서는 WAFL 디스크 경합이나 평균 CPU 사용률 중 더 높은 값을 0~100% 사이의 숫자로 보고합니다.  지속적으로 50% 이상의 값이 관찰되면 크기가 작음을 나타냅니다. 즉, 컨트롤러/노드가 충분히 크지 않거나 회전 디스크가 쓰기 작업 부하를 흡수하기에 충분하지 않을 수 있습니다.
* IOPS – 노드 개체에 대한 ONTAP ZAPI 호출에서 직접 파생됩니다.
* 지연 시간 – 노드 개체에 대한 ONTAP ZAPI 호출에서 직접 파생됩니다.
* 처리량 – 노드 개체에 대한 ONTAP ZAPI 호출에서 직접 파생됩니다.
* 프로세서 - CPU 수.




== 요구 사항

이 데이터 수집기를 구성하고 사용하기 위한 요구 사항은 다음과 같습니다.

* 읽기 전용 API 호출을 위해 구성된 관리자 계정에 액세스할 수 있어야 합니다.
* 계정 세부 정보에는 사용자 이름과 비밀번호가 포함됩니다.
* 포트 요구 사항: 80 또는 443
* 계정 권한:
+
** 기본 Vserver에 대한 ontapi 애플리케이션의 읽기 전용 역할 이름
** 추가적인 선택적 쓰기 권한이 필요할 수 있습니다.  아래의 권한에 대한 참고 사항을 참조하세요.


* ONTAP 라이센스 요구 사항:
+
** 파이버 채널 검색에 필요한 FCP 라이센스 및 매핑/마스킹 볼륨






=== ONTAP 스위치 메트릭 수집을 위한 권한 요구 사항

Data Infrastructure Insights 수집기의 옵션으로 ONTAP 클러스터 스위치 데이터를 수집하는 기능을 갖추고 있습니다.<<advanced-configuration,고급 구성>> 설정.  Data Infrastructure Insights 수집기에서 이를 활성화하는 것 외에도 ONTAP 시스템 자체를 구성하여 다음을 제공해야 합니다.link:https://docs.netapp.com/us-en/ontap-cli-98/system-switch-ethernet-create.html["스위치 정보"] , 그리고 올바른 것을 보장합니다<<a-note-about-permissions,권한>> 스위치 데이터가 Data Infrastructure Insights 로 전송될 수 있도록 설정되었습니다.



== 구성

[cols="2*"]
|===
| 필드 | 설명 


| NetApp 관리 IP | NetApp 클러스터의 IP 주소 또는 정규화된 도메인 이름 


| 사용자 이름 | NetApp 클러스터의 사용자 이름 


| 비밀번호 | NetApp 클러스터의 비밀번호 
|===


== 고급 구성

[cols="2*"]
|===
| 필드 | 설명 


| 연결 유형 | HTTP(기본 포트 80) 또는 HTTPS(기본 포트 443)를 선택하세요.  기본값은 HTTPS입니다 


| 통신 포트 재정의 | 기본 포트를 사용하지 않으려면 다른 포트를 지정하세요. 


| 재고 폴링 간격(분) | 기본값은 60분입니다. 


| HTTPS용 TLS의 경우 | HTTPS를 사용할 때 TLS만 프로토콜로 허용 


| 자동으로 넷그룹 조회 | 내보내기 정책 규칙에 대한 자동 넷그룹 조회를 활성화합니다. 


| 넷그룹 확장 | 넷그룹 확장 전략.  _파일_ 또는 _셸_을 선택하세요.  기본값은 _shell_입니다. 


| HTTP 읽기 시간 초과(초) | 기본값은 30입니다 


| UTF-8로 응답 강제 적용 | CLI의 응답을 UTF-8로 해석하도록 데이터 수집기 코드를 강제합니다. 


| 성능 폴링 간격(초) | 기본값은 900초입니다. 


| 고급 카운터 데이터 수집 | ONTAP 통합을 활성화합니다.  여론조사에 ONTAP 고급 카운터 데이터를 포함하려면 이 옵션을 선택하세요.  목록에서 원하는 카운터를 선택하세요. 


| 클러스터 스위치 메트릭 | Data Infrastructure Insights 클러스터 스위치 데이터를 수집하도록 허용합니다.  Data Infrastructure Insights 측에서 이를 활성화하는 것 외에도 ONTAP 시스템을 구성하여 다음을 제공해야 합니다.link:https://docs.netapp.com/us-en/ontap-cli-98/system-switch-ethernet-create.html["스위치 정보"] , 그리고 올바른 것을 보장합니다<<a-note-about-permissions,권한>> 스위치 데이터가 Data Infrastructure Insights 로 전송될 수 있도록 설정되었습니다.  아래의 "권한에 대한 참고 사항"을 참조하세요. 
|===


== ONTAP 전력 측정

여러 ONTAP 모델은 모니터링이나 알림에 사용할 수 있는 Data Infrastructure Insights 에 대한 전력 측정 항목을 제공합니다.


NOTE: 이 목록은 포괄적이지 않으며 변경될 수 있습니다.  일반적으로 모델이 목록에 있는 모델과 같은 계열에 속하면 지원은 동일해야 하지만 동일하다는 보장은 없습니다.  모델이 전력 측정 항목을 지원하는지 확실하지 않으면 ONTAP 지원팀에 문의하세요.

지원 모델:

A200 A220 A250 A300 A320 A400 A700 A700s A800 A900 C190 FAS2240-4 FAS2552 FAS2650 FAS2720 FAS2750 FAS8200 FAS8300 FAS8700 FAS9000

지원되지 않는 모델:

FAS2620 FAS3250 FAS3270 FAS500f FAS6280 FAS/ AFF 8020 FAS/ AFF 8040 FAS/ AFF 8060 FAS/ AFF 8080



== 권한에 대한 참고 사항

여러 Data Infrastructure Insights ONTAP 대시보드가 ​​고급 ONTAP 카운터에 의존하므로 데이터 수집기 ​​고급 구성 섹션에서 *고급 카운터 데이터 수집*을 활성화해야 합니다.

또한 ONTAP API에 대한 쓰기 권한이 활성화되어 있는지 확인해야 합니다.  일반적으로 필요한 권한이 있는 클러스터 수준의 계정이 필요합니다.

클러스터 수준에서 Data Infrastructure Insights 에 대한 로컬 계정을 만들려면 클러스터 관리 관리자 사용자 이름/비밀번호로 ONTAP 에 로그인하고 ONTAP 서버에서 다음 명령을 실행합니다.

. 시작하기 전에 _관리자_ 계정으로 ONTAP 에 로그인하고 _진단 수준 명령_을 활성화해야 합니다.
. 다음 명령을 사용하여 읽기 전용 역할을 만듭니다.
+
....
security login role create -role ci_readonly -cmddirname DEFAULT -access readonly
security login role create -role ci_readonly -cmddirname security -access readonly
security login role create -role ci_readonly -access all -cmddirname {cluster application-record create}
....
. 다음 명령을 사용하여 읽기 전용 사용자를 만듭니다.  create 명령을 실행하면 해당 사용자의 비밀번호를 입력하라는 메시지가 표시됩니다.
+
 security login create -username ci_user -application ontapi -authentication-method password -role ci_readonly


AD/LDAP 계정을 사용하는 경우 명령은 다음과 같아야 합니다.

 security login create -user-or-group-name DOMAIN\aduser/adgroup -application ontapi -authentication-method domain -role ci_readonly
클러스터 스위치 데이터를 수집하는 경우:

....
security login rest-role create -role ci_readonly_rest -api /api/network/ethernet -access readonly
security login create -user-or-group-name ci_user -application http -authmethod password -role ci_readonly_rest
....
결과적으로 나타나는 역할과 사용자 로그인은 다음과 같습니다.  실제 출력은 다를 수 있습니다.

....
Role Command/ Access
Vserver Name Directory Query Level
---------- ------------- --------- ------------------ --------
cluster1 ci_readonly DEFAULT read only
cluster1 ci_readonly security readonly
....
....
cluster1:security login> show
Vserver: cluster1
Authentication Acct
UserName    Application   Method      Role Name      Locked
---------   -------      ----------- -------------- --------
ci_user     ontapi      password    ci_readonly   no
....

NOTE: ONTAP 액세스 제어가 올바르게 설정되지 않으면 Data Infrastructure Insights REST 호출이 실패하여 장치의 데이터에 차이가 생길 수 있습니다.  예를 들어, Data Infrastructure Insights 수집기에서 해당 기능을 활성화했지만 ONTAP 에서 권한을 구성하지 않은 경우 획득이 실패합니다.  또한, 역할이 이전에 ONTAP 에 정의되어 있고 REST API 기능을 추가하는 경우 _http_가 역할에 추가되었는지 확인하세요.



== 문제 해결

이 데이터 수집기에 문제가 발생하면 시도해 볼 수 있는 몇 가지 사항은 다음과 같습니다.



=== 목록

[cols="2*"]
|===
| 문제: | 다음을 시도해 보세요: 


| 401 HTTP 응답 또는 13003 ZAPI 오류 코드를 수신하고 ZAPI가 "권한이 부족합니다" 또는 "이 명령에 대한 권한이 없습니다"를 반환합니다. | 사용자 이름과 비밀번호, 사용자 권한/허가를 확인하세요. 


| 클러스터 버전은 < 8.1입니다. | 클러스터에서 지원하는 최소 버전은 8.1입니다.  지원되는 최소 버전으로 업그레이드하세요. 


| ZAPI가 "클러스터 역할이 cluster_mgmt LIF가 아닙니다"를 반환합니다. | AU는 클러스터 관리 IP와 통신해야 합니다.  IP를 확인하고 필요한 경우 다른 IP로 변경하세요. 


| 오류: "7 모드 필터가 지원되지 않습니다" | 이 데이터 수집기를 사용하여 7모드 필터를 발견하면 이런 일이 발생할 수 있습니다.  대신 IP를 cdot 클러스터를 가리키도록 변경하세요. 


| 재시도 후 ZAPI 명령이 실패합니다. | AU는 클러스터와 통신 문제가 있습니다.  네트워크, 포트 번호, IP 주소를 확인하세요.  사용자는 AU 머신의 명령줄에서 명령을 실행해보아야 합니다. 


| AU가 HTTP를 통해 ZAPI에 연결하지 못했습니다. | ZAPI 포트가 일반 텍스트를 허용하는지 확인하세요.  AU가 SSL 소켓에 일반 텍스트를 보내려고 하면 통신이 실패합니다. 


| SSLException으로 인해 통신이 실패합니다. | AU는 파일러의 일반 텍스트 포트로 SSL을 보내려고 시도하고 있습니다.  ZAPI 포트가 SSL을 허용하는지 확인하거나 다른 포트를 사용하세요. 


| 추가 연결 오류: ZAPI 응답에 오류 코드 13001, "데이터베이스가 열려 있지 않습니다"가 있습니다. ZAPI 오류 코드는 60이고 응답에는 "API가 제 시간에 완료되지 않았습니다"가 포함됩니다. ZAPI 응답에는 "initialize_session()이 NULL 환경을 반환했습니다"가 포함됩니다. ZAPI 오류 코드는 14007이고 응답에는 "노드가 정상이 아닙니다"가 포함됩니다. | 네트워크, 포트 번호, IP 주소를 확인하세요.  사용자는 AU 머신의 명령줄에서 명령을 실행해보아야 합니다. 
|===


=== 성능

[cols="2*"]
|===
| 문제: | 다음을 시도해 보세요: 


| "ZAPI에서 성능 수집에 실패했습니다" 오류 | 이는 일반적으로 perf stat이 실행되지 않기 때문에 발생합니다.  각 노드에서 다음 명령을 시도하세요. > _system node systemshell -node * -command “spmctl -h cmd –stop; spmctl -h cmd –exec”_ 
|===
추가 정보는 다음에서 찾을 수 있습니다.link:concept_requesting_support.html["지원하다"] 페이지 또는link:reference_data_collector_support_matrix.html["데이터 수집기 지원 매트릭스"] .
