---
sidebar: sidebar 
permalink: task_defining_annotations.html 
keywords: annotations, monitor, notes, tags 
summary: 주석을 사용하여 데이터를 추적합니다. 
---
= 주석 정의
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
기업 요구 사항에 맞게 데이터를 추적하기 위해 Data Infrastructure Insights 사용자 정의할 때 주석이라고 하는 특수 메모를 정의하고 자산에 할당할 수 있습니다.

자산 수명 종료, 데이터 센터, 건물 위치, 스토리지 계층 또는 볼륨 서비스 수준과 같은 정보를 사용하여 자산에 주석을 할당할 수 있습니다.

주석을 사용하여 환경을 모니터링하는 데는 다음과 같은 고급 작업이 포함됩니다.

* 모든 주석 유형에 대한 정의를 만들거나 편집합니다.
* 자산 페이지를 표시하고 각 자산을 하나 이상의 주석과 연결합니다.
+
예를 들어, 자산을 임대하고 있고 임대 기간이 2개월 이내에 만료되는 경우 자산에 수명 종료 주석을 적용할 수 있습니다.  이렇게 하면 다른 사람이 해당 자산을 장기간 사용하는 것을 방지할 수 있습니다.

* 동일한 유형의 여러 자산에 자동으로 주석을 적용하는 규칙을 만듭니다.
* 주석으로 자산을 필터링합니다.




== 기본 주석 유형

Data Infrastructure Insights 몇 가지 기본 주석 유형을 제공합니다.  이러한 주석은 데이터를 필터링하거나 그룹화하는 데 사용할 수 있습니다.

다음과 같은 기본 주석 유형과 자산을 연결할 수 있습니다.

* 생일, 종료 또는 수명 종료와 같은 자산 수명 주기
* 데이터 센터, 건물 또는 층과 같은 장치에 대한 위치 정보
* 품질(계층), 연결된 장치(스위치 수준) 또는 서비스 수준 등의 자산 분류
* 상태, 예: 핫(활용도 높음)


다음 표에는 Data Infrastructure Insights 에서 제공하는 주석 유형이 나열되어 있습니다.

[cols="30,53, 16"]
|===


| 주석 유형 | 설명 | 유형 


| 별명 | 리소스에 대한 사용자 친화적인 이름 | 텍스트 


| 컴퓨팅 리소스 그룹 | 호스트 및 VM 파일 시스템 데이터 수집기에서 사용하는 그룹 할당 | 목록 


| 데이터 센터 | 물리적 위치 | 목록 


| 더운 | 정기적으로 많이 사용되거나 용량 한계에 도달한 장치 | 부울 


| 참고 | 리소스와 관련된 주석 | 시험 


| 서비스 수준 | 리소스에 할당할 수 있는 지원되는 서비스 수준 집합입니다.  내부 볼륨, Qtree 및 볼륨에 대한 정렬된 옵션 목록을 제공합니다.  다양한 수준에 대한 성능 정책을 설정하려면 서비스 수준을 편집합니다. | 목록 


| 일몰 | 해당 장치에 더 이상 새로운 할당을 할 수 없게 되는 임계값을 설정합니다.  계획된 마이그레이션 및 기타 보류 중인 네트워크 변경에 유용합니다. | 날짜 


| 스위치 레벨 | 스위치에 대한 카테고리를 설정하기 위한 미리 정의된 옵션입니다.  일반적으로 이러한 지정은 장치의 수명 동안 유지되지만 편집할 수도 있습니다.  스위치에만 사용 가능합니다. | 목록 


| 층 | 사용자 환경 내에서 다양한 서비스 수준을 정의하는 데 사용할 수 있습니다.  티어는 필요한 속도(예: 골드 또는 실버)와 같은 레벨 유형을 정의할 수 있습니다.  이 기능은 내부 볼륨, Q트리, 스토리지 어레이, 스토리지 풀 및 볼륨에서만 사용할 수 있습니다. | 목록 


| 위반 심각도 | 위반 사항(예: 호스트 포트 누락 또는 중복성 누락)의 순위(예: 주요)를 가장 높은 중요도에서 가장 낮은 중요도 순으로 표시합니다. | 목록 
|===

NOTE: 별칭, 데이터 센터, 핫, 서비스 수준, 일몰, 스위치 수준, 계층 및 위반 심각도는 시스템 수준 주석으로, 삭제하거나 이름을 바꿀 수 없습니다. 할당된 값만 변경할 수 있습니다.



== 사용자 정의 주석 만들기

주석을 사용하면 비즈니스 요구 사항에 맞는 맞춤형 비즈니스별 데이터를 자산에 추가할 수 있습니다.  Data Infrastructure Insights 기본 주석 세트를 제공하지만 다른 방법으로 데이터를 보고 싶을 수도 있습니다.  사용자 정의 주석의 데이터는 저장소 제조업체, 볼륨 수, 성능 통계 등 이미 수집된 장치 데이터를 보완합니다.  주석을 사용하여 추가한 데이터는 Data Infrastructure Insights 에서 검색되지 않습니다.

.단계
. Data Infrastructure Insights 메뉴에서 *관리 > 주석*을 클릭합니다.
+
주석 페이지에는 주석 목록이 표시됩니다.

. *+추가*를 클릭하세요
. 주석의 *이름*과 *설명*을 입력하세요.
+
이 필드에는 최대 255자까지 입력할 수 있습니다.

. *유형*을 클릭한 다음 이 주석에 허용되는 데이터 유형을 나타내는 다음 옵션 중 하나를 선택합니다.


.주석 유형
* 부울: '예'와 '아니요' 선택 항목을 포함하는 드롭다운 목록을 생성합니다. 예를 들어, "직접 연결됨" 주석은 부울 값입니다.
* 날짜: 날짜를 저장하는 필드를 만듭니다. 예를 들어, 주석이 날짜인 경우 이를 선택합니다.
* 목록: 다음 중 하나를 생성합니다.
+
** 드롭다운 고정 목록
+
다른 사람이 장치에 이 주석 유형을 할당하는 경우 목록에 더 많은 값을 추가할 수 없습니다.

** 드롭다운 유연한 목록
+
이 목록을 만들 때 즉시 새 값 추가 옵션을 선택하면 다른 사람이 장치에서 이 주석 유형을 할당할 때 목록에 더 많은 값을 추가할 수 있습니다.



* 숫자: 주석을 할당하는 사용자가 숫자를 입력할 수 있는 필드를 만듭니다.  예를 들어, 주석 유형이 "층"인 경우 사용자는 값 유형으로 "숫자"를 선택하고 층 번호를 입력할 수 있습니다.
* 텍스트: 자유형 텍스트를 입력할 수 있는 필드를 만듭니다.  예를 들어, 주석 유형으로 "언어"를 입력하고, 값 유형으로 "텍스트"를 선택하고, 값으로 언어를 입력할 수 있습니다.



NOTE: 유형을 설정하고 변경 사항을 저장한 후에는 주석 유형을 변경할 수 없습니다.  유형을 변경해야 하는 경우 주석을 삭제하고 새 주석을 만들어야 합니다.

. 주석 유형으로 목록을 선택한 경우 다음을 수행합니다.
+
.. 자산 페이지에 있을 때 주석에 더 많은 값을 추가할 수 있는 기능을 원하면 *즉시 새 값 추가*를 선택하세요. 이렇게 하면 유연한 목록이 생성됩니다.
+
예를 들어, 자산 페이지에 있고 자산에 '도시' 주석이 있고 값이 '디트로이트', '탬파', '보스턴'이라고 가정해 보겠습니다.  *즉시 새 값 추가* 옵션을 선택한 경우, 주석 페이지로 이동하여 값을 추가하지 않고도 자산 페이지에서 샌프란시스코나 시카고와 같은 도시에 직접 값을 추가할 수 있습니다.  이 옵션을 선택하지 않으면 주석을 적용할 때 새로운 주석 값을 추가할 수 없습니다. 이렇게 하면 고정 목록이 생성됩니다.

.. *값* 및 *설명* 필드에 값과 설명을 입력합니다.
.. 추가 값을 추가하려면 *+추가+*를 클릭하세요.
.. 값을 삭제하려면 휴지통 아이콘을 클릭하세요.


. *저장*을 클릭하세요
+
주석은 주석 페이지의 목록에 표시됩니다.



.부울 주석에 대한 참고 사항
부울 주석을 필터링할 때 필터링할 다음 값이 표시될 수 있습니다.

* *모든*: "예", "아니요"로 설정된 결과 또는 전혀 설정되지 않은 결과를 포함하여 _모든_ 결과가 반환됩니다.
* *예*: "예" 결과만 반환합니다. DII는 대부분 표에서 체크 표시로 "예"를 표시합니다. 값은 "참", "켜짐" 등으로 설정할 수 있으며, DII는 이러한 모든 값을 "예"로 처리합니다.
* *아니요*: "아니요" 결과만 반환합니다. DII는 대부분 표에서 "아니요"를 "X"로 표시합니다. 값은 "False", "Off" 등으로 설정될 수 있으며, DII는 이러한 모든 값을 "No"로 처리합니다.
* *없음*: 주석이 전혀 설정되지 않은 결과만 반환합니다. "Null" 값이라고도 합니다.


.당신이 완료한 후
UI에서 주석은 즉시 사용할 수 있습니다.
