---
sidebar: sidebar 
permalink: task_business_entity_annotations.html 
keywords: annotations, business entity 
summary: 비즈니스 엔터티 주석은 비즈니스 계층의 자산을 모니터링하고 보고하는 데 사용할 수 있습니다. 
---
= 비즈니스 엔터티 주석
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
*비즈니스 엔터티* 주석 유형을 사용하여 기업 환경에 대한 비즈니스 엔터티를 만들고 관리합니다.



== 사업체 만들기

사업체를 만들려면 다음을 수행하세요.

. *관리 > 주석*을 클릭하고 _사업체_ 링크를 클릭합니다.
+
현재 정의된 사업체 목록이 표시됩니다.

. *+ 사업체*를 클릭하세요.
. *테넌트*, *사업부*, *사업부*, *프로젝트* 필드에 값을 입력합니다.
+
귀하의 사업체에 해당되지 않는 필드는 비워두셔도 됩니다.

. 이전에 필드에 값을 입력한 경우 드롭다운에서 해당 값을 선택할 수 있습니다.  다시 입력할 필요가 없습니다.



NOTE: 선택된 값은 고유한 전체 사업체를 구성해야 합니다.  예를 들어, 이미 _A / B / C / D_ 값을 순서대로 갖는 사업체가 있는 경우 해당 값을 순서대로 갖는 다른 사업체를 만들 수 없습니다.  하지만 다른 순서로 해당 값을 사용하여 비즈니스 엔터티를 만들 수도 있습니다.



== 객체에 비즈니스 엔터티 적용

비즈니스 엔터티를 개체에 적용하는 가장 쉬운 방법은 쿼리를 사용하는 것입니다.

. *쿼리 > +새 쿼리*를 클릭하고 원하는 개체 유형을 선택합니다.  필터를 적용하면 결과를 더욱 좁힐 수 있습니다.
. 체크박스를 클릭하여 비즈니스 엔터티를 적용할 객체를 선택합니다.
. *대량 작업*을 클릭하고 *주석 추가*를 선택하세요.
. _사업체_ 주석을 선택하고 목록에서 원하는 사업체 값을 선택합니다.
. *저장*을 클릭하여 비즈니스 엔터티를 개체에 적용합니다.


또한, 개체의 자산 랜딩 페이지로 이동하여 사용자 데이터 섹션에서 *+주석)을 클릭하여 개별 개체에 비즈니스 엔터티를 적용할 수도 있습니다.

또한 다음을 구성할 수도 있습니다.link:task_create_annotation_rules.html["주석 규칙"] 비즈니스 엔터티를 객체에 적용합니다.


NOTE: 하나의 객체에는 하나의 비즈니스 엔터티만 연관될 수 있습니다.



== 객체에서 비즈니스 엔터티 제거

개체에서 비즈니스 엔터티를 제거하려면 해당 개체를 쿼리하여 선택하고 *대량 작업*을 클릭한 다음 _주석 제거_를 선택합니다.  사업체 주석을 선택하고 *삭제*를 클릭합니다.
