---
sidebar: sidebar 
permalink: task_dc_brocade_rest.html 
keywords: data collector, Brocade, FC switch, FOS, Rest 
summary: Brocade FOS REST 데이터 수집기를 구성합니다. 
---
= Brocade FOS REST 데이터 수집기
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Data Infrastructure Insights Brocade FOS REST 수집기를 사용하여 FabricOS(FOS) 펌웨어 8.2 이상을 실행하는 Brocade 스위치 장치의 인벤토리와 성능을 검색합니다.  초기 8.2 FOS 릴리스에는 REST API 버그가 있을 수 있으니, 플랫폼에서 지원하는 최신 FOS 릴리스를 실행하는 것이 좋습니다.

참고: FOS의 기본 "사용자" 수준은 Data Infrastructure Insights 장치의 모든 논리적 측면을 볼 수 있을 만큼 강력하지 않습니다. "섀시 역할"이 활성화된 사용자 계정과 스위치에 구성된 모든 가상 패브릭에 대한 권한이 필요합니다.

다음은 FOS 장치에 대한 SSH 세션에서 Data Infrastructure Insights 사용을 위한 "최소 권한" 사용자 계정을 만드는 방법의 예입니다.

userConfig --NetAppCIUser 추가 -r 사용자 -l 1-128 -c 사용자 -p Qwerty!

이렇게 하면 비밀번호가 "Qwerty!"인 "NetAppCIUser" 사용자가 생성됩니다.  이 사용자는 가능한 128개의 모든 가상 패브릭(-l)에 걸쳐 "사용자" 역할(-r)을 갖습니다.  이 사용자는 또한 사용자 수준 액세스가 할당된 필수 "섀시" 역할(-c)을 갖고 있습니다.

기본적으로 이 수집기는 스위치가 속한 모든 패브릭에 속하는 모든 FOS 장치를 검색하려고 시도합니다.

참고: FOS의 기본 읽기 전용 사용자 "user"는 모든 가상 패브릭에 대한 보기 권한이 없으며 "섀시 역할" 권한도 없습니다.  즉, FOS 장치의 물리적 및 논리적 구성을 모두 이해해야 하는 Data Infrastructure Insights 에서 "사용자"를 사용하여 성공할 가능성이 낮다는 것을 의미합니다.



== 술어

Data Infrastructure Insights Brocade FOS REST 데이터 수집기에서 다음과 같은 인벤토리 정보를 수집합니다.  Data Infrastructure Insights 에서 수집한 각 자산 유형에 대해 해당 자산에 가장 일반적으로 사용되는 용어가 표시됩니다.  이 데이터 수집기를 보거나 문제를 해결할 때 다음 용어를 염두에 두십시오.

[cols="2*"]
|===
| 공급업체/모델 용어 | Data Infrastructure Insights 용어 


| 스위치 | 스위치 


| 포트 | 포트 


| 가상 패브릭, 물리적 패브릭 | 구조 


| 존 | 존 


| 논리 스위치 | 논리 스위치 


| LSAN 구역 | IVR 구역 
|===
참고: 이는 일반적인 용어 매핑일 뿐이며 이 데이터 수집기의 모든 사례를 나타내지 않을 수 있습니다.



== 요구 사항

* 패브릭의 모든 스위치에는 TCP 연결이 있어야 합니다.  이 데이터 수집기 ​​유형은 패브릭의 각 장치에 대해 HTTP와 HTTPS를 모두 원활하게 시도합니다.  _패브릭의 모든 스위치 검색_ 확인란을 선택하면 Data Infrastructure Insights 패브릭의 모든 스위치를 식별합니다. 하지만 이러한 추가 스위치를 검색하려면 해당 스위치에 대한 TCP 연결이 필요합니다.
* 패브릭의 모든 스위치에서 전역적으로 동일한 계정이 필요합니다.  장치의 웹 인터페이스를 사용하여 액세스를 확인할 수 있습니다.




== 구성

[cols="2*"]
|===
| 필드 | 설명 


| IP 전환 | FOS 스위치의 IP 주소 또는 정규화된 도메인 이름 


| 사용자 이름 | 스위치의 사용자 이름 


| 비밀번호 | 스위치의 비밀번호 
|===


== 고급 구성

[cols="2*"]
|===
| 필드 | 설명 


| 제외된 장치 | 폴링에서 제외할 장치 IPv4 주소의 쉼표로 구분된 목록입니다. 


| 재고 폴링 간격(분) | 재고 조사 간격.  기본값은 60입니다. 


| 패브릭의 모든 스위치를 검색하세요 | 패브릭의 모든 스위치를 검색하도록 선택합니다. 


| HBA 대 영역 별칭을 선호하도록 선택하세요 | HBA 또는 영역 별칭을 선호할지 선택합니다. 


| 연결 유형 | HTTP 또는 HTTPS. 


| 이 설정은 CI가 장치별로 먼저 사용하려고 하는 프로토콜만 변경한다는 점에 유의하세요. 기본값이 실패하면 CI는 자동으로 반대 프로토콜을 시도합니다. | TCP 포트 재정의 


| 기본값을 사용하지 않는 경우 포트를 지정하세요. | 성능 폴링 간격(초) 
|===


== 문제 해결

이 데이터 수집기에 문제가 발생하면 시도해 볼 수 있는 몇 가지 사항은 다음과 같습니다.



=== 목록

[cols="2*"]
|===
| 문제: | 다음을 시도해 보세요: 


| 테스트 기능은 프로토콜에 접근할 수 없다고 경고합니다. | Brocade FOS 8.2+ 장치는 HTTP 또는 HTTPS로만 통신하려고 합니다. 스위치에 디지털 인증서가 설치된 경우 암호화되지 않은 HTTP 대신 HTTPS로 통신을 시도하면 스위치에서 HTTP 오류가 발생합니다.  테스트 기능은 HTTP와 HTTPS 둘 다와 통신을 시도합니다. 테스트에서 한 프로토콜이 통과한다고 나오면 수집기를 안전하게 저장하고 다른 프로토콜이 실패했는지 걱정할 필요가 없습니다. 수집기는 수집하는 동안 두 프로토콜을 모두 시도하고 둘 다 작동하지 않는 경우에만 실패합니다. 


| 오류: 인벤토리가 401 인증되지 않음...잘못된 세션 키...로 실패합니다. | 이는 HTTP 기본 인증을 제대로 지원하지 않는 일부 초기 8.2 FOS 릴리스와 8.2.1c의 뚜렷한 버그입니다.  이후 8.2 또는 9.* 릴리스로 업그레이드하세요. 


| 오류: "Data Infrastructure Insights 잘못된 섀시 역할을 받았습니다." | 이 데이터 소스에 구성된 사용자에게 섀시 역할 권한이 부여되었는지 확인하세요. 


| 오류: "섀시 IP 주소가 일치하지 않습니다" | 섀시 IP 주소를 사용하도록 데이터 소스 구성을 변경합니다. 


| 403 Forbidden 오류로 인해 인벤토리가 실패합니다. | 이는 단순히 자격 증명이 잘못되었거나, 충분히 강력하지 않은 역할을 사용하려고 한다는 것을 나타낼 수 있습니다. "사용자" 수준의 사용자는 필요한 "섀시 역할" 권한이 없고, 기본이 아닌 가상 패브릭에 대한 보기 액세스 권한이 없다는 점을 기억하세요. 
|===
추가 정보는 다음에서 찾을 수 있습니다.link:concept_requesting_support.html["지원하다"] 페이지 또는link:reference_data_collector_support_matrix.html["데이터 수집기 지원 매트릭스"] .
