---
sidebar: sidebar 
permalink: task_dc_ms_hyperv.html 
keywords: data collector, Microsoft, Hyper-V 
summary: Microsoft Hyper-V 데이터 수집기 구성. 
---
= Microsoft Hyper-V 데이터 수집기
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Microsoft Hyper-V 데이터 수집기는 가상화된 서버 컴퓨팅 환경에서 인벤토리 및 성능 데이터를 가져옵니다. 이 데이터 수집기는 독립 실행형 Hyper-V 호스트를 검색할 수도 있고, 전체 클러스터를 검색할 수도 있습니다. 독립 실행형 호스트 또는 클러스터당 하나의 Collector를 생성할 수도 있습니다.



== 용어

Data Infrastructure Insights는 Microsoft Hyper-V(WMI)에서 다음과 같은 인벤토리 정보를 가져옵니다. Data Infrastructure Insights에서 구입한 각 자산 유형에 대해 이 자산에 사용되는 가장 일반적인 용어가 표시되어 있습니다. 이 데이터 수집기를 보거나 문제를 해결할 때 다음 용어를 염두에 두십시오.

[cols="2*"]
|===
| 공급업체/모델 기간 | Data Infrastructure Insights 용어 


| 가상 하드 디스크 | 가상 디스크 


| 호스트 | 호스트 


| 가상 머신 | 가상 머신 


| CSV(Cluster Shared Volumes), 파티션 볼륨 | 데이터 저장소 


| 인터넷 SCSI 장치, 다중 경로 SCSI LUN | LUN입니다 


| Fibre Channel 포트 | 포트 
|===
참고: 이러한 용어 매핑은 일반적인 용어 매핑일 뿐이며 이 데이터 수집기의 모든 경우를 나타내는 것은 아닙니다.



== 요구 사항

이 데이터 수집기를 구성하려면 다음이 필요합니다.

* Hyper-V를 사용하려면 데이터 수집 및 원격 액세스/관리를 위해 포트 5985를 열어야 합니다.
* 클러스터 또는 독립 실행형 하이퍼바이저의 IP 주소 또는 FQDN입니다. 부동 클러스터 호스트 이름 또는 IP를 사용하는 것이 가장 신뢰할 수 있는 방법일 수 있습니다. 이는 수집기가 클러스터의 특정 노드 중 하나만 가리키는 것과 비교할 수 있습니다.
* 클러스터의 모든 하이퍼바이저에서 작동하는 관리 수준 사용자 계정입니다.
* WinRM은 모든 하이퍼바이저에서 활성화되어 있어야 합니다
* 포트 요구 사항: Windows 2003 및 이전 버전의 경우 1024-65535로 할당된 WMI 및 동적 TCP 포트를 통해 135번 포트 및 Windows 2008의 경우 49152-65535번 포트.
* 데이터 수집기가 IP 주소만 가리키는 경우에도 DNS 확인이 성공해야 합니다
* 각 Hyper-V 하이퍼바이저에는 모든 호스트의 모든 VM에 대해 "리소스 계측"이 켜져 있어야 합니다. 따라서 각 하이퍼바이저에서 각 게스트에서 Data Infrastructure Insights에 더 많은 데이터를 사용할 수 있습니다. 이 옵션을 설정하지 않으면 각 게스트에 대해 더 적은 성능 메트릭이 획득됩니다. 리소스 측정에 대한 자세한 내용은 Microsoft 설명서를 참조하십시오.
+
link:https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-R2-and-2012/hh831661(v=ws.11)["Hyper-V 리소스 측정 개요"]

+
link:https://docs.microsoft.com/en-us/powershell/module/hyper-v/enable-vmresourcemetering?view=win10-ps["활성화 - VMResourceMetering"]




NOTE: Hyper-V 데이터 수집기는 Windows 획득 장치가 필요합니다.



== 구성

[cols="2*"]
|===
| 필드에 입력합니다 | 설명 


| 클러스터 IP 주소 또는 부동 클러스터 FQDN입니다 | 클러스터의 IP 주소 또는 정규화된 도메인 이름 또는 클러스터링되지 않은 독립 실행형 하이퍼바이저입니다 


| 사용자 이름 | 하이퍼바이저의 관리자 사용자 이름입니다 


| 암호 | 하이퍼바이저의 암호입니다 


| DNS 도메인 접미사 | 하이퍼바이저의 FQDN을 렌더링하기 위해 단순 호스트 이름과 결합된 호스트 이름 접미사 
|===


== 고급 구성

[cols="2*"]
|===
| 필드에 입력합니다 | 설명 


| 재고 폴링 간격(분) | 기본값은 20분입니다. 
|===


== 문제 해결

이 데이터 수집기에 대한 추가 정보는 페이지 또는 에서 찾을 link:concept_requesting_support.html["지원"]link:reference_data_collector_support_matrix.html["Data Collector 지원 매트릭스"]수 있습니다.
