---
sidebar: sidebar 
permalink: task_dc_hds_nas.html 
keywords: data collector, HDS HNAS, HDS NAS 
summary: 'HDS NAS(HNAS) 데이터 수집기를 구성합니다.' 
---
= Hitachi Vantara NAS 데이터 수집기 구성
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Hitachi Vantara NAS 데이터 수집기는 HDS NAS 클러스터 검색을 지원하는 인벤토리 및 구성 데이터 수집기입니다.  Data Infrastructure Insights NFS 및 CIFS 공유, 파일 시스템(내부 볼륨), 스팬(스토리지 풀)을 검색하는 기능을 지원합니다.



== 술어

Data Infrastructure Insights HNAS 데이터 수집기에서 다음과 같은 인벤토리 정보를 수집합니다.  Data Infrastructure Insights 에서 수집한 각 자산 유형에 대해 해당 자산에 가장 일반적으로 사용되는 용어가 표시됩니다.  이 데이터 수집기를 보거나 문제를 해결할 때 다음 용어를 염두에 두십시오.

[cols="2*"]
|===
| 공급업체/모델 용어 | Data Infrastructure Insights 용어 


| 층 | 디스크 그룹 


| 무리 | 스토리지 


| 마디 | 저장 노드 


| 기간 | 스토리지 풀 


| 시스템 드라이브 | 백엔드 LUN 


| 파일 시스템 | 내부 볼륨 
|===
참고: 이는 일반적인 용어 매핑일 뿐이며 이 데이터 수집기의 모든 사례를 나타내지 않을 수 있습니다.



== 요구 사항

* 장치 IP 주소
* 포트 22, SSH 프로토콜
* 사용자 이름 및 비밀번호 - 권한 수준: 관리자
* 참고: 이 데이터 수집기는 SSH 기반이므로 이를 호스팅하는 AU는 HNAS 자체의 TCP 22 또는 클러스터가 연결된 시스템 관리 장치(SMU)에 대한 SSH 세션을 시작할 수 있어야 합니다.




== 구성

[cols="2*"]
|===
| 필드 | 설명 


| HNAS 호스트 | HNAS 관리 호스트의 IP 주소 또는 정규화된 도메인 이름 


| 사용자 이름 | HNAS CLI의 사용자 이름 


| 비밀번호 | HNAS CLI에 사용되는 비밀번호 
|===


== 고급 구성

[cols="2*"]
|===
| 필드 | 설명 


| 재고 폴링 간격(분) | 재고 조사 간격. 기본값은 30분입니다. 
|===


== 문제 해결

이 데이터 수집기에 문제가 발생하면 시도해 볼 수 있는 몇 가지 사항은 다음과 같습니다.



=== 목록

[cols="2*"]
|===
| 문제: | 다음을 시도해 보세요: 


| "연결 오류"와 함께 "셸 채널 설정 오류:" 또는 "셸 채널 열기 오류" 오류 메시지가 표시됩니다. | 네트워크 연결 문제나 SSH가 잘못 구성된 것이 원인일 수 있습니다.  대체 SSH 클라이언트와의 연결 확인 


| "시간 초과" 또는 "데이터 검색 오류"와 함께 "명령: XXX의 시간이 초과되었습니다."라는 오류 메시지가 표시됩니다. | * 대체 SSH 클라이언트로 명령을 시도하세요. * 시간 초과를 늘리세요. 


| "연결 오류" 또는 "잘못된 로그인 자격 증명"과 함께 "장치와 통신할 수 없습니다."라는 오류 메시지가 표시됩니다. | * IP 주소 확인 * 사용자 이름 및 비밀번호 확인 * 대체 SSH 클라이언트와의 연결 확인 
|===
추가 정보는 다음에서 찾을 수 있습니다.link:concept_requesting_support.html["지원하다"] 페이지 또는link:reference_data_collector_support_matrix.html["데이터 수집기 지원 매트릭스"] .
