---
sidebar: sidebar 
permalink: task_dc_emc_powerstore.html 
keywords: data collector, PowerStore, EMC, DELL 
summary: DELL EMC PowerStore 데이터 수집기를 구성합니다. 
---
= Dell EMC PowerStore 데이터 수집기
:hardbreaks:
:allow-uri-read: 


[role="lead"]
EMC PowerStore 데이터 수집기는 EMC PowerStore 스토리지에서 인벤토리 정보를 수집합니다.  구성을 위해 데이터 수집기에는 스토리지 프로세서의 IP 주소와 읽기 전용 사용자 이름과 비밀번호가 필요합니다.

EMC PowerStore 데이터 수집기는 PowerStore가 다른 스토리지 어레이에서 조정하는 볼륨 간 복제 관계를 수집합니다.  Data Infrastructure Insights 각 PowerStore 클러스터에 대한 스토리지 배열을 보여주고 해당 클러스터의 노드와 스토리지 포트에 대한 인벤토리 데이터를 수집합니다.  스토리지 풀이나 볼륨 데이터는 수집되지 않습니다.



== 술어

Data Infrastructure Insights 이 데이터 수집기로부터 다음과 같은 인벤토리 정보를 수집합니다.  Data Infrastructure Insights 에서 수집한 각 자산 유형에 대해 해당 자산에 가장 일반적으로 사용되는 용어가 표시됩니다.  이 데이터 수집기를 보거나 문제를 해결할 때 다음 용어를 염두에 두십시오.

[cols="2*"]
|===
| 공급업체/모델 용어 | Data Infrastructure Insights 용어 


| 주인 | 주인 


| 호스트 볼륨 매핑 | 호스트 볼륨 매핑 


| 하드웨어("extra_details" 개체 아래에 드라이브가 있음): 드라이브 | 디스크 


| 기구 | 스토리지풀 


| 무리 | 스토리지 어레이 


| 마디 | 스토리지노드 


| fc_포트 | 포트 


| 용량 | 용량 


| 내부 볼륨 | 파일 시스템 
|===
참고: 이는 일반적인 용어 매핑일 뿐이며 이 데이터 수집기의 모든 사례를 나타내지 않을 수 있습니다.



== 요구 사항

이 데이터 수집기를 구성하려면 다음 정보가 필요합니다.

* 저장 프로세서의 IP 주소 또는 정규화된 도메인 이름
* 읽기 전용 사용자 이름 및 비밀번호




== 구성

[cols="2*"]
|===
| 필드 | 설명 


| PowerStore 게이트웨이 | PowerStore 스토리지의 IP 주소 또는 정규화된 도메인 이름 


| 사용자 이름 | PowerStore의 사용자 이름 


| 비밀번호 | PowerStore에 사용되는 비밀번호 
|===


== 고급 구성

[cols="2*"]
|===
| 필드 | 설명 


| HTTPS 포트 | 기본값은 443입니다 


| 재고 폴링 간격(분) | 재고 조사 간격. 기본값은 60분입니다. 
|===
Cloud Insight의 PowerStore 성능 수집은 PowerStore의 5분 단위 소스 데이터를 활용합니다.  따라서 Data Infrastructure Insights 5분마다 해당 데이터를 폴링하며, 이는 구성할 수 없습니다.



== 문제 해결

이 데이터 수집기에 대한 추가 정보는 다음에서 찾을 수 있습니다.link:concept_requesting_support.html["지원하다"] 페이지 또는link:reference_data_collector_support_matrix.html["데이터 수집기 지원 매트릭스"] .
