---
sidebar: sidebar 
permalink: task_dc_hpe_nimble.html 
keywords: data collector, HP Nimble, HP, HPE, Alletra 6000 
summary: 'HP Enterprise Alletra 6000(이전 Nimble) 데이터 수집기 구성.' 
---
= HPE Alletra 6000 데이터 수집기
:hardbreaks:
:allow-uri-read: 


[role="lead"]
HP Enterprise Alletra 6000(이전 Nimble) 데이터 수집기는 Alletra 6000 스토리지 어레이의 인벤토리 및 성능 데이터를 지원합니다.



== 술어

Data Infrastructure Insights 이 수집기에서 다음과 같은 인벤토리 정보를 수집합니다.  Data Infrastructure Insights 에서 수집한 각 자산 유형에 대해 해당 자산에 가장 일반적으로 사용되는 용어가 표시됩니다.  이 데이터 수집기를 보거나 문제를 해결할 때 다음 용어를 염두에 두십시오.

[cols="2*"]
|===
| 공급업체/모델 용어 | Data Infrastructure Insights 용어 


| 정렬 | 스토리지 


| 디스크 | 디스크 


| 용량 | 용량 


| 수영장 | 스토리지 풀 


| 창시자 | 스토리지 호스트 별칭 


| 제어 장치 | 저장 노드 


| 파이버 채널 인터페이스 | 제어 장치 
|===
참고: 이는 일반적인 용어 매핑일 뿐이며 이 데이터 수집기의 모든 사례를 나타내지 않을 수 있습니다.



== 요구 사항

스토리지 어레이에서 인벤토리 및 구성 데이터를 수집하려면 다음이 필요합니다.

* 어레이는 설치 및 구성되어야 하며, 클라이언트에서 정규화된 도메인 이름(FQDN)이나 어레이 관리 IP 주소를 통해 접근할 수 있어야 합니다.
* 어레이는 NimbleOS 2.3.x 이상을 실행해야 합니다.
* 최소한 "운영자" 수준 역할이 있는 배열에 대한 유효한 사용자 이름과 암호가 있어야 합니다.  "게스트" 역할에는 개시자 구성을 이해할 수 있는 충분한 액세스 권한이 없습니다.
* 어레이에서 포트 5392가 열려 있어야 합니다.


스토리지 어레이에서 성능 데이터를 수집하려면 다음이 필요합니다.

* 배열은 NimbleOS 4.0.0 이상을 실행해야 합니다.
* 어레이에는 볼륨이 구성되어 있어야 합니다.  NimbleOS가 제공하는 유일한 성능 API는 볼륨에 대한 것이며 모든 통계 Data Infrastructure Insights 보고서는 볼륨에 대한 통계에서 파생됩니다.




== 구성

[cols="2*"]
|===
| 필드 | 설명 


| 어레이 관리 IP 주소 | 정규화된 도메인 이름(FQDN) 또는 어레이 관리 IP 주소입니다. 


| 사용자 이름 | 배열의 사용자 이름 


| 비밀번호 | 배열의 비밀번호 
|===


== 고급 구성

|===


| 필드 | 설명 


| 포트 | Nimble REST API에서 사용하는 포트입니다.  기본값은 5392입니다. 


| 재고 폴링 간격(분) | 재고 조사 간격. 기본값은 60분입니다. 
|===
참고: 기본 성능 폴링 간격은 300초이며 변경할 수 없습니다.  이는 HPE Alletra 6000에서 지원하는 유일한 간격입니다.
