---
sidebar: sidebar 
permalink: task_dc_ibm_svc.html 
keywords: IBM, SVC,SAN 
summary: IBM SAN Volume Controller 데이터 수집기를 구성합니다. 
---
= IBM SAN Volume Controller 데이터 수집기 구성
:hardbreaks:
:allow-uri-read: 


[role="lead"]
IBM SAN Volume Controller(SVC) 데이터 수집기는 SSH를 사용하여 인벤토리 및 성능 데이터를 수집하며, SVC 운영 체제를 실행하는 다양한 장치를 지원합니다.

지원되는 장치 목록에는 SVC, v7000, v5000, v3700 등의 모델이 포함됩니다.  지원되는 모델과 펌웨어 버전은 Data Infrastructure Insights 지원 매트릭스를 참조하세요.



== 술어

Data Infrastructure Insights IBM SVC 데이터 수집기에서 다음과 같은 인벤토리 정보를 수집합니다.  Data Infrastructure Insights 에서 수집한 각 자산 유형에 대해 해당 자산에 가장 일반적으로 사용되는 용어가 표시됩니다.  이 데이터 수집기를 보거나 문제를 해결할 때 다음 용어를 염두에 두십시오.

[cols="2*"]
|===
| 공급업체/모델 용어 | Data Infrastructure Insights 용어 


| 운전하다 | 디스크 


| 무리 | 스토리지 


| 마디 | 저장 노드 


| Mdisk 그룹 | 스토리지 풀 


| V디스크 | 용량 


| 엠디스크 | 백엔드 LUN 및 경로 
|===
참고: 이는 일반적인 용어 매핑일 뿐이며 이 데이터 수집기의 모든 사례를 나타내지 않을 수 있습니다.



=== 재고 요구 사항

* 각 SVC 클러스터의 IP 주소
* 포트 22 사용 가능
* 읽기 전용 사용자 이름 및 비밀번호




=== 성능 요구 사항

* SVC 클러스터에 필수이며 SVC Discovery Foundation 패키지에 필요한 SVC 콘솔입니다.
* 클러스터 노드에서 구성 노드로 성능 파일을 복사하는 경우에는 자격 증명에 관리 액세스 수준만 필요합니다.
* SSH를 통해 SVC 클러스터에 연결하고 _svctask startstats -interval 1_을 실행하여 데이터 수집을 활성화합니다.
+
참고: 또는 SVC 관리 사용자 인터페이스를 사용하여 데이터 수집을 활성화하세요.





== 구성

[cols="2*"]
|===
| 필드 | 설명 


| 클러스터 IP 주소 | SVC 스토리지의 IP 주소 또는 정규화된 도메인 이름 


| 인벤토리 사용자 이름 | SVC CLI의 사용자 이름 


| 재고 비밀번호 | SVC CLI에 대한 비밀번호 
|===


== 고급 구성

[cols="2*"]
|===
| 필드 | 설명 


| 재고 폴링 간격(분) | 재고 조사 간격. 기본값은 40분입니다. 


| 성능 폴링 간격(초) | 성과 여론조사 간격. 기본값은 300초입니다. 


| 덤프된 통계 파일을 정리하려면 | 덤프된 통계 파일을 정리하려면 이 확인란을 선택하세요. 
|===


== 문제 해결

이 데이터 수집기에 문제가 발생하면 시도해 볼 수 있는 몇 가지 사항은 다음과 같습니다.

[cols="2*"]
|===
| 문제: | 다음을 시도해 보세요: 


| 오류: "구성 노드에서 실행되지 않았기 때문에 명령을 시작할 수 없습니다." | 해당 명령은 구성 노드에서 실행되어야 합니다. 
|===
이 데이터 수집기에 문제가 발생하면 시도해 볼 수 있는 몇 가지 사항은 다음과 같습니다.

[cols="2*"]
|===
| 문제: | 다음을 시도해 보세요: 


| 오류: "구성 노드에서 실행되지 않았기 때문에 명령을 시작할 수 없습니다." | 해당 명령은 구성 노드에서 실행되어야 합니다. 
|===
이 데이터 수집기에 대한 추가 정보는 다음에서 찾을 수 있습니다.link:concept_requesting_support.html["지원하다"] 페이지 또는link:reference_data_collector_support_matrix.html["데이터 수집기 지원 매트릭스"] .
