---
sidebar: sidebar 
permalink: task_dc_proxmox_ve.html 
keywords: data collector, Proxmox Virtual Environment, PVE 
summary: Proxmox Virtual Environment 데이터 수집기 구성. 
---
= Proxmox Virtual Environment 데이터 수집기
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
DII Proxmox 가상 환경 수집기는 PVE 기반 가상 머신(LXC 컨테이너 제외) 및 호스트/하이퍼바이저에 대한 인벤토리 및 성능 데이터를 수집합니다. 이 수집기는 HTTPS REST API 기반이며, TCP 8006 포트에서 수신 대기하는 pveproxy 서비스/데몬이 제공하는 Proxmox REST API와 통신해야 합니다.

이 데이터 수집기는 사용자 + 토큰 인증을 사용합니다. 각 Proxmox 클러스터에 서비스 계정을 생성하고 해당 사용자에게 적절한 권한을 할당한 다음, 동일한 권한을 가진 API 토큰을 생성해야 합니다. 특정 Proxmox 사용자의 토큰이 사용자와 동일한 권한을 갖는 것은 아니라는 점에 유의하십시오. DII는 일반적으로 전역 감사/모니터링 수준 권한이 필요합니다. Proxmox UI를 통해 서비스 계정을 생성하는 경우, PathPermision은 "/"로 시작하고, 전파(Propagate)는 "예"로 설정하며, 최소한 Datastore Audit, Mapping Audit, Pool Audit, SDN Audit, Sys Audit, VM Audit, VM Monitor 권한을 활성화해야 합니다. 사용자 계정이 생성되면 해당 계정에 대한 액세스 토큰을 생성할 수 있습니다. 토큰 만료 기한을 0으로 설정하여 토큰이 만료되지 않도록 하는 것이 좋습니다.



[[terminology]]
== 술어

Data Infrastructure Insights 에서 수집한 각 자산 유형에 대해 해당 자산에 가장 일반적으로 사용되는 용어가 표시됩니다.  이 데이터 수집기를 보거나 문제를 해결할 때 다음 용어를 염두에 두십시오.

[cols="50,50"]
|===
| 공급업체/모델 용어 | Data Infrastructure Insights 용어 


| 디스크 | 가상 디스크 


| 주인 | 주인 


| 가상 머신 | 가상 머신 


| 스토리지 | 데이터 저장소 
|===
참고: 이는 일반적인 용어 매핑일 뿐이며 이 데이터 수집기의 모든 사례를 나타내지 않을 수 있습니다.



[[configuration]]
== 구성

[cols="50,50"]
|===
| 필드 | 설명 


| 호스트 이름 또는 IP 주소 | 호스트 이름 스토리지 시스템의 IP 주소 


| API 토큰 ID | 접근하려면 API 토큰이 필요합니다. 


| API 토큰 시크릿 | 위 토큰의 시크릿 
|===


[[advanced-configuration]]
== 고급 구성

[cols="50,50"]
|===
| 필드 | 설명 


| HTTPS 통신 포트 | HTTPS 통신에 사용되는 포트(기본값 8006) 


| 재고 폴링 간격(분) | 기본값은 20분입니다. 
|===


[[troubleshooting]]
== 문제 해결

이 데이터 수집기에 대한 추가 정보는 다음에서 찾을 수 있습니다.link:concept_requesting_support.html["지원하다"] 페이지 또는link:reference_data_collector_support_matrix.html["데이터 수집기 지원 매트릭스"] .
