---
sidebar: sidebar 
permalink: task_dc_oracle_zfs.html 
keywords: data collector, Oracle, ZFS, storage applicance 
summary: Oracle ZFS 데이터 수집기 구성. 
---
= Oracle ZFS Storage Appliance 데이터 수집기
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Data Infrastructure Insights Oracle ZFS Storage Appliance 데이터 수집기를 사용하여 인벤토리 및 성능 데이터를 수집합니다.



== 술어

Data Infrastructure Insights Oracle ZFS 데이터 수집기를 통해 인벤토리 정보를 수집합니다.  Data Infrastructure Insights 에서 수집한 각 자산 유형에 대해 해당 자산에 가장 일반적으로 사용되는 용어가 표시됩니다.  이 데이터 수집기를 보거나 문제를 해결할 때 다음 용어를 염두에 두십시오.

[cols="2*"]
|===
| 공급업체/모델 용어 | Data Infrastructure Insights 용어 


| 디스크(SSD) | 디스크 


| 무리 | 스토리지 


| 제어 장치 | 저장 노드 


| LUN | 용량 


| LUN 맵 | 볼륨 맵 


| 개시자, 대상 | 볼륨 마스크 


| 공유하다 | 내부 볼륨 
|===
참고: 이는 일반적인 용어 매핑일 뿐이며 이 데이터 소스의 모든 사례를 나타내지 않을 수 있습니다.



== 요구 사항

* ZFS Controller-1 및 ZFS Controller-2의 호스트 이름
* 관리자 사용자 이름 및 비밀번호
* 포트 요구 사항: 215 HTTP/HTTPS




== 필수 성능 지표

Oracle ZFS 어플라이언스는 스토리지 관리자에게 성능 통계를 수집하는 데 있어 많은 유연성을 제공합니다.  Data Infrastructure Insights 고가용성 쌍의 각 컨트롤러가 다음 메트릭을 캡처하도록 구성되어 있어야 합니다.

* smb2.ops[공유]
* nfs3.ops[공유]
* nfs4.ops[공유]
* nfs4-1.ops[공유]


컨트롤러가 이러한 모든 것을 포착하지 못하면 Data Infrastructure Insights 에서 "내부 볼륨"에 대한 작업 부하를 파악하지 못하거나 보고하지 못할 가능성이 높습니다.



== 구성

[cols="2*"]
|===
| 필드 | 설명 


| ZFS 컨트롤러-1 호스트 이름 | 스토리지 컨트롤러 1의 호스트 이름 


| ZFS 컨트롤러-2 호스트 이름 | 스토리지 컨트롤러 2의 호스트 이름 


| 사용자 이름 | 스토리지 시스템 관리자 사용자 계정의 사용자 이름 


| 비밀번호 | 관리자 사용자 계정의 비밀번호 
|===


== 고급 구성

[cols="2*"]
|===
| 필드 | 설명 


| 연결 유형 | HTTPS 또는 HTTP도 기본 포트를 표시합니다. 


| 연결 포트 재정의 | 비어 있는 경우 연결 유형 필드에서 기본 포트를 사용하고, 그렇지 않은 경우 사용할 연결 포트를 입력합니다. 


| 재고 폴링 간격 | 기본값은 60초입니다 


| 성능 폴링 간격(초) | 기본값은 300입니다. 
|===


== 문제 해결

이 데이터 수집기에 문제가 발생하면 시도해 볼 수 있는 몇 가지 사항은 다음과 같습니다.



=== 목록

[cols="2a, 2a"]
|===
| 문제: | 다음을 시도해 보세요: 


 a| 
"잘못된 로그인 자격 증명입니다"
 a| 
Zfs 사용자 계정 및 비밀번호 확인



 a| 
"요청이 상태 404 \https://.....:215/api/access/v1로 실패했습니다."
 a| 
ZFS 어레이가 너무 오래되어 REST API를 지원할 수 없습니다.  AK 2013.1.3.0은 REST API를 지원하는 최초의 ZFS OS 릴리스였으며, 모든 ZFS 어플라이언스를 이 버전으로 업그레이드할 수 있는 것은 아닙니다.



 a| 
"REST 서비스가 비활성화되었습니다"라는 오류 메시지가 있는 "구성 오류"
 a| 
이 장치에서 REST 서비스가 활성화되어 있는지 확인하세요.



 a| 
"구성 오류"와 "명령에 대한 권한이 없는 사용자" 오류 메시지가 표시됨
 a| 
이 오류는 구성된 사용자에 대해 특정 역할(예: 'advanced_analytics')이 포함되지 않았기 때문에 발생할 수 있습니다.

읽기 전용 역할이 있는 사용자에게 분석 범위를 적용하면 오류가 제거될 수 있습니다. 다음 단계를 따르세요.

. ZFs 시스템에서 구성 -> 사용자 화면에서 마우스를 역할 위로 이동하고 두 번 클릭하여 편집을 허용합니다.
. 범위 드롭다운 메뉴에서 "분석"을 선택합니다.  가능한 속성 목록이 나타납니다.
. 가장 위에 있는 확인란을 클릭하면 세 개의 속성이 모두 선택됩니다.
. 오른쪽에 있는 추가 버튼을 클릭하세요.
. 팝업 창의 오른쪽 상단에 있는 적용 버튼을 클릭하세요.  팝업창이 닫힙니다.


|===
추가 정보는 다음에서 찾을 수 있습니다.link:concept_requesting_support.html["지원하다"] 페이지 또는link:reference_data_collector_support_matrix.html["데이터 수집기 지원 매트릭스"] .
