---
sidebar: sidebar 
permalink: task_cloud_insights_onboarding_1.html 
summary: Data Infrastructure Insights 에 가입하고 테넌트를 생성합니다. 
keywords: onboarding, new user 
---
= Data Infrastructure Insights 온보딩
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Data Infrastructure Insights 사용하려면 먼저 * NetApp Console* 포털에 가입해야 합니다.  이미 NetApp Console 로그인이 있는 경우 몇 가지 간단한 단계만 거치면 Data Infrastructure Insights 의 무료 평가판을 시작할 수 있습니다.



== NetApp Console 계정 만들기

NetApp의 클라우드 서비스를 시작하려면 다음으로 이동하세요.link:https://console.netapp.com/["* NetApp Console*"^] *시작하기*를 클릭하세요.

* 아직 가입하지 않으셨다면 *가입*을 선택하세요.
* 유효한 비즈니스 이메일 주소를 입력하고 비밀번호를 선택하세요.
* 회사 이름과 성명을 입력하세요.
* 이용 약관에 동의하고 *계속*을 선택하세요.
* 콘솔을 통해 시작하는 방법을 안내해 드립니다.




=== 이미 NetApp Console 로그인이 있는 경우에는 어떻게 해야 하나요?

NetApp Console 계정이 있으면 간단히 *로그인*을 선택하세요.link:https://console.netapp.com/["* NetApp Console*"^] 포털 페이지.

이메일 주소와 비밀번호를 입력하세요.  그러면 NetApp의 클라우드 서비스 페이지로 이동하게 됩니다.

*분석 및 제어 > 관찰성*으로 이동하여 Data Infrastructure Insights 에 대해 알아보거나 데모를 요청하세요.



== Data Infrastructure Insights 무료 평가판 시작하기

Data Infrastructure Insights 에 처음 로그인하시는 경우, Data Infrastructure Insights 제공하는 모든 기능에 대한 정보를 읽어보시고, 준비가 되셨으면 *체험판 요청*을 클릭하여 정보를 입력해 주세요.

평가판 테넌트 설정의 일환으로 테넌트를 호스팅할 리전을 선택하고 AWS 또는 Azure 중 어느 곳에서 테넌트를 호스팅할지 결정해야 합니다.

테넌트 생성이 완료되면 콘솔 자격 증명을 사용하여 로그인하고 Data Infrastructure Insights 의 무료 30일 평가판을 시작하세요. 이 체험판을 통해 Data Infrastructure Insights 제공하는 기능을 탐색해 볼 수 있습니다.

무료 체험 기간 동안 다음을 수행할 수 있습니다.link:concept_subscribing_to_cloud_insights.html["구독을 시작하세요"] 언제든지 Data Infrastructure Insights 에 문의하세요.  구독하면 현재 구독에 따라 Data Infrastructure Insights 기능을 사용할 수 있습니다.



== Sign in 하고 가세요

테넌트가 생성되면 언제든지 NetApp BlueXP 포털에 로그인하여 해당 페이지로 이동하면 됩니다. link:https://services.cloud.netapp.com["클라우드 서비스"] 해당 페이지에서 * Data Infrastructure Insights 로 이동*을 선택합니다.

예를 들어, 브라우저를 Data Infrastructure Insights 테넌트 URL로 직접 열 수도 있습니다.

 \https://<tenant-prefix>.c01.cloudinsights.netapp.com/
각 사용자의 초대 이메일에도 URL이 포함되어 간편하게 접속하고 북마크할 수 있습니다.  사용자가 아직 콘솔에 로그인하지 않은 경우 로그인하라는 메시지가 표시됩니다.


NOTE: 새로운 사용자는 테넌트 URL에 액세스하기 전에 콘솔 액세스에 가입해야 합니다.

새로운 테넌트에 처음 로그인하면 설정 방법에 대한 안내가 제공됩니다.link:task_getting_started_with_cloud_insights.html["*데이터 수집 시작*"] .



== 로그아웃

Data Infrastructure Insights 에서 로그아웃하려면 *사용자 이름*을 클릭하고 *로그아웃*을 선택하세요.  콘솔 로그인 화면으로 돌아갑니다.


NOTE: Data Infrastructure Insights 에서 로그아웃하면 Console에서도 로그아웃됩니다.  콘솔 로그인을 사용하는 다른 NetApp Cloud 서비스에서도 로그아웃됩니다.



=== 비활성 시간 초과

기본적으로 콘솔은 6시간(360분) 동안 활동이 없으면 사용자를 로그아웃합니다.  활동에 관계없이 사용자는 7일 후에 로그아웃됩니다.
