---
sidebar: sidebar 
permalink: task_dc_na_ontap_afx.html 
keywords: data collector, ontap, afx 
summary: ONTAP AFX 컬렉터 
---
= NetApp ONTAP AFX 데이터 수집기
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
이 데이터 수집기는 REST API 호출을 사용하여 ONTAP 9.16.0 이상을 실행하는 스토리지 시스템에서 인벤토리, EMS 로그 및 성능 데이터를 수집합니다.



== 요구 사항

이 데이터 수집기를 구성하고 사용하기 위한 요구 사항은 다음과 같습니다.

* 필요한 수준의 액세스 권한이 있는 사용자 계정에 액세스할 수 있어야 합니다.  새로운 REST 사용자/역할을 생성하는 경우 관리자 권한이 필요합니다.
+
** 기능적으로 Data Infrastructure Insights 주로 읽기 요청을 하지만, Data Infrastructure Insights ONTAP 배열에 등록하려면 일부 쓰기 권한이 필요합니다.  바로 아래의 _권한에 대한 참고사항_을 참조하세요.


* ONTAP 버전 9.16.0 이상.
* 포트 요구 사항: 443




== 권한에 대한 참고 사항

여러 Data Infrastructure Insights ONTAP 대시보드가 ​​고급 ONTAP 카운터에 의존하므로 데이터 수집기 ​​고급 구성 섹션에서 *고급 카운터 데이터 수집 사용*을 활성화된 상태로 유지해야 합니다.

클러스터 수준에서 Data Infrastructure Insights 에 대한 로컬 계정을 만들려면 클러스터 관리 관리자 사용자 이름/비밀번호로 ONTAP 에 로그인하고 ONTAP 서버에서 다음 명령을 실행합니다.

. 시작하기 전에 _관리자_ 계정으로 ONTAP 에 로그인하고 _진단 수준 명령_을 활성화해야 합니다.
. _admin_ 유형인 vserver의 이름을 검색합니다.  이후 명령에서는 이 이름을 사용하게 됩니다.
+
 vserver show -type admin
. 다음 명령을 사용하여 역할을 만듭니다.
+
....
security login rest-role create -role {role name} -api /api -access readonly
security login rest-role create -role {role name} -api /api/cluster/agents -access all
vserver services web access create -name spi -role {role name} -vserver {vserver name as retrieved above}
security login create -user-or-group-name {username} -application http -authentication-method password -role {role name}
....
. 다음 명령을 사용하여 읽기 전용 사용자를 만듭니다.  create 명령을 실행하면 해당 사용자의 비밀번호를 입력하라는 메시지가 표시됩니다.
+
 security login create -username ci_user -application http -authentication-method password -role ci_readonly


AD/LDAP 계정을 사용하는 경우 명령은 다음과 같아야 합니다.

 security login create -user-or-group-name DOMAIN\aduser/adgroup -application http -authentication-method domain -role ci_readonly
결과적으로 나타나는 역할과 사용자 로그인은 다음과 같습니다.  실제 출력은 다를 수 있습니다.

[listing]
----
security login rest-role show -vserver <vserver name> -role restRole

               Role                                    Access
Vserver        Name            API                     Level
----------     -------------   -------------------     ------
<vserver name> restRole        /api                    readonly
                               /api/cluster/agents     all
2 entries were displayed.

security login show -vserver <vserver name> -user-or-group-name restUser

Vserver: <vserver name>
                                                                 Second
User/Group                 Authentication                 Acct   Authentication
Name           Application Method        Role Name        Locked Method
-------------- ----------- ------------- ---------------- ------ --------------
restUser       http        password      restRole         no     none
----


== 이주

이전 ONTAP (ontapi) 데이터 수집기에서 최신 ONTAP REST 수집기로 마이그레이션하려면 다음을 수행하세요.

. REST 수집기를 추가합니다.  이전 수집기에 대해 구성된 사용자와 다른 사용자에 대한 정보를 입력하는 것이 좋습니다.  예를 들어, 위의 권한 섹션에 언급된 사용자를 사용하세요.
. 이전 수집기를 일시 중지하여 더 이상 데이터를 수집하지 않도록 합니다.
. 새로운 REST 수집기가 최소 30분 동안 데이터를 수집하도록 합니다.  이 기간 동안 "정상"으로 보이지 않는 데이터는 무시하세요.
. 휴식 기간이 끝나면 REST 수집기가 계속해서 데이터를 수집함에 따라 데이터가 안정화되는 것을 볼 수 있습니다.


원한다면 이와 동일한 과정을 거쳐 이전 수집기로 돌아갈 수 있습니다.



== 구성

[cols="2*"]
|===
| 필드 | 설명 


| ONTAP 관리 IP 주소 | NetApp 클러스터의 IP 주소 또는 정규화된 도메인 이름입니다.  클러스터 관리 IP/FQDN이어야 합니다. 


| ONTAP REST 사용자 이름 | NetApp 클러스터의 사용자 이름 


| ONTAP REST 비밀번호 | NetApp 클러스터의 비밀번호 
|===


== 고급 구성

[cols="2*"]
|===
| 필드 | 설명 


| 재고 폴링 간격(분) | 기본값은 60분입니다. 


| 성능 폴링 간격(초) | 기본값은 60초입니다. 


| 고급 카운터 데이터 수집 | 여론조사에 ONTAP 고급 카운터 데이터를 포함하려면 이 옵션을 선택하세요. 기본적으로 활성화되어 있습니다. 


| EMS 이벤트 수집 활성화 | ONTAP EMS 로그 이벤트 데이터를 포함하려면 이것을 선택하세요. 기본적으로 활성화되어 있습니다. 


| EMS 폴링 간격(초) | 기본값은 60초입니다. 
|===


== 술어

Data Infrastructure Insights ONTAP 데이터 수집기에서 인벤토리, 로그 및 성능 데이터를 수집합니다.  인수한 각 자산 유형에 대해 해당 자산에 사용되는 가장 일반적인 용어가 표시됩니다.  이 데이터 수집기를 보거나 문제를 해결할 때 다음 용어를 염두에 두십시오.

[cols="2*"]
|===
| 공급업체/모델 용어 | Data Infrastructure Insights 용어 


| 무리 | 스토리지 


| 마디 | 스토리지노드 


| 볼륨/ FlexVol/ FlexGroup | 내부 볼륨 


| Qtree/FlexTree | Qtree (유형: Explixit/Default) 


| S3 버킷 | Qtree (유형: 버킷) 


| StoragePod/StorageAvailabilityZone | 스토리지풀 


| 공유하다 | 공유하다 


| 몫 | 몫 


| SVM(스토리지 가상 머신) | 스토리지 가상 머신 
|===


== ONTAP 데이터 관리 용어

다음 용어는 ONTAP 데이터 관리 스토리지 자산 랜딩 페이지에서 찾을 수 있는 객체나 참조에 적용됩니다.  이러한 용어의 대부분은 다른 데이터 수집자에게도 적용됩니다.



=== 스토리지

* 모델 – 이 클러스터 내의 고유하고 개별적인 노드 모델 이름을 쉼표로 구분하여 나열한 목록입니다.  클러스터의 모든 노드가 동일한 모델 유형인 경우 모델 이름은 하나만 나타납니다.
* 공급업체 – 새 데이터 소스를 구성하는 경우와 동일한 공급업체 이름입니다.
* 일련 번호 - 배열 UUID
* IP – 일반적으로 데이터 소스에 구성된 IP 또는 호스트 이름이 됩니다.
* 마이크로코드 버전 - 펌웨어.
* 원시 용량 – 역할에 관계없이 시스템의 모든 물리적 디스크의 2진 합산입니다.
* 대기 시간 - 호스트가 읽기와 쓰기 모두에서 작업 부하를 경험하는 것을 표현한 것입니다.  이상적으로는 Data Infrastructure Insights 이 가치를 직접 소싱하는 것이 좋지만, 그렇지 않은 경우가 많습니다.  이를 제공하는 배열 대신, Data Infrastructure Insights 일반적으로 개별 내부 볼륨의 통계에서 파생된 IOPS 가중치 계산을 수행합니다.
* 처리량 – 내부 볼륨에서 집계됨.  관리 – 여기에는 장치의 관리 인터페이스에 대한 하이퍼링크가 포함될 수 있습니다.  인벤토리 보고의 일부로 Data Infrastructure Insights 데이터 소스에 의해 프로그래밍 방식으로 생성되었습니다.




=== 스토리지 풀

* 저장소 – 이 풀이 어떤 저장소 배열에 있는지.  필수적인.
* 유형 – 가능성의 열거된 목록에서 나온 설명적 값입니다.  가장 일반적으로는 "집계" 또는 "RAID 그룹"입니다.
* 노드 - 이 스토리지 어레이의 아키텍처가 풀이 특정 스토리지 노드에 속하도록 되어 있는 경우, 해당 이름은 자체 랜딩 페이지로 연결되는 하이퍼링크로 여기에 표시됩니다.
* 플래시 풀 사용 – 예/아니요 값 – 이 SATA/SAS 기반 풀에 캐싱 가속에 사용되는 SSD가 있습니까?
* 중복성 – RAID 수준 또는 보호 체계.  RAID_DP는 듀얼 패리티이고, RAID_TP는 트리플 패리티입니다.
* 용량 – 여기의 값은 논리적으로 사용된 용량, 사용 가능한 용량, 논리적 총 용량, 그리고 이들에 사용된 백분율입니다.
* 과도하게 할당된 용량 – 효율성 기술을 사용하여 스토리지 풀의 논리적 용량보다 큰 볼륨 또는 내부 볼륨 용량의 총합을 할당한 경우 여기의 백분율 값은 0%보다 커집니다.
* 스냅샷 – 스토리지 풀 아키텍처가 용량의 일부를 스냅샷 전용 세그먼트 영역에 할당하는 경우 사용된 스냅샷 용량과 총 용량입니다.  MetroCluster 구성의 ONTAP 에서는 이런 현상이 나타날 가능성이 높지만, 다른 ONTAP 구성에서는 그렇지 않습니다.
* 활용도 – 이 스토리지 풀에 용량을 제공하는 모든 디스크 중 가장 높은 디스크 사용률을 나타내는 백분율 값입니다.  디스크 사용률은 반드시 어레이 성능과 강한 상관관계가 있는 것은 아닙니다. 호스트 기반 워크로드가 없는 경우 디스크 재구축, 중복 제거 활동 등으로 인해 사용률이 높을 수 있습니다.  또한 많은 어레이의 복제 구현은 내부 볼륨이나 볼륨 작업 부하로 표시되지 않으면서도 디스크 활용도를 높일 수 있습니다.
* IOPS – 이 스토리지 풀에 용량을 제공하는 모든 디스크의 합계 IOPS입니다.  처리량 – 이 스토리지 풀에 용량을 제공하는 모든 디스크의 총 처리량입니다.




=== 저장 노드

* 저장소 – 이 노드가 속한 저장소 배열입니다.  필수적인.
* HA 파트너 – 노드가 다른 노드로만 장애 조치되는 플랫폼에서 일반적으로 여기에 표시됩니다.
* 상태 - 노드의 상태.  데이터 소스에서 인벤토리를 수행할 수 있을 만큼 배열이 건강한 경우에만 사용할 수 있습니다.
* 모델 – 노드의 모델 이름.
* 버전 – 장치의 버전 이름.
* 일련 번호 – 노드 일련 번호.
* 메모리 – 가능하다면 2진수 메모리를 사용합니다.
* 활용도 – ONTAP 에서 이는 독점 알고리즘의 컨트롤러 스트레스 지수입니다.  모든 성능 폴링에서는 WAFL 디스크 경합이나 평균 CPU 사용률 중 더 높은 값을 0~100% 사이의 숫자로 보고합니다.  지속적으로 50% 이상의 값이 관찰되면 크기가 작음을 나타냅니다. 즉, 컨트롤러/노드가 충분히 크지 않거나 회전 디스크가 쓰기 작업 부하를 흡수하기에 충분하지 않을 수 있습니다.
* IOPS – 노드 개체에 대한 ONTAP REST 호출에서 직접 파생됩니다.
* 지연 시간 – 노드 개체에 대한 ONTAP REST 호출에서 직접 파생됩니다.
* 처리량 – 노드 개체에 대한 ONTAP REST 호출에서 직접 파생됩니다.
* 프로세서 - CPU 수.




== ONTAP 전력 측정

여러 ONTAP 모델은 모니터링이나 알림에 사용할 수 있는 Data Infrastructure Insights 에 대한 전력 측정 항목을 제공합니다.  아래의 지원되는 모델과 지원되지 않는 모델 목록은 포괄적이지는 않지만 어느 정도 지침을 제공합니다. 일반적으로 모델이 목록에 있는 모델과 같은 제품군에 속하면 지원도 동일합니다.

지원 모델:

A200 A220 A250 A300 A320 A400 A700 A700s A800 A900 C190 FAS2240-4 FAS2552 FAS2650 FAS2720 FAS2750 FAS8200 FAS8300 FAS8700 FAS9000

지원되지 않는 모델:

FAS2620 FAS3250 FAS3270 FAS500f FAS6280 FAS/ AFF 8020 FAS/ AFF 8040 FAS/ AFF 8060 FAS/ AFF 8080



== 문제 해결

이 데이터 수집기에 문제가 발생하면 시도해 볼 수 있는 몇 가지 사항은 다음과 같습니다.

[cols="2*"]
|===
| 문제: | 다음을 시도해 보세요: 


| ONTAP REST 데이터 수집기를 생성하려고 할 때 다음과 같은 오류가 표시됩니다. 구성: 10.193.70.14: 10.193.70.14의 ONTAP REST API를 사용할 수 없습니다. 10.193.70.14에서 /api/cluster를 GET하지 못했습니다. 400 잘못된 요청입니다. | 이는 REST API 기능이 없는 오래된 ONTAP 어레이(예: ONTAP 9.6) 때문일 가능성이 높습니다.  ONTAP 9.14.1은 ONTAP REST 수집기가 지원하는 최소 ONTAP 버전입니다.  REST ONTAP 이전 릴리스에서는 "400 잘못된 요청" 응답이 예상됩니다.  REST를 지원하지만 9.14.1 이상이 아닌 ONTAP 버전의 경우 다음과 유사한 메시지가 표시될 수 있습니다. 구성: 10.193.98.84: 10.193.98.84의 ONTAP REST API를 사용할 수 없습니다. 10.193.98.84: 10.193.98.84의 ONTAP REST API를 사용할 수 있습니다. cheryl5-cluster-2 9.10.1 a3cb3247-3d3c-11ee-8ff3-005056b364a7이지만 최소 버전 9.14.1이 아닙니다. 


| ONTAP ontapi 수집기가 데이터를 표시하는 곳에 비어 있거나 "0" 메트릭이 표시됩니다. | ONTAP REST는 ONTAP 시스템에서 내부적으로 사용되는 메트릭만 보고하지 않습니다.  예를 들어, ONTAP REST에서는 시스템 집계가 수집되지 않고, "데이터" 유형의 SVM만 수집됩니다.  0 또는 비어 있는 데이터를 보고할 수 있는 ONTAP REST 메트릭의 다른 예: InternalVolumes: REST는 더 이상 vol0을 보고하지 않습니다.  집계: REST는 더 이상 aggr0을 보고하지 않습니다.  저장: 대부분의 지표는 내부 볼륨 지표의 롤업이며 위의 내용에 영향을 받습니다.  스토리지 가상 머신: REST는 더 이상 '데이터' 이외의 유형(예: '클러스터', 'mgmt', '노드')의 SVM을 보고하지 않습니다.  기본 성능 폴링 기간이 15분에서 5분으로 변경되어 데이터가 있는 그래프의 모양이 변경된 것을 알 수도 있습니다.  여론조사를 더 자주 실시할수록 분석할 데이터 포인트가 더 많아집니다. 
|===
추가 정보는 다음에서 찾을 수 있습니다.link:concept_requesting_support.html["지원하다"] 페이지 또는link:reference_data_collector_support_matrix.html["데이터 수집기 지원 매트릭스"] .
