---
sidebar: sidebar 
permalink: task_dc_nutanix.html 
keywords: data collector, Nutanix, NX Series 
summary: Nutanix 데이터 수집기를 구성하는 중입니다. 
---
= Nutanix NX 데이터 수집기
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Data Infrastructure Insights는 Nutanix 데이터 수집기를 사용하여 Nutanix NX 스토리지 시스템의 인벤토리 및 성능 데이터를 검색합니다.



== 용어

Data Infrastructure Insights는 Nutanix 데이터 수집기에서 다음과 같은 인벤토리 정보를 수집합니다. Data Infrastructure Insights에서 구입한 각 자산 유형에 대해 이 자산에 사용되는 가장 일반적인 용어가 표시되어 있습니다. 이 데이터 수집기를 보거나 문제를 해결할 때 다음 용어를 염두에 두십시오.

[cols="2*"]
|===
| 공급업체/모델 기간 | Data Infrastructure Insights 용어 


| 스토리지 풀 | 스토리지 풀 


| Nutanix 컨테이너 | 내부 볼륨 


| Nutanix 컨테이너 | 파일 공유 


| NFS 공유 | 공유 
|===
참고: 이러한 용어 매핑은 일반적인 용어 매핑일 뿐이며 이 데이터 수집기의 모든 경우를 나타내는 것은 아닙니다.



== 요구 사항

* 클러스터의 외부 데이터 서비스 IP 주소입니다
* volume_groups를 사용하지 않는 한 읽기 전용 사용자 이름 및 암호가 필요합니다. 이 경우 Admin 사용자 이름과 암호가 필요합니다
* 포트 요구 사항: HTTPS 443




== 구성

[cols="2*"]
|===
| 필드에 입력합니다 | 설명 


| PRISM 외부 IP 주소 | 클러스터의 외부 데이터 서비스 IP 주소입니다 


| 사용자 이름입니다 | Admin 계정의 사용자 이름입니다 


| 암호 | Admin 계정의 암호입니다 
|===


== 고급 구성

[cols="2*"]
|===
| 필드에 입력합니다 | 설명 


| TCP 포트입니다 | Nutanix 어레이에 연결하는 데 사용되는 TCP 포트입니다. 기본값은 9440입니다. 


| 재고 폴링 간격(분) | 재고 조사 사이의 간격입니다. 기본값은 60분입니다. 


| 성능 폴링 간격(초) | 성능 폴링 간격입니다. 기본값은 300초입니다. 
|===


== 문제 해결

이 데이터 수집기에 대한 추가 정보는 페이지 또는 에서 찾을 link:concept_requesting_support.html["지원"]link:reference_data_collector_support_matrix.html["Data Collector 지원 매트릭스"]수 있습니다.
