---
sidebar: sidebar 
permalink: task_dc_ibm_cleversafe.html 
keywords: data collector, IBM Cleversafe 
summary: IBM Cleversafe 데이터 수집기 구성. 
---
= IBM Cleversafe 데이터 수집기
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Data Infrastructure Insights 이 데이터 수집기를 사용하여 IBM Cleversafe 스토리지 시스템의 인벤토리 및 성능 데이터를 검색합니다.


NOTE: IBM Cleversafe는 Raw TB와 Managed Unit의 요금이 다르게 책정됩니다.  포맷되지 않은 IBM Cleversafe 용량 40TB마다 1로 청구됩니다.link:concept_subscribing_to_cloud_insights.html#pricing["관리 단위(MU)"] .



== 술어

Data Infrastructure Insights IBM Cleversafe 데이터 수집기에서 다음과 같은 인벤토리 정보를 수집합니다.  Data Infrastructure Insights 에서 수집한 각 자산 유형에 대해 해당 자산에 가장 일반적으로 사용되는 용어가 표시됩니다.  이 데이터 수집기를 보거나 문제를 해결할 때 다음 용어를 염두에 두십시오.

[cols="2*"]
|===
| 공급업체/모델 용어 | Data Infrastructure Insights 용어 


| 스토리지 풀 | 스토리지 풀 


| 컨테이너 | 내부 볼륨 


| 컨테이너 | 파일 공유 


| NFS 공유 | 공유하다 
|===
참고: 이는 일반적인 용어 매핑일 뿐이며 이 데이터 수집기의 모든 사례를 나타내지 않을 수 있습니다.



== 요구 사항

* 클러스터의 외부 데이터 서비스 IP 주소
* 관리자 사용자 이름 및 비밀번호
* 포트 9440




== 구성

[cols="2*"]
|===
| 필드 | 설명 


| 관리자 IP 또는 호스트 이름 | 관리 노드의 IP 주소 또는 호스트 이름 


| 사용자 이름 | 슈퍼 유저 또는 시스템 관리자 역할을 가진 사용자 계정의 사용자 이름 


| 비밀번호 | 슈퍼 유저 또는 시스템 관리자 역할을 가진 사용자 계정의 비밀번호 
|===


== 고급 구성

[cols="2*"]
|===
| 필드 | 설명 


| 재고 폴링 간격(분) | 재고 조사 간격. 


| HTTP 연결 시간 초과(초) | HTTP 시간 초과(초) 
|===


== 문제 해결

이 데이터 수집기에 대한 추가 정보는 다음에서 찾을 수 있습니다.link:concept_requesting_support.html["지원하다"] 페이지 또는link:reference_data_collector_support_matrix.html["데이터 수집기 지원 매트릭스"] .
