---
sidebar: sidebar 
permalink: task_query_assign_multiple_applications.html 
summary: 쿼리를 사용하여 여러 애플리케이션이나 주석을 개체에 할당하거나 개체에서 여러 애플리케이션이나 주석을 제거합니다. 
keywords: query, queries, application, annotation, multiple 
---
= 자산에 여러 애플리케이션을 할당하거나 자산에서 여러 애플리케이션을 제거합니다.
:hardbreaks:
:allow-uri-read: 


[role="lead"]
여러 개를 할당할 수 있습니다link:task_create_application.html["응용 프로그램"] 수동으로 애플리케이션을 할당하거나 제거하는 대신 쿼리를 사용하여 자산에서 여러 애플리케이션을 제거하거나 할당할 수 있습니다.


NOTE: 다음 단계를 사용하여 추가하거나 제거할 수 있습니다.link:task_defining_annotations.html["주석"] 같은 방법으로.

.시작하기 전에
편집하려는 모든 자산을 찾는 쿼리를 이미 만들었을 것입니다.

.단계
. *탐색*을 클릭하고 *메트릭 쿼리*를 선택합니다.
+
쿼리 페이지가 표시됩니다.

. 자산을 찾는 쿼리의 이름을 클릭합니다.
+
쿼리와 관련된 자산 목록이 표시됩니다.

. 목록에서 원하는 자산을 선택하거나 상단의 확인란을 클릭하여 모두를 선택하세요.
+
대량 작업 드롭다운이 표시됩니다.

. 선택한 자산에 애플리케이션을 추가하려면 대량 작업을 클릭하고 *애플리케이션 추가*를 선택합니다.
. 하나 이상의 애플리케이션을 선택하세요.
+
호스트, 내부 볼륨, Q트리, 가상 머신에 대해 여러 애플리케이션을 선택할 수 있습니다. 그러나 볼륨이나 공유에 대해서는 하나의 애플리케이션만 선택할 수 있습니다.

. *저장*을 클릭하세요.
. 자산에 할당된 애플리케이션을 제거하려면 대량 작업을 클릭하고 *애플리케이션 제거*를 선택하세요.
. 제거하려는 애플리케이션을 선택하세요.
. *삭제*를 클릭하세요.


새로 할당한 모든 애플리케이션은 다른 자산에서 파생된 자산의 모든 애플리케이션을 재정의합니다.  예를 들어, 볼륨은 호스트로부터 애플리케이션을 상속받으며, 볼륨에 새 애플리케이션이 할당되면 새 애플리케이션이 파생된 애플리케이션보다 우선합니다.

대량 추가 작업에서 _저장_을 클릭하거나 대량 삭제 작업에서 _제거_를 클릭하면 Data Infrastructure Insights 해당 작업에 시간이 걸린다는 알림을 표시합니다.  이 메시지를 무시해도 됩니다. 작업은 백그라운드에서 계속 진행됩니다.


NOTE: 관련 자산이 대량으로 있는 환경의 경우 해당 자산에 대한 애플리케이션 할당을 상속하는 데 몇 분이 걸릴 수 있습니다.  관련 자산이 많은 경우 상속이 이루어지는 데 더 많은 시간이 소요될 수 있습니다.
