---
sidebar: sidebar 
permalink: task_dc_emc_vnx_file.html 
keywords: data collector, Celerra, EMC, DELL, VNX File 
summary: DELL EMC Celerra 데이터 수집기 구성. 
---
= DELL EMC VNX 파일(이전 Celerra Unified Storage System) 데이터 수집기
:hardbreaks:
:allow-uri-read: 


[role="lead"]
이 데이터 수집기는 VNX 파일 스토리지 시스템에서 인벤토리 정보를 수집합니다.  구성을 위해 이 데이터 수집기에는 스토리지 프로세서의 IP 주소와 읽기 전용 사용자 이름과 비밀번호가 필요합니다.



== 술어

Data Infrastructure Insights VNX 파일 데이터 수집기에서 다음과 같은 인벤토리 정보를 수집합니다.  Data Infrastructure Insights 에서 수집한 각 자산 유형에 대해 해당 자산에 가장 일반적으로 사용되는 용어가 표시됩니다.  이 데이터 수집기를 보거나 문제를 해결할 때 다음 용어를 염두에 두십시오.

[cols="2*"]
|===
| 공급업체/모델 용어 | Data Infrastructure Insights 용어 


| Celerra 네트워크 서버/Celerra 스토리지 풀 | 스토리지 풀 


| 파일 시스템 | 내부 볼륨 


| 데이터 무버 | 제어 장치 


| 데이터 무버에 마운트된 파일 시스템 | 파일 공유 


| CIFS 및 NFS 내보내기 | 공유하다 


| 디스크 볼륨 | 백엔드 LUN 
|===
참고: 이는 일반적인 용어 매핑일 뿐이며 이 데이터 수집기의 모든 사례를 나타내지 않을 수 있습니다.



== 요구 사항

이 데이터 수집기를 구성하려면 다음이 필요합니다.

* 저장 프로세서의 IP 주소
* 읽기 전용 사용자 이름 및 비밀번호
* SSH 포트 22




== 구성

[cols="2*"]
|===
| 필드 | 설명 


| VNX 파일 IP 주소 | VNX 파일 장치의 IP 주소 또는 정규화된 도메인 이름 


| 사용자 이름 | VNX 파일 장치에 로그인하는 데 사용되는 이름 


| 비밀번호 | VNX 파일 장치에 로그인하는 데 사용되는 비밀번호 
|===


== 고급 구성

[cols="2*"]
|===
| 필드 | 설명 


| 재고 폴링 간격(분) | 재고 조사 간격. 기본값은 20분입니다. 
|===


== 문제 해결

이 데이터 수집기에 문제가 발생하면 시도해 볼 수 있는 몇 가지 사항은 다음과 같습니다.



=== 목록

[cols="2*"]
|===
| 문제: | 다음을 시도해 보세요: 


| 오류: DART 업데이트가 진행 중이므로 진행할 수 없습니다. | 가능한 해결책: 데이터 수집기를 일시 중지하고 DART 업그레이드가 완료될 때까지 기다린 후 다른 수집 요청을 시도합니다. 
|===
추가 정보는 다음에서 찾을 수 있습니다.link:concept_requesting_support.html["지원하다"] 페이지 또는link:reference_data_collector_support_matrix.html["데이터 수집기 지원 매트릭스"] .
