---
sidebar: sidebar 
permalink: task_dc_emc_xio.html 
keywords: data collector, XtremeIO, EMC 
summary: XtremeIO 데이터 수집기 구성. 
---
= Dell EMC XtremeIO 데이터 수집기
:hardbreaks:
:allow-uri-read: 


[role="lead"]
EMC XtremIO 데이터 수집기는 EMC XtremIO 스토리지 시스템에서 인벤토리 및 성능 데이터를 수집합니다.



== 요구 사항

EMC XtremIO(HTTP) 데이터 수집기를 구성하려면 다음이 필요합니다.

* XtremIO 관리 서버(XMS) 호스트 주소
* 관리자 권한이 있는 계정
* 포트 443(HTTPS)에 접속




== 술어

Data Infrastructure Insights EMC XtremIO 데이터 수집기에서 다음과 같은 인벤토리 정보를 수집합니다.  Data Infrastructure Insights 에서 수집한 각 자산 유형에 대해 해당 자산에 가장 일반적으로 사용되는 용어가 표시됩니다.  이 데이터 소스를 보거나 문제를 해결할 때 다음 용어를 염두에 두세요.

[cols="2*"]
|===
| 공급업체/모델 용어 | Data Infrastructure Insights 용어 


| 디스크(SSD) | 디스크 


| 무리 | 스토리지 


| 제어 장치 | 저장 노드 


| 용량 | 용량 


| LUN 맵 | 볼륨 맵 


| 타겟 FC 이니시에이터 | 볼륨 마스크 
|===
참고: 이는 일반적인 용어 매핑일 뿐이며 이 데이터 소스의 모든 사례를 나타내지 않을 수 있습니다.



== 요구 사항

* XtremIO 관리 서버(XMS) 호스트 IP 주소
* XtremIO의 관리자 사용자 이름 및 비밀번호




== 구성

[cols="2*"]
|===
| 필드 | 설명 


| XMS 호스트 | XtremIO 관리 서버의 IP 주소 또는 정규화된 도메인 이름 


| 사용자 이름 | XtremIO 관리 서버의 사용자 이름 


| 비밀번호 | XtremIO 관리 서버의 비밀번호 
|===


== 고급 구성

[cols="2*"]
|===
| 필드 | 설명 


| TCP 포트 | XTremIO 관리 서버에 연결하는 데 사용되는 TCP 포트입니다.  기본값은 443입니다. 


| 재고 폴링 간격(분) | 재고 조사 간격. 기본값은 60분입니다. 


| 성능 폴링 간격(초) | 성과 여론조사 간격. 기본값은 300초입니다. 
|===


== 문제 해결

이 데이터 수집기에 대한 추가 정보는 다음에서 찾을 수 있습니다.link:concept_requesting_support.html["지원하다"] 페이지 또는link:reference_data_collector_support_matrix.html["데이터 수집기 지원 매트릭스"] .
