---
sidebar: sidebar 
permalink: task_dc_emc_ecs.html 
keywords: data collector, ecs, EMC 
summary: ECS 데이터 수집기 구성. 
---
= EMC ECS 데이터 수집기 구성
:hardbreaks:
:allow-uri-read: 


[role="lead"]
이 데이터 수집기는 EMC ECS 스토리지 시스템에서 인벤토리 및 성능 데이터를 수집합니다.  구성을 위해 데이터 수집기에는 ECS 클러스터의 IP 주소 또는 호스트 이름과 사용자 이름 및 비밀번호가 필요합니다.


NOTE: Dell EMC ECS는 Raw TB와 Managed Unit의 요금이 다르게 책정됩니다.  포맷되지 않은 ECS 용량 40TB마다 1로 청구됩니다.link:concept_subscribing_to_cloud_insights.html#pricing["관리 단위(MU)"] .



== 술어

Data Infrastructure Insights ECS 데이터 수집기에서 다음과 같은 인벤토리 정보를 수집합니다.  인수한 각 자산 유형에 대해 해당 자산에 사용되는 가장 일반적인 용어가 표시됩니다.  이 데이터 수집기를 보거나 문제를 해결할 때 다음 용어를 염두에 두십시오.

[cols="2*"]
|===
| 공급업체/모델 용어 | Data Infrastructure Insights 용어 


| 무리 | 스토리지 


| 거주자 | 스토리지 풀 


| 버킷 | 내부 볼륨 


| 디스크 | 디스크 
|===
참고: 이는 일반적인 용어 매핑일 뿐이며 이 데이터 수집기의 모든 사례를 나타내지 않을 수 있습니다.



== 요구 사항

* ECS 클러스터의 IP 주소 또는 호스트 이름
* ECS 시스템의 사용자 이름과 비밀번호
* 포트 4443(HTTPS).  ECS 시스템의 TCP 포트 4443에 대한 아웃바운드 연결이 필요합니다.




== 구성

[cols="2*"]
|===
| 필드 | 설명 


| ECS 호스트 | ECS 시스템의 IP 주소 또는 정규화된 도메인 이름 


| ECS 호스트 포트 | ECS 호스트와 통신하는 데 사용되는 포트 


| ECS 사용자 ID | ECS 사용자 ID 


| 비밀번호 | ECS에 사용되는 비밀번호 
|===


== 고급 구성

[cols="2*"]
|===
| 필드 | 설명 


| 재고 폴링 간격(분) | 기본값은 360분입니다. 
|===


== 문제 해결

이 데이터 수집기에 문제가 발생하면 시도해 볼 수 있는 몇 가지 사항은 다음과 같습니다.



=== 목록

[cols="2*"]
|===
| 문제: | 다음을 시도해 보세요: 


| 오류: 사용자 인증에 실패했습니다. | 이 장치에 대한 자격 증명이 올바른지 확인하세요. 
|===


=== 성능

[cols="2*"]
|===
| 문제: | 다음을 시도해 보세요: 


| 오류: 수집된 데이터가 충분하지 않습니다. | * 로그 파일에서 수집 타임스탬프를 확인하고 폴링 간격을 적절히 수정합니다. * 더 오랜 시간 동안 기다립니다. 


| 오류: 성능 폴링 간격이 너무 큽니다. | 로그 파일 ${logfile}에서 수집 타임스탬프를 확인하고 폴링 간격을 적절히 수정합니다. 
|===
추가 정보는 다음에서 찾을 수 있습니다.link:concept_requesting_support.html["지원하다"] 페이지 또는link:reference_data_collector_support_matrix.html["데이터 수집기 지원 매트릭스"] .
