---
sidebar: sidebar 
permalink: ws_audit_events.html 
summary: Workload Security의 감사 이벤트 
keywords: workload security, audit, events 
---
= Workload Security 이벤트 감사
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


예상되는 변경 사항(추적용)과 예상치 못한 변경 사항(문제 해결용)을 모두 식별합니다. Workload Security 시스템 이벤트 및 사용자 활동에 대한 감사 추적 기록을 볼 수 있습니다.



== 감사된 이벤트 보기

감사 페이지를 보려면 메뉴에서 Admin > Audit를 클릭하십시오. 감사 페이지가 표시되며 각 감사 항목에 대한 다음 세부 정보가 제공됩니다.

* 시간 - 이벤트 또는 활동의 날짜 및 시간
* 사용자 - 활동을 시작한 사용자
* 역할 - Workload Security에서 사용자의 역할(게스트, 사용자, 관리자)
* IP - 이벤트와 연결된 IP 주소
* 작업 - 활동 유형(예: Login, Create, Update)
* 범주 - 활동의 범주입니다.
* 세부 정보 - 활동에 대한 세부 정보
* 애플리케이션 유형 - 감사 대상 애플리케이션 유형: Observability 또는 Workload Security. Workload Security 감사만 필터링하는 데 사용합니다.


감사되는 Workload Security 이벤트에는 다음이 포함되지만 이에 국한되지는 않습니다.

* Workload Security 정책 변경 사항.
* 새로운 Data Source Collector(DSC) 생성.
* DSC 수정.
* 에이전트 생성.
* 사용자 관리 작업.
* API 토큰 작업.




== 감사 항목 표시

감사 항목을 보는 방법에는 여러 가지가 있습니다.

* 특정 기간(1시간, 24시간, 3일 등)을 선택하여 감사 항목을 표시할 수 있습니다.
* 열 머리글의 화살표를 클릭하면 항목의 정렬 순서를 오름차순(위쪽 화살표) 또는 내림차순(아래쪽 화살표)으로 변경할 수 있습니다. 기본적으로 표는 시간 내림차순으로 항목을 표시합니다.
* 필터 필드를 사용하면 표에 원하는 항목만 표시할 수 있습니다.  추가 필터를 추가하려면 [+] 버튼을 클릭하세요.




== 필터링에 대한 추가 정보

다음 중 하나를 사용하여 필터를 구체화할 수 있습니다.

|===


| 필터 | 그것이 하는 일 | 예 | 결과 


| * (별표) | 모든 것을 검색할 수 있습니다 | 볼*렐 | "vol"로 시작하고 "rhel"로 끝나는 모든 리소스를 반환합니다. 


| ?  (물음표) | 특정 수의 문자를 검색할 수 있습니다 | BOS-PRD??-S12 | BOS-PRD12-S12, BOS-PRD23-S12 등을 반환합니다 


| 또는 | 여러 엔터티를 지정할 수 있습니다. | FAS2240 또는 CX600 또는 FAS3270 | FAS2440, CX600 또는 FAS3270 중 하나를 반환합니다. 


| 아니다 | 검색 결과에서 텍스트를 제외할 수 있습니다. | EMC가 아닙니다* | "EMC"로 시작하지 않는 모든 항목을 반환합니다. 


| None | 선택된 모든 필드에서 공백/NULL/없음을 검색합니다. | None | 대상 필드가 비어 있지 않은 결과를 반환합니다. 


| 아니다 * | 위의 None과 마찬가지로, 이 형식을 사용하여 텍스트 전용 필드에서 NULL 값을 검색할 수도 있습니다. | 아니다 * | 대상 필드가 비어 있지 않은 결과를 반환합니다. 


| "" | 정확한 일치 항목을 검색합니다 | "NetApp*" | NetApp*라는 정확한 문자열을 포함하는 결과를 반환합니다 
|===
필터 문자열을 큰따옴표로 묶으면 Insight는 첫 번째 따옴표와 마지막 따옴표 사이의 모든 내용을 정확한 일치로 처리합니다.  따옴표 안의 특수 문자나 연산자는 리터럴로 처리됩니다.  예를 들어, "*"로 필터링하면 별표 문자가 반환됩니다. 이 경우 별표는 와일드카드로 처리되지 않습니다.  OR 및 NOT 연산자도 큰따옴표로 묶으면 문자열로 처리됩니다.



== 감사된 이벤트 및 작업

Workload Security에서 감사하는 이벤트 및 작업은 다음과 같은 광범위한 영역으로 분류할 수 있습니다.

* 사용자 계정: 로그인, 로그아웃, 역할 변경 등
* 에이전트: 생성, 삭제, 업그레이드, 고정, 고정 해제 등
+
예: _Agent Agent-Boston-1이 삭제되었습니다._ _일괄 작업으로 시작된 버전 1.760.0으로 Agent 업그레이드_

* 데이터/사용자 디렉터리 수집기: 추가, 제거, 수정, 업그레이드, 연기/재개, 에이전트 변경, 재시작 등
+
예: _Data collector Collector-Boston1 제거됨, 유형 ONTAP SVM_ _Agent: Agent-Boston-1, Cluster IP 10.193.88.36, SVM demoGroupShares2_ _Collector ONTAP SVM 대량 작업으로 버전 1.417.0으로 업그레이드 시작_

* 자동 응답 정책: 추가, 업데이트, 제거, 활성화, 비활성화 등
+
예시: _자동화된 공격 정책 Policy-Boston1이 업데이트되었습니다. 속성 Devices가 업데이트되었습니다, 이전 값: [Device(name=svm_boston1, dataSourceId=39fb3b9c-9dd4-4961-bc27-23eb0b6f9ab7)], 새 값: [Device(name=demoGroupShares2, dataSourceId=5b9f5b74-4533-4852-909d-8886582a4359)]_

* 사용자 차단/차단 해제: 자동 또는 수동 사용자 차단 및 차단 해제.
+
예: _2시간 동안 자동 응답의 일환으로 사용자 Safwan Langley에 대해 차단이 시작되었습니다_

* Apikey: 추가, 제거 등
+
예: _Workload Security API 액세스 토큰 JPick-SWS가 생성되었습니다_

* 알림: 이메일 변경 등
+
예: _Recipient ci-alerts-notifications-dl created_





== 감사 이벤트 내보내기

감사 결과를 .CSV 파일로 내보내어 데이터를 분석하거나 다른 애플리케이션으로 가져올 수 있습니다. 단계 1. 감사 페이지에서 원하는 시간 범위와 필터를 설정합니다. Workload Security는 설정한 필터링 및 시간 범위와 일치하는 감사 항목만 내보냅니다. 2. 표 오른쪽 상단의 내보내기 버튼을 클릭합니다. 표시된 감사 이벤트가 최대 10,000행까지 .CSV 파일로 내보내집니다.



== 감사 데이터 보존

Workload Security에서 감사 데이터를 보존하는 기간은 구독 유형에 따라 다릅니다.

* 시험 환경: 감사 데이터는 30일 동안 보관됩니다.
* 구독 환경: 감사 데이터는 1년 + 1일 동안 보관됩니다.


보존 기간보다 오래된 감사 항목은 자동으로 삭제됩니다.  사용자 상호 작용이 필요하지 않습니다.
